### ISSUE TITLE
tree dont work: No query for results

### ISSUE THREAD

**Issue by edukmattos** [staudenmeir/laravel-adjacency-list#1]
HI !
Im using your package and the Trait tree dont work !

In my case $tree = CompanySector::tree()->get();
error: "No query results for Model CompanySector.

The other features are ok

**Comment by Tickthokk** [comment]
I was having this same issue. It looks like they require `parent_id`s to be `NULL`. 

I was using `0` as my root identifier, but on reflection I did some testing and switched to use NULL over zero.

Hope this helps someone else!

**Comment by WillieOng-HK** [comment]
can it set 0 as the root identifier? because it's limited by another front-end plugins. Thanks.

**Comment by staudenmeir** [comment]
@WillieOng-HK Take a look at the `treeOf()` scope: https://github.com/staudenmeir/laravel-adjacency-list#trees

```php
$constraint = function ($query) {
    $query->where('parent_id', 0);
};

$tree = User::treeOf($constraint)->get();
```
