### ISSUE TITLE
Getting Descendant of Ancestor with Descendant in a single query

### ISSUE THREAD

**Issue by soundar8562** [staudenmeir/laravel-adjacency-list#10]
Hello,
Here you can see my ancestor and descendant table,
**Ancestor | Descendant**
Electronics | Computer
Electronics | Laptop
Electronics | Mobile phone

**Here is my code,**
$descendants = Category::find($id)->descendants()->whereDepth(1)->get();
foreach ($descendants as $value) {
echo $value->name;
$ancestor=Category::find($value->id)->ancestors;
echo $ancestor[0]->name;
}
}

**Question:**
As of right now, this works fine, but there will be a lot of queries if I handle some large amount of data, so is there any way to get the descendant of the ancestor with a descendant from a single query?

Thanks

**Comment by staudenmeir** [comment]
Please post the table schema and the `Category` model.

**Comment by soundar8562** [comment]
Hello, sorry I was on vacation,
**Schema:**
public function up()
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->integer('parent_id')->nullable()->unsigned();
            $table->timestamps();
        });
        Schema::table('categories', function($table) {
            $table->foreign('parent_id')
                  ->references('id')->on('categories')
                  ->onUpdate('cascade')
                  ->onDelete('cascade');
        });
    }

**Category model**
namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;
    
    protected $fillable = ['name','parent_id'];

    public function getParentKeyName()
    {
        return 'parent_id';
    }
 
}

**Comment by staudenmeir** [comment]
Do you mean eager loading?

```php
$descendants = Category::find($id)->descendants()->whereDepth(1)->with('ancestors')->get();
```

**Comment by soundar8562** [comment]
Yes, that's what I want.
The code above is not working :)

**Comment by staudenmeir** [comment]
What's the error?

**Comment by soundar8562** [comment]
![image](https://user-images.githubusercontent.com/54890548/69516368-72d04c80-0f77-11ea-944c-148a8e9c92f8.png)

**Comment by soundar8562** [comment]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'laravel_cte.id' in 'where clause' (SQL: with recursive `laravel_cte` as ((select *, -1 as `depth`, cast(`id` as char(65535)) as `path` from `categories` where `laravel_cte`.`id` in (1)) union all (select `categories`.*, `depth` - 1 as `depth`, concat(`path`, '.', `categories`.`id`) from `categories` inner join `laravel_cte` on `laravel_cte`.`parent_id` = `categories`.`id`)) select * from `laravel_cte`)

**Comment by staudenmeir** [comment]
I'll look into it.

In your specific case, you can actually use the `children` relationship:

```php
$descendants = Category::find($id)->children()->with('ancestors')->get();
```

**Comment by soundar8562** [comment]
Thanks for the code, it works at the same parent level, but I have to do this for every parent. We are using whereDepth() to get this right now. It could be great if you look into the previous error.

**Comment by soundar8562** [comment]
Hello there, I hope you are well!
I am still trying to get the ancestors of descendants any help from your end plz?
Thanks

**Comment by staudenmeir** [comment]
I'm working on fix a for the eager loading issue.

**Comment by soundar8562** [comment]
Thank you so much :)

**Comment by soundar8562** [comment]
Any updates for the eager loading?

**Comment by staudenmeir** [comment]
I'm still working on it.

**Comment by staudenmeir** [comment]
I've released a new version that fixes this issue.

**Comment by soundar8562** [comment]
Awesome Thanks
I am gonna try this out :)

**Comment by soundar8562** [comment]
Thank you so much, it works like a charm and I'm excited to know what you did to make it happen.

**Comment by staudenmeir** [comment]
The necessary change was rather small: https://github.com/staudenmeir/laravel-adjacency-list/commit/f232d4f033dfc5f1084d3543648b6c6119fb62be
