### ISSUE TITLE
User Model Query duplication without calling anything from HasRecursiveRelationships class

### ISSUE THREAD

**Issue by denizgolbas** [staudenmeir/laravel-adjacency-list#102]
Hello,

```
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;


    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'role_id',
        'lang_id',
        'password',
        'name',
        'surname',
        'email',
        'reference_code',
        'reference_id'
        ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];



    //Relations
    public function role()
    {
        return $this->belongsTo(Role::class, 'role_id', 'id');
    }
    public function language()
    {
        return $this->belongsTo(Language::class, 'lang_id', 'id');
    }
    public function codes()
    {
        return $this->hasMany(ReferenceCode::class, 'user_id', 'id');
    }
    public function nfts()
    {
        return $this->hasMany(NFT::class, 'owner_id', 'id');
    }
    public function reference()
    {
        return $this->belongsTo(self::class, 'reference_id','id');
    }

    public function contacts()
    {
        return $this->hasMany(ContactMessages::class, 'handler_id', 'id');
    }

  

    //Mutators
    public function email_unverify(){
        $this->email_verified_at = null;
        return $this->save();
    }




  


    public function getParentKeyName()
    {
        return 'reference_id';
    }

  
}
```

This is my user model. I use descendants() just a particular page. But instead of this page i see HasRecursiveRelationships class triggered by every User::find(id) queries. 

<img width="1440" alt="Screen Shot 2022-04-28 at 19 08 00" src="https://user-images.githubusercontent.com/27892099/165796490-e61ad3aa-3b83-485a-96c7-409aac0a569d.png">

**Comment by staudenmeir** [comment]
In models that use the package's `HasRecursiveRelationships` trait, it has to override the default Eloquent query builder class so it can do its job:

https://github.com/staudenmeir/laravel-adjacency-list/blob/c39224c118cf9354425c1113ba8c04c4fccb9ce4/src/Eloquent/Traits/HasAdjacencyList.php#L399-L402

Because of this, the package's builder class is used for _all_ of the model's queries – even if you are not executing recursive queries. This doesn't cause any performance issues.

**Comment by denizgolbas** [comment]
> In models that use the package's `HasRecursiveRelationships` trait, it has to override the default Eloquent query builder class so it can do its job:
> 
> https://github.com/staudenmeir/laravel-adjacency-list/blob/c39224c118cf9354425c1113ba8c04c4fccb9ce4/src/Eloquent/Traits/HasAdjacencyList.php#L399-L402
> 
> Because of this, the package's builder class is used for _all_ of the model's queries – even if you are not executing recursive queries. This doesn't cause any performance issues.

Thanks for your info
