### ISSUE TITLE
withCount('decendants) Error with MySQL

### ISSUE THREAD

**Issue by denizgolbas** [staudenmeir/laravel-adjacency-list#105]
My eloquent raw query is at below:
``
select `users`.*, (select sum(`commission_payments`.`amount`) from `commission_payments` inner join `commission_weeklies` on `commission_weeklies`.`id` = `commission_payments`.`id` where `users`.`id` = `commission_weeklies`.`user_id`) as `payments_sum_amount`, (select count(*) from `n_f_t_s` inner join `favorites` on `n_f_t_s`.`id` = `favorites`.`nft_id` where `users`.`id` = `favorites`.`user_id`) as `favorite_nfts_count`, (select count(*) from `n_f_t_s` inner join `stars` on `n_f_t_s`.`id` = `stars`.`nft_id` where `users`.`id` = `stars`.`user_id`) as `star_nfts_count`, (with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `users` as `laravel_reserved_0` where `laravel_reserved_0`.`reference_id` = `users`.`id`) union all (select `laravel_reserved_0`.*, `depth` + 1 as `depth`, concat(`path`, ., `laravel_reserved_0`.`id`) from `users` as `laravel_reserved_0` inner join `laravel_cte` on `laravel_cte`.`id` = `laravel_reserved_0`.`reference_id`)) select count(*) from `laravel_cte`) as `descendants_count` from `users` where `id` = 1 limit 1
``

This query works on pgSQL (pgsql-12.4). But when I run it at mySQL(mariadb-10.5) i see '“SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause"' this error. 

Eloquent query:

`        $user = User::withCount('descendants')
->withSum('payments', 'amount')
        ->with(['commission_weekly'=>function($query) {
            return $query->select('id', 'user_id', 'total_amount', 'created_at')->latest('id')->limit(10);
        }])
        ->with(['favorite_nfts'=>function($query) {
            return $query->with('image', 'collection.currency')->limit(4);
        }])
        ->withCount('favorite_nfts')
        ->with(['star_nfts'=>function($query) {
            return $query->with('image', 'collection.currency')->limit(4);
        }])
        ->withCount('star_nfts')
        ->where('id', Auth::user()->id)->first();`

**Comment by staudenmeir** [comment]
Unfortunately, MariaDB doesn't support this kind of query yet:
https://jira.mariadb.org/browse/MDEV-19077

**Comment by denizgolbas** [comment]
> Unfortunately, MariaDB doesn't support this kind of query yet:
> https://jira.mariadb.org/browse/MDEV-19077

I tried change mariadb to mysql8.0. It works well. Thank you for information.

**Comment by denizgolbas** [comment]
> Unfortunately, MariaDB doesn't support this kind of query yet:
> https://jira.mariadb.org/browse/MDEV-19077

I tried change mariadb to mysql8.0. It works well. Thank you for information.
