### ISSUE TITLE
Sum of descendants' related table's sums column

### ISSUE THREAD

**Issue by denizgolbas** [staudenmeir/laravel-adjacency-list#106]
```
User::where('id', 1)->withSum(['descendants' => function($query) {
        return $query->whereDepth('<', 10)->depthFirst()->withSum('nfts', 'price');
 }],'nfts_sum_price')->first();
```

When I write 'id' or 'depth' instead of "nfts_sum_price", query is work well. But with "nfts_sum_price", I take "Undefined column" error. 

Is "sum of descendants' related table's sums column at 1 query" possible for this package? If it is possible how is the query?

I'am trying this query because at test server we have 20k users rows. 

When I try: 
```
$test = User::where('id', 1)->with(['descendants' => function($query) {
        return $query->whereDepth('<', 10)->depthFirst()->withSum('nfts', 'price');
 }],'nfts_sum_price')->first();

$sum = $test->descendants->sum('nfts_sum_price')
```

It works but I see at laravel debug bar 20k user models is load for just "head user" of list. I need directly just sum of related table sums. 

Do you have a suggestion?

Thanks.

**Comment by staudenmeir** [comment]
Can you share the whole error message? What database are you using?

**Comment by denizgolbas** [comment]
**Database:** pgsql-12.4

**Query:**
```
        $t = User::where('id', 1)->withSum(['descendants' => function($query) {
            return $query->whereDepth('<', 10)->depthFirst()->withSum('nfts', 'price');
        }], 'nfts_sum_price')->first();
```

**Error:**
```
Illuminate\Database\QueryException
SQLSTATE[42703]: Undefined column: 7 ERROR: column laravel_cte.nfts_sum_price does not exist LINE 1: ... "laravel_reserved_1"."reference_id")) select sum("laravel_c... ^
```

`select "users".*, (with recursive "laravel_cte" as ((select *, 1 as "depth", array["id"] as "path" from "users" as "laravel_reserved_1" where "laravel_reserved_1"."reference_id" = "users"."id") union all (select "laravel_reserved_1".*, "depth" + 1 as "depth", "path" || "laravel_reserved_1"."id" from "users" as "laravel_reserved_1" inner join "laravel_cte" on "laravel_cte"."id" = "laravel_reserved_1"."reference_id")) select sum("laravel_cte"."nfts_sum_price") from "laravel_cte" where "depth" < 10) as "descendants_sum_nfts_sum_price" from "users" where "id" = 1 limit 1
`

**Relation method:**
```
  public function nfts()
    {
        return $this->hasMany(NFT::class, 'owner_id', 'id');
    }
```

**Comment by staudenmeir** [comment]
Try a [`HasManyOfDescendants`](https://github.com/staudenmeir/laravel-adjacency-list#hasmanyofdescendants) relationship:

```php
class User extends Model
{
    public function descendantNfts()
    {
        return $this->hasManyOfDescendants(NFT::class, 'owner_id', 'id');
    }
}

$t = User::where('id', 1)->withSum(['descendantNfts' => function($query) {
    $query->whereDepth('<', 10);
}], 'price')->first();
```

**Comment by denizgolbas** [comment]
> ```
>     public function descendantNfts()
>     {
>         return $this->hasManyOfDescendants(NFT::class, 'owner_id', 'id');
>     }
> ```


I see error like that:
`SQLSTATE[42703]: Undefined column: 7 ERROR: column "depth" does not exist LINE 1: ...elect sum("n_f_t_s"."price") from "n_f_t_s" where "depth" = ... ^`
`select "users".*, (with recursive "laravel_cte" as ((select *, 1 as "depth" from "users" as "laravel_reserved_1" where "laravel_reserved_1"."reference_id" = "users"."id") union all (select "users".*, "depth" + 1 as "depth" from "users" inner join "laravel_cte" on "laravel_cte"."id" = "users"."reference_id")) select sum("n_f_t_s"."price") from "n_f_t_s" where "depth" = < and "n_f_t_s"."owner_id" in (select "id" from "laravel_cte")) as "descendant_nfts_sum_price" from "users" where "id" = 1 limit 1`

But it is work without  "$query->whereDepth('<', 10);"

**Comment by staudenmeir** [comment]
What version of the package are you using?

**Comment by denizgolbas** [comment]
> What version of the package are you using?

staudenmeir/laravel-adjacency-list   v1.10.3 Recursive Laravel Eloquent relationships with CTEs
staudenmeir/laravel-cte              v1.6.2  Laravel queries with common table expressions

**Comment by denizgolbas** [comment]
> You actually need to use an intermediate scope:
> 
> ```
> class User extends Model
> {
>     public function descendantNfts()
>     {
>         return $this->hasManyOfDescendants(NFT::class, 'owner_id', 'id')
>                     ->withIntermediateScope(
>                         'depth',
>                         function ($query) {
>                             $query->whereDepth('<', 10);
>                         }
>                     );
>     }
> }
> 
> $t = User::where('id', 1)->withSum('descendantNfts', 'price')->first();
> ```

You are amazing, thank you very much for your work.
