### ISSUE TITLE
Self Referencing Polymorphic instead of Parent ID?

### ISSUE THREAD

**Issue by panthro100** [staudenmeir/laravel-adjacency-list#107]
Instead of having `parent_id`, is this package able to use a polymorphic relationship to self reference?

For example, a comment system. A `comment` could `morphTo` a `post` or `comment` (a reply).

Inversely the `comment` would `morphMany` `comments` and `posts`.

Is this possible?

**Comment by staudenmeir** [comment]
Can you share the `Comment` model, the `comments` migration and some sample rows?

**Comment by staudenmeir** [comment]
Thanks. What kind of queries would you want to run on this structure?

- Get all comments of a post recursively?
- Get all replies to a comment recursively?

**Comment by panthro100** [comment]
What you mentioned would be useful.

I would like to get all comments for a `post` including all `decedents` to a tree. I have this set up using the `parent_id` method at the minute but was wondering if this could be achieved using a self referencing polymorphic relationship.

**Comment by staudenmeir** [comment]
You can get the recursive comments of a post like this:

```php
class Comment extends Model
{
    use HasRecursiveRelationships;

    public function getParentKeyName()
    {
        return 'commentable_id';
    }
}

$tree = Comment::withRecursiveQueryConstraint(function ($query) {
    $query->where('commentable_type', Comment::class);
}, function () use ($post) {
    return Comment::treeOf(
        function ($query) use ($post) {
            $query->where('commentable_id', $post->id)
                  ->where('commentable_type', $post::class);
        }
    )->get();
});
```

You can get the recursive replies to a comment like this:

```php
class Comment extends Model
{
    use HasRecursiveRelationships;

    public function getParentKeyName()
    {
        return 'commentable_id';
    }
}

$replies = Comment::withRecursiveQueryConstraint(function ($query) {
    $query->where('commentable_type', Comment::class);
}, function () use ($comment) {
    return $comment->descendants;
});
```

**Comment by panthro100** [comment]
@staudenmeir thank you for that, I will try that out.

Is it possible to wrap the `withRecursiveQueryConstraint` in a relationship so I can use it with Laravel Query Builder?

**Comment by staudenmeir** [comment]
In your case, it should be possible to add the constraint to all recursive queries:

```php
class Comment extends Model
{
    use HasRecursiveRelationships;

    public function getParentKeyName()
    {
        return 'commentable_id';
    }

    protected static function booted()
    {
        static::$recursiveQueryConstraint = function ($query) {
            $query->where('comments.commentable_type', static::class);
        };
    }
}

$tree =  Comment::treeOf(
    function ($query) use ($post) {
        $query->where('commentable_id', $post->id)
              ->where('commentable_type', $post::class);
    }
)->get();


$replies = $comment->descendants;
```
