### ISSUE TITLE
[Question] Is it possible to apply this package for a many to many morphed relationships?

### ISSUE THREAD

**Issue by Marchiuzzz** [staudenmeir/laravel-adjacency-list#108]
Hello,
I have a relatively complicated database structure and was wondering if this package is suitable for my needs. I've tried inspecting every provided example but still couldn't figure out if it will work or not.
Here is a simplified explanation of the structure I have:
`Object.php` has a morphable relationship to different types of objects called `entityable`. One of those types is `Group.php`. `Group.php` has a many-to-many relationship with `Object.php` (because a grop might contain other objects, which might also be groups, which might also have lots of objects, which might also be groups and so on...). I want to retrieve recursively all `Objects.php` with all morphed objects, including the `Group.php` with all of their recursive objects. Which method, if any, is most suitable for such use case?

**Comment by staudenmeir** [comment]
Can you share the structure of these tables (as migrations or a database dump) and a few sample rows?

**Comment by Marchiuzzz** [comment]
@staudenmeir Sure here it is.
The "group" object I was talking about is actually called `View`
Here's it's structure
![image](https://user-images.githubusercontent.com/73941456/168972825-2b1d50f3-1fed-41e7-807e-b7633fcb5c2a.png)

`Objects` table structure (this is the object that morphs to entities - can morph to `View`)
![image](https://user-images.githubusercontent.com/73941456/168973151-96a3bc87-e00f-42ab-88c1-9a3f7ea083b3.png)

`Views_objects` table (fk to objects table is dynamic_object_id, fk for `View` is `view_id`) :
![image](https://user-images.githubusercontent.com/73941456/168973280-b9ee7fcb-8f54-4996-b84b-c0f096de4723.png)

Example rows:
`Objects` table containing a view object
![image](https://user-images.githubusercontent.com/73941456/168975232-992e0c41-d95d-4d2b-b792-ff2c5b4b64cd.png)

This view record in `Views` table
![image](https://user-images.githubusercontent.com/73941456/168975290-7ee58dc1-3d1f-4663-b796-1262688d6226.png)

`Views_objects` table records
![image](https://user-images.githubusercontent.com/73941456/168975427-c2a8c384-255d-4819-b71f-f267d9be83f4.png)

Objects related to this `View`
![image](https://user-images.githubusercontent.com/73941456/168975558-1bbb49d8-1b25-4ced-aa12-b02d94311979.png)
![image](https://user-images.githubusercontent.com/73941456/168975585-cb5741bf-af8a-434b-a0cf-ca8b22f8847c.png)

And then as you can see, those objects are also views, which are related to other objects.

**Comment by Marchiuzzz** [comment]
I've been playing around with CTE and I think this should be the correct query, however, I get `table list_structure not found` when I try to run it.

```
WITH list_structure AS
(
SELECT
    views.id as parentID,
    objects.abstract_object_id as childID,
    0 AS levels
    FROM views
    inner join views_objects as objects on views.id = objects.view_id
    WHERE views.id NOT IN (
				select distinct b.view_id 
                from dynamic_abstract_objects a
				inner join views_objects b on a.id = b.abstract_object_id
				inner join views v on v.id = a.entityable_id
            )
UNION ALL
SELECT        
	views.id as parentID,
    objects.abstract_object_id as childID,
    levels+1
    FROM views
    inner join views_objects as objects on views.id = objects.view_id
    inner join dynamic_abstract_objects as o on o.entityable_id = views.id
    INNER JOIN list_structure
    ON o.id = list_structure.childID
)
SELECT * FROM list_structure;
```

**Comment by staudenmeir** [comment]
You had posted (and deleted) a CTE query that didn't work. It was missing the `RECURSIVE` keyword:

```sql
WITH RECURSIVE list_structure AS
```

**Comment by Marchiuzzz** [comment]
@staudenmeir Yup, I found that this was the issue so I deleted my comment 😄 I think I'll just go with manual approach, thanks
