### ISSUE TITLE
Would this package work with two parent_id? (father_id, mother_id)

### ISSUE THREAD

**Issue by aFluxx** [staudenmeir/laravel-adjacency-list#11]
Title stated the question, here's a table drawing my question:

|id|father_id|mother_id|
|---|---|---|
|1|||
|2||   |
|3|1|2| 

Wondering if it's possible to do something like `User::find(3)->descendantsAndSelf()` where you would get a tree of the node sibling with it's parents, greatparents etc..

**Comment by staudenmeir** [comment]
The package doesn't support this kind of relationship.

I recommend that you use the underlying [CTE package](https://github.com/staudenmeir/laravel-cte) to implement the necessary queries.

**Comment by aFluxx** [comment]
Didn't get a notification of your answer! Thanks for clarying, I'll have to dig into the underlying package!

**Comment by daninfocus** [comment]
Hi will this work for #79 feature?

**Comment by staudenmeir** [comment]
#79 is similar, but there's a crucial difference: In #79, the parent ids are defined in a separate table.

**Comment by luismabenitez** [comment]
@staudenmeir but the point is to get something like father_id and mother_id on the same table. Like that, think we have a "dogs" table or a "persons" table. That relation to father_id or mother_id will be a belongsTo the same table. Read on some issue that is a WIP task?
