### ISSUE TITLE
Custom value when parent_id node doesn't exist?

### ISSUE THREAD

**Issue by daninfocus** [staudenmeir/laravel-adjacency-list#111]
Hi, sorry for being here again...

I'm wondering if there is a way to add a custom value when parent_id in pivot table doesn't exist in node table.

So I'll continue with the example in #109 

I need the pedigree list to be in order, and if the is no parent present, I need that position in the ancestor array to be empty, to structure the pedigree correctly.

So in this first example, the pedigree is correct, the parents that aren't present, appear in the correct position:

![image](https://user-images.githubusercontent.com/46300009/172177414-b0c843a8-a593-498c-a975-e9a878aad1e8.png)

But with the `ancestors()` relationship it would be something like this, all the ancestors that are missing from the pedigree, won't maintain the correct order and appear at the end, so any generation where there is a parent missing, the order will be wrong:

![image](https://user-images.githubusercontent.com/46300009/172177318-30694777-b37f-4e1a-8065-631bea2d6f8e.png)

Thank you.

**Comment by staudenmeir** [comment]
What does your `ancestors` query look like in these case?

**Comment by daninfocus** [comment]
```
$ancestors = Dog::withRecursiveQueryConstraint(function (Builder $query) {
   $query->whereDepth('>', -5);
}, function () {
   return Dogs::find($id)->ancestors;
});

//this is what reorders the array by depth
foreach ($ancestors as $ancestor) {
    $ancestor = $ancestor->toArray();
    if (!isset($pedigree[abs($ancestor["depth"])])) {
        $pedigree[abs($ancestor["depth"])] = [];
    }
    $new_dog = new Dog($ancestor);
    $new_dog->id = $ancestor['id'];
    array_push($pedigree[abs($ancestor["depth"])], $new_dog);
}

```

**Comment by staudenmeir** [comment]
> the correct order was generated before using your wonderful package, but it was too slow and made way too many queries.

What did that code look like and what queries did it run? It might be easier to optimize this code than adjust the other one.

**Comment by staudenmeir** [comment]
Unfortunately, I don't see a way for the package to help you building this data structure.

However, you should be able to improve the performance of the original approach by fetching all ancestors beforehand:

```php
public static function deepAncestors($dog, $depth=4)
{
    $cache = $dog->ancestors()->get(['id', 'sire_id', 'dam_id', 'country_id', 'name', 'regtype_id', 'user_id', 'show_titles', 'sex', 'birth_day'])->keyBy('id');

    $anc = array();
    $anc [0][] = $dog;

    $level = 0;
    $anc = self::getParents($anc, $level, $depth, $cache);

    return $anc;
}

private static function getParents($anc, $level, $depth=4, $cache)
{
    $i=0;
    foreach ($anc[$level] as $gen) {
        $anc[$level+1][$i++] = (isset($gen->sire_id)) ? $cache[$gen->sire_id] : 'empty';
        $anc[$level+1][$i++] = (isset($gen->dam_id)) ? $cache[$gen->dam_id] : 'empty';
    }
    if ($level < $depth-1) {
        $anc = self::getParents($anc, ++$level, $depth, $cache);
    }
    return $anc;
}
```
