### ISSUE TITLE
Can it run alongside laravel-nestedset?

### ISSUE THREAD

**Issue by sawirricardo** [staudenmeir/laravel-adjacency-list#113]
Hi, great package, really love it.

I was thinking maybe we can try to make this package co-existable with current nested-set? Since it has some features I would love to use that doesn't require nested set, but didn't want to leave the nested set too.

https://github.com/lazychaser/laravel-nestedset

currently, if we just install this, it will have conflicting methods such as parents and children relationship...

**Comment by staudenmeir** [comment]
Hi @sawirricardo,
How does/would your database structure look like? Would you have both the `parent_id` column for this package and the `lft` & `rgt` columns for nested set in the same table?

**Comment by sawirricardo** [comment]
yes, `_lft` and `_rgt` to be precise, that's the nested set package standard way,

**Comment by sawirricardo** [comment]
and I think should not the columns be in 1 table though? haven't seen structures which has lft/rgt and parent_id in different places 🤔

**Comment by staudenmeir** [comment]
> and I think should not the columns be in 1 table though? haven't seen structures which has lft/rgt and parent_id in different places 🤔

I didn't mean in comparison to having the columns in multiple tables, but I wanted to confirm that you want to have the columns for both packages at the same time. It sounds quite cumbersome to always keep two sets of hierarchies up-to-date and in sync.

> currently, if we just install this, it will have conflicting methods such as parents and children relationship...

You should be able to solve the conflicts with method aliases:
https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict

**Comment by staudenmeir** [comment]
I just looked at the actual conflicts: You can solve the conflicts for methods like `ancestors` and `children` with aliases, but the conflicts for `newCollection` and especially `newEloquentBuilder` are different: You would have to manually merge classes of the two packages which is probably possible but quite a lot of work.

**Comment by staudenmeir** [comment]
Does `lazychaser/laravel-nestedset` offer any features that you are missing from this package?

**Comment by sawirricardo** [comment]
the motivation behind me is the uncertain to pick exactly 1 package between these two, hence the thinking to _why not use both_, but if it isn't possible, that's okay. Do you have any situation say... when you will pick this package rather than nested set? or vice versa?

**Comment by decadence** [comment]
Yes, advantage of this package: it doesn't need to build left / right positions every time so tree can't be [broken](https://github.com/lazychaser/laravel-nestedset/issues/503) on parallel update / inserts.
