### ISSUE TITLE
Call to undefined method Staudenmeir\LaravelAdjacencyList\Eloquent\Builder::descendants()

### ISSUE THREAD

**Issue by emirlike** [staudenmeir/laravel-adjacency-list#116]
Hi!
unfortunately I can't seem to get this extension to work. I'm a beginner with Laravel.

I have a user model and userRelationships model. The latter holds the parent-child bindings. 

```
class UserRelationships extends Model
{
    //use HasFactory;
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function getParentKeyName()
    {
        return 'sponsor_id';
    }
    public function getLocalKeyName()
    {
        return 'user_id';
    }

	protected $table = 'user_relationships';
    protected $primaryKey = 'user_id';
    public $incrementing = false;

	protected $casts = [
	];

	protected $dates = [
	];

	protected $fillable = [
        'user_id',
		'sponsor_id',
        'matrix_level'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function sponsor()
    {
        return $this->belongsTo(User::class, 'sponsor_id');
    }

}
```

but whenever I call any of this extension methods, eg: 
`$referrals = UserRelationships::where('user_id', $id)->descendants()->get();`

I get this error:
`Call to undefined method Staudenmeir\LaravelAdjacencyList\Eloquent\Builder::descendants()`

**Comment by staudenmeir** [comment]
You need to execute the first query to get the `UserRelationships` result before you use it to fetch a relationship:
https://laravel.com/docs/9.x/eloquent#retrieving-single-models

```php
$referrals = UserRelationships::find($id)->descendants()->get();
```

**Comment by emirlike** [comment]
indeed it works. My apologies and thank you
