### ISSUE TITLE
Filter path

### ISSUE THREAD

**Issue by MiladAheshmeh** [staudenmeir/laravel-adjacency-list#117]
How can I filter a path that visible = 0

users
--------
id
first_name
last_name
parent_id
visible (0,1)

**Comment by MiladAheshmeh** [comment]
$tree = User::withRecursiveQueryConstraint(function (Builder $query) {
   $query->where('users.active', true);
}, function () {
   return User::find(2)->descendants()
});

**Comment by staudenmeir** [comment]
Hi @MiladAheshmeh,

You need to remove the parentheses to execute the relationship query:

```php
$tree = User::withRecursiveQueryConstraint(function (Builder $query) {
   $query->where('users.visible', 1);
}, function () {
   return User::find(2)->descendants;
});                                ^^
```

**Comment by MiladAheshmeh** [comment]
![Screen Shot 1401-04-07 at 21 29 07](https://user-images.githubusercontent.com/5099000/176239334-9b99d3e6-d64b-4da0-a16c-a842e8d9d862.png)
![Screen Shot 1401-04-07 at 21 28 52](https://user-images.githubusercontent.com/5099000/176239345-940f3239-d0ea-4aed-824b-85bc99667ac5.png)
![Screen Shot 1401-04-07 at 21 28 19](https://user-images.githubusercontent.com/5099000/176239353-a9a9501c-762d-46f0-b872-6607e0fa4350.png)

**Comment by staudenmeir** [comment]
You're right, the query doesn't catch invisible descendants on the first level (direct children). I'm looking into a solution.

In the meantime, combine it with the (internal) scope `withRelationshipExpression()`:

```php
$tree = User::withRecursiveQueryConstraint(function ($query) {
    $query->where('users.visible', 1);
}, function () {
    $constraint = function ($query) {
        $query->where('parent_id', 2)->where('visible', 1);
    };

    return User::withRelationshipExpression('desc', $constraint, 1);
})->pluck('first_name');
```

**Comment by stephanesoares** [comment]
Someone has a solution for this?

**Comment by valentinomariotto** [comment]
apply the same constraint to the original query too, because the withRecursiveQueryConstraint does not apply to the immediate children and parents of the target user.

so either what Jonas did [here](https://github.com/staudenmeir/laravel-adjacency-list/issues/117#issuecomment-1174128600) or like so, it should work the same:
```
$tree = User::withRecursiveQueryConstraint(function (Builder $query) {
   $query->where('users.visible', 1);
}, function () {
   return User::find(2)->descendants()->where('users.visible', 1);
});
```

**Comment by staudenmeir** [comment]
I've released a new version with `withQueryConstraint()` that allows you to add the constraint to both queries:
https://github.com/staudenmeir/laravel-adjacency-list?tab=readme-ov-file#initial--recursive-query-constraints

```php
$tree = User::withQueryConstraint(function (Builder $query) {
   $query->where('users.visible', 1);
}, function () {
   return User::find(2)->descendants;
});  
```
