### ISSUE TITLE
Incomplete results when using Single Table Inheritance

### ISSUE THREAD

**Issue by denisgoryaynov** [staudenmeir/laravel-adjacency-list#118]
I have a base Model called "Organization" and two children models "Company" and "Bar". The two child models share the same columns so it makes sense to store them under the same table "organizations" but since they have a lot of different methods/relations I don't want to clutter the base Model.

Currently I am using this package https://github.com/calebporzio/parental, which basically applies a scope on the "type" columns and returns the correct class for the model.

The problem comes when I try to use any of the methods of this package, for example calling children on a "Company" returns only the models of the same class and completely ignores all the "Bar" models.

**Comment by staudenmeir** [comment]
> The problem comes when I try to use any of the methods of this package, for example calling children on a "Company" 

Like `Company::find($id)->children`?

> returns only the models of the same class and completely ignores all the "Bar" models.

Isn't that the correct behavior when you use a child model? Queries on the `Organization` model would return all child models.

**Comment by denisgoryaynov** [comment]
Yes, but the problem is that calling Organization::find($id) actually returns an instance of Company|Bar because of the scope applied by the library I use for single table inheritance so the method Organization::find($id)->children ends up calling the children method on the sub class, example:

$organization = Organization::find($id); // returns an App/Models/Company

$organization->companySpecificMethod();
$children = $organization->children; // returns a Collection of App/Models/Company, ignores App/Models/Bar

**Comment by staudenmeir** [comment]
If you don't use global scopes like `SoftDeletes`, you can remove all global scopes:

```php
$children = $organization->children()->withoutGlobalScopes()->get();
```

Certainly not ideal, but the easiest solution I see at the moment.

This is a not issue with my package but a limitation of `parental`: It affects `children` but any self-referencing `HasMany` relationship would have the same issue:

```php
public function referrals()
{
    return $this->hasMany(static::class, 'referrer_id');
}

Organization::find($id)->referrals; // Only returns App/Models/Company
```
