### ISSUE TITLE
[Question] - Create or append child on Multiple Parents per Node (Many-to-Many)

### ISSUE THREAD

**Issue by reksmeysrey** [staudenmeir/laravel-adjacency-list#119]
First of all, thanks for amazing package.

I have question on creating/append specific parent on **Multiple Parents per Node (Many-to-Many)**

1. How to create or append child on specific parent
2. Is it possible to move one node of **_parent A_** to  another **node** of **_parent B_**

Link: [lazychaser/laravel-nestedset](https://github.com/lazychaser/laravel-nestedset#appending-and-prepending-to-the-specified-parent)

```php
### Create or append child sample

 // #1 Using deferred insert
$node->appendToNode($parent)->save();

// Using parent node
$parent->appendNode($node);

// #3 Using parent's children relationship
$parent->children()->create($attributes);

// #5 Using node's parent relationship
$node->parent()->associate($parent)->save();

// #6 Using the parent attribute
$node->parent_id = $parent->id;
$node->save();

// #7 Using static method
Category::create($attributes, $parent);

```

**Comment by staudenmeir** [comment]
Hi @reksmeysrey,

Thanks. I still need to document this part. Graph relationships are based on the `BelongsToMany` class and you can use its native methods on `children()` and `parents()`:
https://laravel.com/docs/9.x/eloquent-relationships#updating-many-to-many-relationships

> How to create or append child on specific parent

```php
// Append
$node->children()->attach(1);
$node->children()->attach(1, ['label' => 'Test', 'weight' => 123]);

// Create and append
$node->children()->create(['name' => 'Test']);
$node->children()->create(['name' => 'Test'], ['label' => 'Test', 'weight' => 123]);
```

> Is it possible to move one node of parent A to another node of parent B

```php
$nodeA->children()->detach(1);
$nodeB->children()->attach(1);
```

**Comment by reksmeysrey** [comment]
Thanks @staudenmeir
