### ISSUE TITLE
how to use addGlobalScope with table name

### ISSUE THREAD

**Issue by githubgithubhub** [staudenmeir/laravel-adjacency-list#12]
My model contains a boot function, the boot function use addGlobalScope to add a scope.

And I got this PostgreSQL error **Undefined table: 7 ERROR:  missing FROM-clause entry for table**  when the query in scope contains a table name.
`$builder->where('users.age', '>', 200);`

However the **users.** may be required for some of my queries. For example, when I join table users and table orders while they both have column name: status.

**Comment by staudenmeir** [comment]
When the package queries a recursive relationship, the `FROM` clause has to change (e.g. to `laravel_cte`).

You need to make the scope more flexible to always use the respective table name:

```php
protected static function boot()
{
    parent::boot();

    static::addGlobalScope(function ($query) {
       $query->where($query->qualifyColumn('age'), '>', 200);
    });
}
```

**Comment by githubgithubhub** [comment]
Thank you! 
It works!
