### ISSUE TITLE
Nested categories

### ISSUE THREAD

**Issue by mradulovic988** [staudenmeir/laravel-adjacency-list#122]
Hi there, thank you very much for this package!

I have the following error:
```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) a' at line 1```

Here is the Controller:
```
<?php
namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        return view('categories.categories', [
            'categories' => Category::tree()->get()->toTree()
	]);
    }
}
```

I have followed this guy's course (https://www.youtube.com/watch?v=-dj1xKG377c&ab_channel=TraversyMedia) on making a nested category, and I have run into this issue.

Many thanks!

**Comment by staudenmeir** [comment]
Hi @mradulovic988,
What version of MySQL/MariaDB are you using?

**Comment by mradulovic988** [comment]
Hi @staudenmeir

`mysql  Ver 8.0.29 for macos12.2 on x86_64 (Homebrew)`

**Comment by staudenmeir** [comment]
Can you share the whole error message? What version of the package are you using?

**Comment by mradulovic988** [comment]
Package version: v1.11.1

Here is the log:
```
Illuminate\ Database\ QueryException
PHP 8.1.8
9.22.1

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) a' at line 1

with recursive `laravel_cte` as (
  (
    select
      *,
      0 as `depth`,
      cast(`id` as char(65535)) as `path`
    from
      `categories`
    where
      `parent_id` is null
  )
  union all
  (
    select
      `categories`.*,
      `depth` + 1 as `depth`,
      concat(`path`,., `categories`.`id`)
    from
      `categories`
      inner join `laravel_cte` on `laravel_cte`.`id` = `categories`.`parent_id`
  )
)
select
  *
from
  `laravel_cte`
```

**Comment by mradulovic988** [comment]
I just tested on an empty Laravel project and got the same error.

**Comment by staudenmeir** [comment]
What's the result of `dd(\DB::getPdo()->getAttribute(\PDO::ATTR_SERVER_VERSION));`?

**Comment by mradulovic988** [comment]
^ "5.7.32"

**Comment by staudenmeir** [comment]
Your Laravel app is somehow not using the MySQL 8 database it should but a MySQL 5.7 database instead. The package requires MySQL 8 and that's what causes the error.

**Comment by mradulovic988** [comment]
Hey @staudenmeir 

Thank you for the help. I will take care of that.
