### ISSUE TITLE
1105 unknown error

### ISSUE THREAD

**Issue by ljmclaney** [staudenmeir/laravel-adjacency-list#123]
I'm experiencing the following error message on MySQL 8.0.23 (using PlanetScale). 

SQLSTATE[HY000]: General error: 1105 unknown error: syntax error at position 5 near 'with' (SQL: with recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from `pages` where `parent_id` is null) union all (select `pages`.*, `depth` + 1 as `depth`, concat(`path`, ., `pages`.`id`) from `pages` inner join `laravel_cte` on `laravel_cte`.`id` = `pages`.`parent_id`)) select * from `laravel_cte`)

I've spent some time looking into, but so far not found a solution. Have you come across this one before?

Thanks!

**Comment by staudenmeir** [comment]
Hi @ljmclaney,
What's the result of `dd(\DB::getPdo()->getAttribute(\PDO::ATTR_SERVER_VERSION));`?

**Comment by ljmclaney** [comment]
Hi @staudenmeir 

Mine is 8.0.28.

I believe it's an issue with Planetscale, I've switched to a DB on DigitalOcean and it's working now. 

Cheers!
