### ISSUE TITLE
I will donated this projects !! you save my day

### ISSUE THREAD

**Issue by igun997** [staudenmeir/laravel-adjacency-list#124]
Send your paypal email here , of course you must replied with your author accounts !

**Comment by staudenmeir** [comment]
Hi @igun997,
Thanks for your support. This is my PayPal link: https://www.paypal.com/paypalme/JonasStaudenmeir

**Comment by decadence** [comment]
@staudenmeir thank you for creating this great package and helping users in Issues 💪

I don't try it yet but I already see your effort on this one. Great documentation and support.
