### ISSUE TITLE
Issue with MariaDB when using Model::tree()->withCount('relation')

### ISSUE THREAD

**Issue by veganista** [staudenmeir/laravel-adjacency-list#125]
It looks like there is an issue with MariaDB when using ```Model::tree()->withCount('relation')```, i've tested this with 10.3, 10.4, and 10.5. However, in MySQL 8.0 the query runs perfectly.

When trying to use ```Model::tree()->withCount('relation')``` in MariaDB, you get the following error:

```
Unknown column 'laravel_cte.id' in 'where clause'
```

Here are the tests i've set up on DB Fiddle. These include the query to set up the tables and the query generated in Laravel.

| Version      | Link                                                                                               | Status |
|--------------|----------------------------------------------------------------------------------------------------|--------|
| MySQL 8.0    | [Link](https://dbfiddle.uk/?rdbms=mysql_8.0&sample=sakila&fiddle=beaa829539dae8d3667ce871cef41be1) | Works  |
| MariaDB 10.3 | [Link](https://dbfiddle.uk/?rdbms=mariadb_10.3&fiddle=beaa829539dae8d3667ce871cef41be1)            | Error  |
| MariaDB 10.4 | [Link](https://dbfiddle.uk/?rdbms=mariadb_10.4&fiddle=beaa829539dae8d3667ce871cef41be1)            | Error  |
| MariaDB 10.5 | [Link](https://dbfiddle.uk/?rdbms=mariadb_10.5&fiddle=beaa829539dae8d3667ce871cef41be1)            | Error  |

The SQL generated from the query is from using the following code in Laravel.

```php
$groups = Group::tree()->withCount('students')->get();
```

My relationships for the ```Group``` model are set as follows:

```php
class Group extends Model
{
    public function groups()
    {
        return $this->hasMany(Group::class, 'parent_id');
    }

    public function group()
    {
        return $this->belongsTo(Group::class, 'parent_id');
    }

    public function students()
    {
        return $this->belongsToManyOfDescendantsAndSelf(Student::class);
    }
}

```

You can see from the output of the MySQL 8.0 fiddle that the expected result would look something like this:

|id |name                        |parent_id|depth|path  |name_path                            |students_count|
|---|----------------------------|---------|-----|------|-------------------------------------|--------------|
|1  |Lake Noah High School       |         |0    |1     |Lake Noah High School                |2             |
|2  |Port Keenanview High School |         |0    |2     |Port Keenanview High School          |0             |
|3  |Monday                      |1        |1    |1.3   |Lake Noah High School/Monday         |2             |
|4  |Group 1                     |3        |2    |1.3.4 |Lake Noah High School/Monday/Group 1 |1             |
|5  |Group 2                     |3        |2    |1.3.5 |Lake Noah High School/Monday/Group 2 |1             |

In my examples, groups are in a tree and each group contains a number of students who can also be in multiple groups.

My initial thought was that getting the student counts wouldn't work like this but it works perfectly, even getting the number of students in each group for the root and intermediary nodes, however in MariaDB it doesn't.

Have you any thoughts on this? Could this be an issue with MariaDB?

If you want me to try any thing or provide more information / clarity please let me know.

**Comment by staudenmeir** [comment]
Hi @veganista,
Unfortunately, MariaDB doesn't support this kind of query yet: https://jira.mariadb.org/browse/MDEV-19077

**Comment by veganista** [comment]
I was trying to find out more about the issue last night and didn't come up agains that report.
