### ISSUE TITLE
Graph Trait is not available

### ISSUE THREAD

**Issue by zeematter** [staudenmeir/laravel-adjacency-list#126]
Hi,

I have tried to install few times but the Graph Triat is not available.

Not sure what's happening.

Regards
Zee

**Comment by staudenmeir** [comment]
Hi @zeematter,
What error message are you getting? What version of the package are you using?

**Comment by zeesmatter** [comment]
Sorry got busy and didn't see your comment,

I'm using 1.9.6 in Laravel 8

and I'm getting ""message": "Call to undefined method App\\Models\\Devices::treeOf()"

**Comment by staudenmeir** [comment]
Please share your whole `Devices` model.

**Comment by zeesmatter** [comment]
`<?php

namespace App\Models;

use App\Models\Statics\DevicesLevelsStatics;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class DevicesLevels extends Model
{
    use HasFactory, DevicesLevelsStatics, HasRecursiveRelationships;

    protected $primaryKey = 'device_level_id';

    protected $fillable = ['devices_id', 'device_reading', 'device_level', 'percentage',
        'volume', 'is_valid', 'is_collection', 'data', 'raw_id', 'parent_id'];


    protected $casts = [
        'data'  => 'array',
        'percentage'    =>   'integer',
        'volume'        =>  'integer'
    ];

    protected $with = ['devicesEmissions'];

    public function scopeDefaultSelect($builder)
    {
        $builder->addSelect(['device_level_id', 'devices_id', 'percentage', 'volume', 'is_valid', 'is_collection']);
    }

    public function devicesEmissions()
    {
        return $this->belongsTo(
          DevicesEmissions::class,
            'raw_id',
            'raw_id'
        );
    }

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function child()
    {
        return $this->hasOne(self::class, 'parent_id');
    }




}
`

**Comment by staudenmeir** [comment]
You are trying to call `treeOf()` on the `Devices` model, but the `HasRecursiveRelationships` trait is in the `DevicesLevels` model. How are these model connected?

**Comment by zeesmatter** [comment]
Sorry I think I was calling it from wrong model and add to the different one :( All good now but you are awesome with your support. I'll make some donation today 👍

**Comment by zeesmatter** [comment]
Can I call it from Devices model though?

They are connected with foreign id,

devices
id | name

devices_levels
id | devices_id | level | parent_id

**Comment by staudenmeir** [comment]
It sounds like you need to use `treeOf()` with a custom constraint:

```php
$device = Devices::find($id);

$constraint = function ($query) use ($device) {
    $query->where('devices_id', $device->id);
};

$tree = DevicesLevels::treeOf($constraint)->get();
```

**Comment by zeesmatter** [comment]
hmm, thanks. I think I am on right track then... :)

**Comment by zeesmatter** [comment]
Just made some donation, thank you for your awesome work, time and help.

**Comment by staudenmeir** [comment]
Thanks, I appreciate it!
