### ISSUE TITLE
getCustomPaths with pivot column

### ISSUE THREAD

**Issue by loveshiun** [staudenmeir/laravel-adjacency-list#129]
When using pivot in `getCustomPaths()`, it always returns "undefined column error".

https://github.com/staudenmeir/laravel-adjacency-list#graphs-custom-paths

My getCustomPaths contains

```
[
        "name" => "slug_path",
        "column" => "just_pivot_column_or_pivot"."pivot_column",
        "separator" => "/",
      ],
```

Is it possible to have pivot_column in the path. Or how can I get a custom path containing pivot columns without another SQL querying?

**Comment by staudenmeir** [comment]
Hi @loveshiun,
Sorry for not responding to your question, I somehow completely missed it all this time. Are you still having this issue?
