### ISSUE TITLE
Use different primary for tree

### ISSUE THREAD

**Issue by KoIIIeY** [staudenmeir/laravel-adjacency-list#13]
How can I change primary key for selecting?

I have table like 
tree_id | link | parent_link

so primary key tree_id is not a leaf identifier.
I can change name for parent_link, and want to change tree_id to link

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by KoIIIeY** [comment]
And second question: 
I need to select only leafs that has goods with remain > 0

but 
return $q->whereHas('descendants', function($e){
           $e->whereHas('goods', function($f){
                $f->having('stocks_remain_sum', '>', 0);
            });
       });

gives me error 500 without any errors or explanation.

**Comment by staudenmeir** [comment]
Did you enable `APP_DEBUG` in your `.env` file?

**Comment by KoIIIeY** [comment]
Yeah, of course.
Maybe it's because I started changing your code for primary keys, I already changes some code in "descendants"

**Comment by KoIIIeY** [comment]
plz, look at these files

https://github.com/KoIIIeY/laravel-adjacency-list/blob/master/src/Eloquent/HasRecursiveRelationships.php

https://github.com/KoIIIeY/laravel-adjacency-list/blob/master/src/Eloquent/Relations/Descendants.php

and changes in it. 

I added getter for primary leaf name
public function getPrimaryTreeKeyName(){
        return 'id';
    }

Works ok, but created path is wrong, it's looks like {parent_link.parent_link.id} , but last section should be "link".

May be you can explain where path generated?

**Comment by staudenmeir** [comment]
Sorry for the late response.

I've released a new version that adds support for custom local keys (requires Laravel 6):

```php
class YourModel extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;
    
    public function getLocalKeyName()
    {
        return 'tree_id';
    }
}
```

**Comment by KoIIIeY** [comment]
All ok. thanks.
