### ISSUE TITLE
IDE helpers

### ISSUE THREAD

**Issue by nandi95** [staudenmeir/laravel-adjacency-list#130]
For the relations included in this package, there is no way to get the relations type hinted when using [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper)

I have made a [hook](https://github.com/barryvdh/laravel-ide-helper#model-hooks) that correctly adds the relelations.
I'm proposing adding the hook utility class here despite it being related the the other plugin because the values would need to be maintained in line with this package.

If this is something you would be interested in, I could add a PR.

**Comment by staudenmeir** [comment]
Hi @nandi95,
Thanks, a PR would be great.
