### ISSUE TITLE
SQLSTATE[42712]: Duplicate alias: 7 ERROR: table name "person_parents" specified more than once

### ISSUE THREAD

**Issue by Kmap-Holdings** [staudenmeir/laravel-adjacency-list#133]
Good day, 

I get the following error when trying to use the HasGraphRelationships Package:

My composer file is as follows: 

"require": {
        "php": "^8.0.2",
        "algolia/scout-extended": "2.0",
        "fakerphp/faker": "^1.9.1",
        "filament/filament": "^2.15",
        "filament/spatie-laravel-media-library-plugin": "^2.15",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/jetstream": "^2.11",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7",
        "livewire/livewire": "^2.5",
        "spatie/laravel-medialibrary": "^10.4",
        "staudenmeir/laravel-adjacency-list": "^1.0"
    },

My model is as follows: 

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasGraphRelationships;

class PersonParent extends Model
{
    use HasFactory;
    use HasGraphRelationships;

    public function getPivotTableName(): string
    {
        return 'person_parents';
    }

    public function getPivotColumns(): array
    {
        return ['parent_type_id'];
    }

    public function parentType()
    {
        return $this->hasOne(ParentType::class);
    }

    public function enableCycleDetection(): bool
    {
        return true;
    }

    public function includeCycleStart(): bool
    {
        return true;
    }

}

My livewire component is as follows: 

 public function mount()
    {
        $parents = PersonParent::with('parents')->get();
    }

My pivot table is as follows: 

Schema::create('person_parents', function (Blueprint $table) {
            $table->id();
            $table->foreignId('parent_id')->constrained('people');
            $table->foreignId('child_id')->constrained('people');
            $table->foreignId('parent_type_id')->constrained('parent_types');
            $table->timestamps();
        });

The query it runs is as follows:

select "person_parents".*, "person_parents"."child_id" as "pivot_child_id", "person_parents"."parent_id" as "pivot_parent_id" from "person_parents" inner join "person_parents" on "person_parents"."id" = "person_parents"."parent_id" where "person_parents"."child_id" in (1, 2, 3, 4, 5, 6) 

Kindly assist. Thanks.

**Comment by staudenmeir** [comment]
Hi @Kmap-Holdings,

You actually need work on and with a different model. Your equivalent to `Node` from the documentation is the `Person` (I assume that's what it's called):

```php
class Person extends Model
{     ^^^^^^
    use HasGraphRelationships;

    public function getPivotTableName(): string
    {
        return 'person_parents';
    }

    public function getPivotColumns(): array
    {
        return ['parent_type_id'];
    }

    public function enableCycleDetection(): bool
    {
        return true;
    }

    public function includeCycleStart(): bool
    {
        return true;
    }
}
```

> My livewire component is as follows:

> public function mount()
> {
> $parents = PersonParent::with('parents')->get();
>}

I don't how your component works exactly, but you need to change that to something like this:

```php
$parents = Person::with('parents')->get();
```

**Comment by Kmap-Holdings** [comment]
Hi,

Thanks for the quick response. Much appreciated. Rookie mistake. Sorry for
that.

**Comment by staudenmeir** [comment]
No worries!

**Comment by Kmap-Holdings** [comment]
Work like magic! Thanks a mill again.
