### ISSUE TITLE
Automatic path without model ID

### ISSUE THREAD

**Issue by maximesahagian** [staudenmeir/laravel-adjacency-list#134]
Hello,

I have a problem with the path of my tree. I would like the path to be automatically as such:
1
1.1.1
1.1.2
2
2.1.1
Etc...

But unfortunately I have
ID
PARENT_ID.PARENT_ID2.ID
PARENT_ID.PARENT_ID2.ID
ID
PARENT_ID.PARENT_ID2.ID
Etc...

I don't want the model ID for my path, but just the current automatically generated path, is that possible?

Thank you

**Comment by staudenmeir** [comment]
Hi @maximesahagian,
Which relationship are you using? What does your query look like?

Please share a few sample rows and the paths you are getting at the moment vs. the paths you would like to get.

**Comment by maximesahagian** [comment]
Thank for your reply @staud

My request is easy as 

```
$constraint = function ($query) use ($model) {
    $query->whereNull('parent_id')->where('model_id', $model->id);
};

$tree = Model::treeOf($constraint)->depthFirst()->get();
```

And when i try for example $tree->first()->path, it's the model's ID, sounds OK, but I want to get the path as I asked above, and not the model_id.

For example in my tree i get parent with id = 7 in the DB, and a children with id = 3.

Here is what i get when i foreach and print path:
- 7
- 7.3
- 
But what i want is:
- 1
- 1.1

Thank you

**Comment by staudenmeir** [comment]
I'll see if there's a solution for that.

**Comment by staudenmeir** [comment]
Which database engine are you using?

**Comment by maximesahagian** [comment]
I'm using Mysql @staudenmeir

**Comment by staudenmeir** [comment]
What do you want to do with that path? Show it in a view?

I looked into generating the path in SQL and it's probably possible, but the query would be pretty complex. It would be much easier to generate the path in PHP after executing the query.

**Comment by maximesahagian** [comment]
> What do you want to do with that path? Show it in a view?
> 
> I looked into generating the path in SQL and it's probably possible, but the query would be pretty complex. It would be much easier to generate the path in PHP after executing the query.

Absolutely, it’s to show it in a view

**Comment by staudenmeir** [comment]
Try something like this:

```php
$tree = Model::treeOf($constraint)->depthFirst()->get();

$version = [];
$depth = -1;

foreach ($tree as $model) {
    if ($model->depth > $depth) {
        $version[$model->depth] = 1;
    } else {
        if ($model->depth < $depth) {
            $version = array_slice($version, 0, $model->depth + 1);
        }

        $version[$model->depth]++;
    }

    $depth = $model->depth;

    $model->version_path = implode('.', $version);

    dump($model->version_path);
}
```
