### ISSUE TITLE
Root parent with relationships

### ISSUE THREAD

**Issue by ottz0** [staudenmeir/laravel-adjacency-list#135]
I have a list of servers with a relationship to it’s product sub category. I can’t see the relationship when I try to view it from it’s parent (null)? 

I can only see it when I view it from the next node down (product sub category)

How can I attach my server list so it finds its way back to the root parent? It’s like product sub category cannot see it’s parent (the root)

```
Products (root null) cannot see server1,2 etc
     ——-subProductType can see see server1,2 etc
              ——- servers 
                        ——server1
                        ——server2
```

**Comment by staudenmeir** [comment]
Hi @ottz0,
Please share the migrations of all tables that are involved here.

**Comment by ottz0** [comment]
**Create Products Table**
```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->string('title');
            $table->string('tagline');
            $table->string('slug');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
};
```

**Create Servers Table**

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('servers', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('product_id')->nullable();
            $table->foreign('product_id')->references('id')->on('products');
            $table->string('slug');
            $table->string('type');
            $table->string('title');
            $table->integer('price');
            $table->string('processor_line_1');
            $table->string('processor_line_2');
            $table->string('memory');
            $table->string('storage_line_1');
            $table->string('storage_line_2');
            $table->string('data');
            $table->integer('benchmark');
            $table->string('benchmark_percentage');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('servers');
    }
};
```

**Comment by staudenmeir** [comment]
> I can’t see the relationship when I try to view it from it’s parent (null)?

What query are you executing in this case?

**Comment by ottz0** [comment]
Hi Sorry it's not an issue. I just can't get the right query or relationship.

I have two models Products and Servers.

Here I can get the Parent (null) Categories with the sub categories but can't get the other model (posts)

```
 $cc = Category::whereHas('bloodline', function ($query) use ($id){
        $query->where('id', $id)->with('posts');
    })->get();
```

Here I can get the sub categories with the posts but can't get Parent (null) categories
```
$users = Category::with('recursivePosts')->get();
```

How can I create a relevant query where I can get the whole tree node?

Parent Category - 1 (Null) eg:dedicated servers
    ----Sub category (fast dedicated Servers) parent_id -1
           ----(id) - the list of servers in this sub category
           ----(id) - the list of servers in this sub category
           ----(id) - the list of servers in this sub category
    ----Sub category (fast dedicated Servers) parent_id -1
           ----(id) - the list of servers in this sub category
           ----(id) - the list of servers in this sub category
           ----(id) - the list of servers in this sub category

**Comment by ottz0** [comment]
I think this might have it

```
$fullTree = Category::tree()->whereHas('bloodline', function ($query) use ($id){
        $query->where('id', $id);
    })->with('posts')->get();
```
