### ISSUE TITLE
Getting count with whereDepth

### ISSUE THREAD

**Issue by soundar8562** [staudenmeir/laravel-adjacency-list#136]
Currently, we are getting a count of different depths of **same model** in separate queries like below,

$count1 = **Model**::find(2)->descendants()->whereDepth(**3**)->where('status', 1)->count();
$count2 = **Model**::find(2)->descendants()->whereDepth(**4**)->where('status', 1)->count();

Is it possible to get the count in a single query?

**Comment by staudenmeir** [comment]
You can get the counts in a single query, but – depending on your table size and database engine – that is not guaranteed to be faster than two separate queries: 

```php
$descendants = Model::find(2)->descendants()->whereBetween('depth', [3, 4])->where('status', 1)->get(['depth']);

$count1 = $descendants->where('depth', 3)->count();
$count2 = $descendants->where('depth', 4)->count();
```

**Comment by soundar8562** [comment]
Yes right, as you mentioned we get the same speed for each query.

Here we are looping through all the ids and ->find($id) to get a count so instead of doing a count inside the loop do you have any idea on getting on the main query?

$m1 = Model::**whereDepth(1)**->pluck('id');

$count1=array();
$count2=array();
foreach($m1 as $key => $id){
  $count1[$key] = Model::find($id)->descendants()**->whereDepth(3)**->where('status', 1)->count();
  $count2[$key] = Model::find($id)->descendants()**->whereDepth(4)**->where('status', 1)->count();
}

dd($count1, $count2);

For example, depth1 is State, depth3 is City and depth4 is the Village, so we want to count each city and village inside of all the states in one query.

**Comment by staudenmeir** [comment]
What's the maximum depth in your tree? Do you have a lot of descendants with `depth > 4`?

**Comment by soundar8562** [comment]
The total depth of my tree is 4. 

**For example,**

Depth 1. **State**
    Depth 2. **District**
        Depth 3. **City**
             Depth 4. **Village**

**Comment by staudenmeir** [comment]
In that case, you can compare the performance to an approach that builds the whole tree once:

```php
$states = Model::tree()->get()->toTree();

foreach ($states as $state) {
    $cities = $state->children->pluck('children')->collapse();
    $villages = $cities->pluck('children')->collapse();

    $count1 = $cities->count();
    $count2 = $villages->count();
}
```

**Comment by soundar8562** [comment]
Okay still we are getting the same in performance vice, is there any possibility to do like the one below?

StateProfile::join('Table as s', 'stateprofile.state_id', '=', 'model.id')
        ->select('stateprofile.*','s.name as state_name','s.id as state_id')
        ->selectRaw("**Table::find(state_id)->descendants()->whereDepth(3)->where('status', 1)->count()**")
        ->orderBy('state_name')
        ->get()->groupBy('state_name');

**Comment by staudenmeir** [comment]
What database are you using?

**Comment by soundar8562** [comment]
MariaDB

**Comment by staudenmeir** [comment]
> ->selectRaw("Table::find(state_id)->descendants()->whereDepth(3)->where('status', 1)->count()")

This is equivalent to `->withCount('descendants')` (with an additional constraint), but MariaDB doesn't support this kind of query yet: https://jira.mariadb.org/browse/MDEV-19077
