### ISSUE TITLE
Custom variable to a constraint

### ISSUE THREAD

**Issue by DekaAkademi** [staudenmeir/laravel-adjacency-list#137]
Hello;
I need to use the constraints like below:

$constraints = function ($query, $lessons) {
    $query->whereIn('lesson_id', $lessons)->orderBy('order', 'desc);
};
$tree = Subject::treeOf($constraints)->get()->toTree();

$lessons holds an array of ids. It doesn't work with this usage. But if I type the array [2,3,4,5,6,7] as hard coding, it works.
How can I solve this problem?

Error: '1 passed in /Applications/XAMPP/xamppfiles/htdocs/deka/vipkurum-api/vendor/staudenmeir/laravel-adjacency-list/src/Eloquent/Traits/HasRecursiveRelationshipScopes.php on line 190 and exactly 2 expected'

**Comment by staudenmeir** [comment]
Hi @DekaAkademi,
Do you mean like [this](https://www.php.net/manual/en/functions.anonymous.php#example-184)?

```php
$constraints = function ($query) use ($lessons) {
    $query->whereIn('lesson_id', $lessons)->orderBy('order', 'desc);
};

$tree = Subject::treeOf($constraints)->get()->toTree();
```

**Comment by DekaAkademi** [comment]
Thanks it worked!
