### ISSUE TITLE
Bulder->paginate queries entire tree to get total amount of items

### ISSUE THREAD

**Issue by Warmic** [staudenmeir/laravel-adjacency-list#139]
Hello, I just ran into an issue where I wanted to use "paginate "method for pagination of root models. However, I saw that $paginator->total was equal to amount of items in the entire tree(roots + descendants).  

Example:
`
{
    "total": 3,
    "data: [
        "id": 1,
        "parent_id": null,
        "children": [
            {
                "id": 2,
                "parent_id": 1,
                "children": [
                    {
                    "id": 3,
                    "parent_id": 2,
                   "children": []
                    }
        ]
            }
        ]
    ]
}
`
There is only 1 item at root level,but total will be equal to 3

My solution was to add "paginateForTree" macro to Staudenmeir\LaravelAdjacencyList\Eloquent\Builder that copies behaviour of ->paginate method,but returns different $total. My question is, did I miss somethig? If this is a bug,I could make a PR that fixes it(although it may bring breaking changes to other users)

**Comment by staudenmeir** [comment]
Hi @Warmic,

> I wanted to use "paginate "method for pagination of root models.

What query are you executing here?

**Comment by Warmic** [comment]
Oh yeah, I completely forgot to mention that I am doing it with result of tree() query. 
Code can look as simple as:
`
use Staudenmeir\LaravelAdjacencyList\Eloquent\Collection;

$paginator = Model::tree()->paginate();
$tree         = (new Collection($paginator->collect()))->toTree();
`

**Comment by staudenmeir** [comment]
Use this to only get root models:

```php
$paginator = Model::isRoot()->paginate();
```

Do you then need the tree for every paginated root model?

**Comment by Warmic** [comment]
Yes, I need to paginate through root models,which have trees. So that ?page=N will be applied to offset root models

**Comment by staudenmeir** [comment]
Does the query work for you?
