### ISSUE TITLE
Getting the count of related models

### ISSUE THREAD

**Issue by alphametric** [staudenmeir/laravel-adjacency-list#14]
Hi,

Firstly, amazing package! Thanks so much.

I'm trying to use it to get the total counts of related models. Consider the following example... a hierarchical `areas` table that I use the `tree` method on e.g.

`Area::tree()->depthFirst()->get()`

So you end up with something like this:

```
California
    -> Los Angeles
        -> Hollywood
        -> Santa Monica
```

Now imagine a `properties` table that is related to `area` via `area_id` and I want the number of properties for each area. I can use `->withCount("properties")`, however that will only give the count of properties for that area. It won't include descendants.

Let's say Los Angeles has 1 property, while Hollywood has 2 and Santa Monica has 3. Using a simple withCount would give this:

```
California (0)
    -> Los Angeles (1)
        -> Hollywood (2)
        -> Santa Monica (3)
```

When in reality, what I'm after, is this:

```
California (6)
    -> Los Angeles (6)
        -> Hollywood (2)
        -> Santa Monica (3)
```

Do you have any idea how I might go about fixing this problem using the package?

Thanks!

**Comment by staudenmeir** [comment]
> When in reality, what I'm after, is this:
> 
> California (6)
>     -> Los Angeles (6)
>         -> Hollywood (2)
>         -> Santa Monica (3)

Do you mean `-> Los Angeles (1)`?

**Comment by alphametric** [comment]
Hi,

Not quite, no. The figure displayed for each area should be the total number of properties for that area + the total number of properties that use an area which is a descendant of that area.

Using the example...

Hollywood (2) and Santa Monica (3) belong to Los Angeles, so their respective property counts (2 and 3) are added together to make Los Angeles (5). There is also one property that has Los Angeles specifically set as its `area_id`, so we add that too. Thus the final figure is Los Angeles (6).

Continuing on, Los Angeles is part of California. Since there are no properties that have California specifically set as their `area_id`, it is displayed as California (6). If there were a property with California set as its `area_id`, then it would be California (7) etc.

Hope that makes things clearer? 
Thanks!

**Comment by alphametric** [comment]
All areas can have properties. Whether they are root or not, does not matter.

**Comment by staudenmeir** [comment]
The easiest solution would be fetching all descendants and calculating the sums in PHP/Laravel.

I assume you are looking for an in-query approach you can implement as a scope?

**Comment by alphametric** [comment]
That would involve potentially a great many queries depending on the depth though, right?

Ideally, yes, one query would be ideal, but I don’t know how practical / efficient it would be...

**Comment by staudenmeir** [comment]
Do you know what the typical use case(s) would look like?

- Would you fetch a (sub)tree and add a column with the total number of properties to each area?
- Or would you want to get the total number of properties for a single area?
- Or both?

**Comment by alphametric** [comment]
My use case is a recursive top to bottom / parent to all grandchildren. A query that returns the depth and property totals at each level for all siblings. 

The data is being put into a report for printing, so I think it’s the first option?

**Comment by staudenmeir** [comment]
> That would involve potentially a great many queries depending on the depth though, right?

In this case, the PHP/Laravel approach should actually be faster. I'm thinking of this query:

```php
$areas = Area::tree()->depthFirst()->withCount('properties')->get();
```

You would run a single recursive query that executes a subquery for each area. You would then have to write a recursive PHP method to calculate the total number of properties for each area. Do you know what I mean?

The alternative would be a *recursive* `withCount()` subquery that counts the total number of properties in the query. The subquery would be quite complex and definitely slower than the PHP approach but more flexible if you need the counts inside the query (e.g. for filtering).

**Comment by alphametric** [comment]
The first approach I understand, however unless I'm interpreting it wrong, you would get incorrect values if you were to paginate the result set? I know I mentioned earlier it was a report, but I'm just trying to cover all bases.

I think I would prefer the recursive sub query. Okay, it may be slower, but it won't matter if the results were paginated. Do you have any idea what that recursive sub query would look like?

P.S. Thanks so much for all your input on this!

**Comment by alphametric** [comment]
This might be useful: https://mysqlserverteam.com/mysql-8-0-labs-recursive-common-table-expressions-in-mysql-ctes-part-three-hierarchies/

See section "Aggregate functions in a nested set"

**Comment by alphametric** [comment]
Okay, I've got a working example, however if there are no listings for a particular area, then `listing_count` will be NULL instead of 0. Any idea how to transform this into an Eloquent query:

```sql
WITH recursive `laravel_cte` AS ( 
	( 
		SELECT	*, 
				0 AS `depth`, 
				cast(`id` AS char(65535)) AS `path` 
		FROM   	`areas` 
		WHERE  	`parent_id` IS NULL
	) 
	UNION ALL 
	( 
		SELECT		`areas`.*, 
					`depth` + 1 AS `depth`, 
					concat(`path`, '|', `areas`.`id`) 
		FROM       	`areas` 
		INNER JOIN 	`laravel_cte` ON `laravel_cte`.`id` = `areas`.`parent_id`
	)
) 
SELECT  `id`, 
        `name`, 
        `depth`, 
        
		## LISTING COUNT SUB QUERY
		( 
			WITH RECURSIVE cte AS
			(
				SELECT laravel_cte.id, laravel_cte.`name` AS temp_area_name, laravel_cte.parent_id FROM laravel_cte 
				JOIN listings ON laravel_cte.id = listings.area_id
				UNION ALL
				SELECT laravel_cte.id, laravel_cte.name, laravel_cte.parent_id
				FROM cte JOIN laravel_cte ON laravel_cte.id = cte.parent_id
			)
			SELECT COUNT(*) AS listing_count FROM cte
			WHERE cte.id = laravel_cte.id
			GROUP BY temp_area_name
		) AS `listings_count`
		## SUB QUERY ENDS
		
FROM     `laravel_cte` 
ORDER BY path ASC
```

**Comment by staudenmeir** [comment]
> The first approach I understand, however unless I'm interpreting it wrong, you would get incorrect values if you were to paginate the result set? I know I mentioned earlier it was a report, but I'm just trying to cover all bases.

Yeah, that's a downside.

I'll look into it.

**Comment by alphametric** [comment]
Thanks!

I was able to use a query like so:

```php

// Recursive sub query
$sql = "
	(
		WITH RECURSIVE cte AS
		(
			SELECT laravel_cte.id, laravel_cte.tenant_id, laravel_cte.name AS area_name, laravel_cte.parent_id FROM laravel_cte
			JOIN listings ON laravel_cte.id = listings.area_id
			UNION ALL
			SELECT laravel_cte.id, laravel_cte.tenant_id, laravel_cte.name, laravel_cte.parent_id
			FROM cte JOIN laravel_cte ON laravel_cte.id = cte.parent_id
		)
		SELECT COUNT(*) AS listings_count FROM cte
		WHERE cte.id = laravel_cte.id
		GROUP BY area_name
	) AS listings_count
";

// Eloquent
Area::tree()->selectRaw($sql)-> simplePaginate(10);
```

**Comment by staudenmeir** [comment]
In this case, the `GROUP BY` clause is actually not necessary and removing it also solves the `null` issue:

```php
$cte = DB::table('laravel_cte')
    ->select('laravel_cte.*')
    ->join('listings', 'listings.area_id', 'laravel_cte.id')
    ->unionAll(
        DB::table('laravel_cte')
            ->select('laravel_cte.*')
            ->join('cte', 'cte.parent_id', 'laravel_cte.id')
    );

$listings = DB::table('cte')
    ->withRecursiveExpression('cte', $cte)
    ->selectRaw('COUNT(*)')
    ->whereColumn('cte.id', 'laravel_cte.id');

Area::tree()
    ->select('laravel_cte.*')
    ->selectSub($listings, 'listings_count')
    ->simplePaginate(10);
```

**Comment by staudenmeir** [comment]
I'll look into adding a `withRecursiveCount()` method to the package.

**Comment by staudenmeir** [comment]
Regarding the table name in the `$cte` query: I was wondering whether there's a difference between `laravel_cte` and `areas`.

I get the same result for your tree query or queries like `Area::find($id)->descendants()->[...]`.

However, only `areas` works correctly for queries like `Area::find($id)->ancestors()->[...]`:

```php
$cte = DB::table('areas')
    ->select('areas.*')
    ->join('listings', 'listings.area_id', 'areas.id')
    ->unionAll(
        DB::table('areas')
            ->select('areas.*')
            ->join('cte', 'cte.parent_id', 'areas.id')
    );
```

Or using the `Area` model:

```php
$cte = Area::select('areas.*')
    ->join('listings', 'listings.area_id', 'areas.id')
    ->unionAll(
        Area::select('areas.*')
            ->join('cte', 'cte.parent_id', 'areas.id')
    );
```

**Comment by alphametric** [comment]
Thanks so much! 

 I’ll try this out and report back my findings.

**Comment by alphametric** [comment]
So the query works as advertised. Thanks so much for that! Really happy to no longer be using raw SQL.

Regarding your table name comment, when I tried replacing `laravel_cte` with `areas` for this: `-> whereColumn("cte.id", "laravel_cte.id")`, it gave me a SQL error, however this might be due to me also adding further `where` restrictions for data based on the current tenant.

Personally, I'm happy with how things are right now, so I'm going to close the issue.

Thanks again for all your help!

**Comment by staudenmeir** [comment]
> Regarding your table name comment, when I tried replacing laravel_cte with areas for this: -> whereColumn("cte.id", "laravel_cte.id"), it gave me a SQL error

This constraint always has to refer to `laravel_cte` ;-)

**Comment by alphametric** [comment]
Ah, right. Got it. Thanks!

**Comment by Naghal** [comment]
Hi, are you still planning to add `withRecursiveCount` to the package? I have the exact same use case as alphametric and I'd like to see that implemented in this package.

**Comment by staudenmeir** [comment]
@Naghal Yes, I'm still working on it.

Please post the error message as a text. What Laravel version are you using?

**Comment by Naghal** [comment]
Hi, here is the text version.
```
QueiyException SQLSTATE[HY000]: General error: 20018 Incorrect syntax near'". [20018] (severity 15) [with [laravel_cte] as (select * from (select *, 0 as [depth], cast([ID] as varchar) as [path] from [_DSKRubrics] where [ParentlD] is null) as [temp table] union all select * from (select [_DSKRubrics].*, [depth] + 1 as [depth], cast(concat([path], [_DSKRubrics].[ID]) as varchar) as [path] from [_DSKRubrics] inner join [laravel_cte] on [laravel cte].[ID] = [_DSKRubrics]. [ParentlD]) as [temp table]) select *, (with recursive 'cte' as (select * from (select [_DSKRubrics].* from [_DSKRubrics] inner join [_DSKTickets] on [_DSKTickets].[RubriclD] = [_DSKRubrics].[ID]) as [temp table] union all select * from (select [_DSKRubrics].* from [_DSKRubrics] inner join [cte] on [cte].[ParentlD] = [_DSKRubrics].[ID]) as [temp table]) select COUNT(*) from 'cte' where 'cte'.'id' = laravel cte'.'id') as [listings count] from [laravel_cte]] (SQL: with [laravel_cte] as (select * from (select *, 0 as [depth], cast([ID] as varchar) as [path] from [_DSKRubrics] where [ParentlD] is null) as [temp table] union all select * from (select [_DSKRubrics].*, [depth] + 1 as [depth], cast(concat([path], [_DSKRubrics].[ID]) as varchar) as [path] from [_DSKRubrics] inner join [laravel_cte] on [laravel cte].[ID] = [_DSKRubrics]. [ParentlD]) as [temp table]) select *, (with recursive 'cte' as (select * from (select [_DSKRubrics].* from [_DSKRubrics] inner join [_DSKTickets] on [_DSKTickets].[RubriclD] = [_DSKRubrics].[ID]) as [temp table] union all select * from (select [_DSKRubrics].* from [_DSKRubrics] inner join [cte] on [cte].[ParentlD] = [_DSKRubrics].[ID]) as [temp table]) select COUNT(*) from 'cte' where 'cte'.'id' = laravel cte'.'id') as [listings count] from [laravel_cte]) 
```

**Comment by staudenmeir** [comment]
It looks like another plugin is conflicting with this one.

You can solve the issue by replacing `DB::table('cte')` with `Rubric::from('cte')`.

**Comment by staudenmeir** [comment]
The latest release allows you to recursively retrieve and count related models with `HasManyOfDescendants` relationships:
https://github.com/staudenmeir/laravel-adjacency-list#custom-relationships

```php
class Area extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function recursiveProperties()
    {
        return $this->hasManyOfDescendantsAndSelf(Property::class);
    }
}

$recursiveProperties = Area::find($id)->recursiveProperties;

$areas = Area::withCount('recursiveProperties')->get();
```

**Comment by mstaack** [comment]
brilliant stuff! this helped me a lot
