### ISSUE TITLE
When I used tree it return all items which has child as root 

### ISSUE THREAD

**Issue by sdfarshid** [staudenmeir/laravel-adjacency-list#140]
Hi this is my TB 
![image](https://user-images.githubusercontent.com/9034581/193746635-62267490-8b77-43fe-be1d-32d3a98772b2.png)
And this is my code 
     $constraint = function ($query) {
            $query->whereNull('parent_id');
        };
 return  $users = Category::select(['id', 'name AS text','parent_id'])->treeOf($constraint)->get()->toTree();
 So I see below  as a return 

> 

 [
  {
    "id": 1,
    "text": "PartenA",
    "parent_id": null,
    "children": [
      {
        "id": 2,
        "text": "Child B",
        "parent_id": 1,
        "children": [
          {
            "id": 3,
            "text": "Child C",
            "parent_id": 2,
            "children": [
              
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 4,
    "text": "Parent B",
    "parent_id": null,
    "children": [
      {
        "id": 5,
        "text": "Child b",
        "parent_id": 4,
        "children": [
          
        ]
      }
    ]
  },
  {
    "id": 2,
    "text": "Child B",
    "parent_id": 1,
    "children": [
      {
        "id": 3,
        "text": "Child C",
        "parent_id": 2,
        "children": [
          
        ]
      }
    ]
  },
  {
    "id": 5,
    "text": "Child b",
    "parent_id": 4,
    "children": [
      
    ]
  },
  {
    "id": 3,
    "text": "Child C",
    "parent_id": 2,
    "children": [
      
    ]
  }
]

> 

But I don't want to have this part 
"
  {
    "id": 2,
    "text": "Child B",
    "parent_id": 1,
    "children": [
      {
        "id": 3,
        "text": "Child C",
        "parent_id": 2,
        "children": [
          
        ]
      }
    ]
  },
  {
    "id": 5,
    "text": "Child b",
    "parent_id": 4,
    "children": [
      
    ]
  },
  {
    "id": 3,
    "text": "Child C",
    "parent_id": 2,
    "children": [
      
    ]
  }
 "

**Comment by sdfarshid** [comment]
I see  this issue 
Tree with orderBy #20
It help me to get what things I expected but I didn't use the tree 
  return  $users = Category::select(['id', 'name AS text','parent_id'])->whereNull('parent_id')
                    ->with(['children:id,name AS text ,parent_id'])->get();

**Comment by staudenmeir** [comment]
Hi @sdfarshid,
Do you only want to get the root models (`PartenA ` and `Parent B`)?

**Comment by staudenmeir** [comment]
Hi @sdfarshid,
> but I didn't use the tree

That's correct. `tree()` returns all models, not just the root models.

Is your issue solved?

**Comment by sdfarshid** [comment]
So if I want to have a tree with just roots and children what can do? 
I define   a children Metod in the model and after that  do this 
        return $this->hasMany(self::class, 'parent_id')->with('children:id,name AS text,parent_id');

**Comment by staudenmeir** [comment]
> return $this->hasMany(self::class, 'parent_id')->with('children:id,name AS text,parent_id');

How are you using this relationship in your query?

**Comment by sdfarshid** [comment]
I used your answer  https://github.com/staudenmeir/laravel-adjacency-list/issues/20 
 It is ok 
 
 class Product extends Model
{
    public function children()
    {
        return $this->hasMany(self::class, 'parent_id')->with(''children:id,name AS text,parent_id');
    }
}

Product::whereNull('parent_id')->with('children:id,name AS text,parent_id')->get();


For having Graphs: Multiple Parents per Node (Many-to-Many)
we must have Laravel 9+. Is it possible to use this feature for Laravel 8?

**Comment by staudenmeir** [comment]
No, graph relationships don't work on Laravel 8.
