### ISSUE TITLE
Orderby Each Level

### ISSUE THREAD

**Issue by ap1969** [staudenmeir/laravel-adjacency-list#141]
Hi,

Is it possible to apply an orderBy clause to each level in the heirarchy?

So if I had

```
id       title        parent_id
1        1A          null
2        2B         1
3        2A         1
4        3B         2
5        3A          2
```

And queried the entire tree, ordering by title, I would get:

```
1A
   2A
   2B
      3A
      3B
```

Many thanks in advance,
Andy

**Comment by staudenmeir** [comment]
Hi @ap1969,
Try this:

```php
YourModel::tree()->breadthFirst()->orderBy('title')->get()
```

**Comment by ap1969** [comment]
Ah, thanks. That worked. I didn't quite understand what breadthFirst() does.
