### ISSUE TITLE
Problem hasManyOfDescendants Relation

### ISSUE THREAD

**Issue by winkcler** [staudenmeir/laravel-adjacency-list#142]
Hello, I'm having a problem with the HasManyOfDescendants relationship.

I'm getting the following error:

![image](https://user-images.githubusercontent.com/4259380/197310806-b8342f7f-fe0c-499a-8566-2fbbde2d6cd5.png)

I'm using Laravel 9 and My Sql 8.

Anyone have an idea what it could be?

**Comment by staudenmeir** [comment]
Hi @winkcler,
How is your `HasManyOfDescendants` relationship defined and how are you using it?
