### ISSUE TITLE
Conditional sub query

### ISSUE THREAD

**Issue by denizgolbas** [staudenmeir/laravel-adjacency-list#143]
I have this query. There is a 'sign' column for amounts. How can implement a sub query if the sign column is negative multiply -1?

`
\App\Models\Accounting\Account::find(1)->descendantsAndSelf()->withSum('slips as total', 'total_amount_base')->get()->sum('total');
`

**Comment by staudenmeir** [comment]
> if the sign column is negative

Hi @denizgolbas,
What are the exact values?
