### ISSUE TITLE
Can i use `tree()` together with load() or with()?

### ISSUE THREAD

**Issue by bhaidar** [staudenmeir/laravel-adjacency-list#145]
Hi

I have a Product and Variation model
 - The variations table has a foreign_id relating it to the products table
 - The variations table has a parent_id linking to itself
 - There are base records and also leaf ones

I want to load only base records and the descendants inside them. 

For example, the variations table has the following data:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1163421/205624111-1cb7bc65-44b9-4978-aea9-1530da57c99a.png">

When I load Product Variations, I expect only to load the following:

ID: 1
Title: Black
Children: [ /* all descendants with nested Children */]

ID: 1
Title: White
Children: [ /* all descendants with nested Children */]

I could make it work when I use the following:

```
Variations::where('product_id', 1)->tree()->get()->toTree();
```

However, I am loading the Product via route-binding and then adding an extra call to load variations:

```
$product->load('variations');
```

What are my options to load the Variations in a tree shape, so I don't get leaf nodes too?

Thanks
Bill

**Comment by bhaidar** [comment]
I believe I solved it using this:

```
class Variation extends Model
{
    // ...

    public function childrenRecursive(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->children()->with('childrenRecursive');
    }

    // ...
}
```

A children() relationship is a hasMany() relationship. The leaf rows won't have any related rows. Hence they will be eliminated from the top-level rows returned.


Let me know please if there is a better way of modeling this.

Thank you
Bill

**Comment by staudenmeir** [comment]
Hi @bhaidar,

> I believe I solved it using this:

How do you use `childrenRecursive()` in your solution?

**Comment by bhaidar** [comment]
@staudenmeir 

Since `childrenRecursive()` is a relation, I do it like that:

```
return Inertia::render('Products/Show', [
            'product' => $product->load('variations.childrenRecursive')
        ]);
```

**Comment by staudenmeir** [comment]
How is  the `variations` relationship defined?

**Comment by bhaidar** [comment]
```
    public function variations(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Variation::class)->whereNull('parent_id');
    }
```

**Comment by bhaidar** [comment]
@staudenmeir Can you illustrate more on the treeOf()? What exactly this one does? Thank you

**Comment by staudenmeir** [comment]
It allows you to fetch a tree with a custom constraint for the root models:
 - With `tree()`, the default constraint is `->whereNull('parent_id')`.
 - In your case, the constraint needs to be `->whereNull('parent_id')->where('product_id', $product->id)` to limit the query to `$product`.

**Comment by bhaidar** [comment]
@staudenmeir 
I still see two queries though:

```
with recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from `variations` where `parent_id` is null and `product_id` = 1) union all (select `variations`.*, `depth` + 1 as `depth`, concat(`path`, '.', `variations`.`id`) from `variations` inner join `laravel_cte` on `laravel_cte`.`id` = `variations`.`parent_id`)) select * from `laravel_cte`

select * from `variations` where `parent_id` is null and `variations`.`product_id` in (1)
```

Also, I should keep the variations() relationship on the Product model otherwise it nags no relationship defined although I am defining one programmatically.

**Comment by bhaidar** [comment]
@staudenmeir Actually, this new relation breaks the logic I am after. Not only do I want to load variations that are the root, but also I want to load the rest of the variation tree recursively. With this query, I get only the variations of the root, no children variations are returned.

**Comment by bhaidar** [comment]
@staudenmeir It seems it works! I should stop loading any relations once I use setRelation. Thanks for this tip :-)

**Comment by staudenmeir** [comment]
> When is the query of the setRelation executed? If I am just returning $product to the frontend, at that time Laravel resolves the relationship before sending down the data?

What result are you getting in the frontend? It should behave the same way as `'product' => $product->load('variations.childrenRecursive')`.

**Comment by bhaidar** [comment]
Indeed yes!

**Comment by staudenmeir** [comment]
Your issue is solved, right?

**Comment by bhaidar** [comment]
@staudenmeir Indeed! Thanks a lot
