### ISSUE TITLE
Pagination datas go with toTree() method

### ISSUE THREAD

**Issue by denizgolbas** [staudenmeir/laravel-adjacency-list#146]
I call a model like that:

`ModelName::where(something)->paginate()->toTree();`

When I put totree() i lost pagination data. 

How can i keep pagination data with toTree() method?

**Comment by staudenmeir** [comment]
You need to replace the paginator's collection:

```php
$models = ModelName::where(something)->paginate();

$models->setCollection(
    $models->toTree()
);
```
