### ISSUE TITLE
Dynamically change parent key name in model.

### ISSUE THREAD

**Issue by johnlemuel-hapa** [staudenmeir/laravel-adjacency-list#15]
Hi how can i dynamically change the parent key name in my model?

Right now I override the `getParentKeyName` method in my model but what if I need to dynamically change it because in my project I have two features in which they have different `parent key name`.

Thanks you.

**Comment by staudenmeir** [comment]
What do you mean by "features"? Can you provide details?

**Comment by johnlemuel-hapa** [comment]
I have a `placement_user_id` and `sponsor_user_id` in my `User` Table. I have one feature in my app that needs to view the graph of the tree base on `placement_user_id` as its `parent key name` and another feature in my app that needs to view the graph of the tree base on `sponsor_user_id` as its  `parent key name`. How can I dynamically change it?

**Comment by staudenmeir** [comment]
You can achieve this with a getter and a setter:

```php
class User extends Model
{
    protected $parentKey;

    public function getParentKeyName()
    {
        return $this->parentKey;
    }

    public function setParentKeyName($parentKey)
    {
        $this->parentKey = $parentKey;

        return $this;
    }
}

$tree = (new User)->setParentKeyName('placement_user_id')->tree()->get();

$tree = (new User)->setParentKeyName('sponsor_user_id')->tree()->get();
```
