### ISSUE TITLE
Error while filtering with hasManyOfDescendantsAndSelf

### ISSUE THREAD

**Issue by robvan2** [staudenmeir/laravel-adjacency-list#150]
Hello, well first of all thanks for the great package <3 it helped me so much. But I'm getting this error while trying to filter by 
hasManyOfDescendantsAndSelf relation

### Error i'm getting 
![image](https://user-images.githubusercontent.com/46126356/209660165-8fd58914-ea94-447c-baf2-b1519b3bbf0b.png)

### Use case:
I have Category model with adjacency list, and hasMany Products (Deals) i wanted to filter by recursiveDeals relation:
```PHP
       class Category extends Model{
          public function deals(){
               return $this->hasMany(Deal::class);
          }
          public function recursiveDeals(){
                return $this->hasManyOfDescendantsAndSelf(Deal::class);
          }
      }
```
**Filtering Example simplified**
```PHP
     Category::has('recursiveDeals')
                ->get();
```
I've tried using other queries like with hasManyDeepFromRelations form your other package (i appreciate that one too) or using whereHas with descendants relation but i'm getting the same issue.

### Environment:
-MariaDB: 10.4
-PHP: 8.1.6
-Laravel: 9.34.0

Thanks again, you really made great packages, if any one can help i really apreciate it.

**Comment by staudenmeir** [comment]
Hi @robvan2,
Unfortunately, MariaDB doesn't support this kind of query yet: https://jira.mariadb.org/browse/MDEV-19077

**Comment by robvan2** [comment]
> Hi @robvan2, Unfortunately, MariaDB doesn't support this kind of query yet: https://jira.mariadb.org/browse/MDEV-19077

I've kinda knew it i tried upgrading to mariadb latest but still getting the same error. Thanks for your reply ^^.
