### ISSUE TITLE
Why drop support for laravel 9?

### ISSUE THREAD

**Issue by vlados** [staudenmeir/laravel-adjacency-list#153]
I am confused by the last release where the package is installable only with Laravel 10.
Why?

**Comment by staudenmeir** [comment]
I'm not dropping any support, I added support for Laravel 10. My packages always have dedicated versions for each Laravel version.

**Comment by vlados** [comment]
Maybe we can add something in the documentation to be more clear?

**Comment by decadence** [comment]
Documentation has table of Laravel / package versions. Seems clear to me. You just need to make sure Composer installs right package version. Usually it does it automatically.
