### ISSUE TITLE
Question: How to filter recursive and represent the results as a tree 

### ISSUE THREAD

**Issue by MartinMulder** [staudenmeir/laravel-adjacency-list#159]
I have a table setup in a book like structure with Chapters, Pragraphs and sub paragraphs.
Like:

1 first chapter
1.1 first paragraph
1.1.1 first subparagraph
1.1.2 second subparagraph
1.2 second paragraph

I try to make a search query to filter on titles, which is working, but I can't get the results as a tree.
The toTree function doesn't make a tree from the results

**Comment by devhammed** [comment]
I don't know if you have solved this using your own custom filter function but I solved this using the treeOf and withRecursiveQueryConstraint methods of the package:

<img width="917" alt="image" src="https://github.com/user-attachments/assets/a1a6b031-f6bc-4fdc-b9c9-327fe708b9a8">

<img width="604" alt="image" src="https://github.com/user-attachments/assets/12410aec-1124-4552-b50d-908b52c0dc3b">
