### ISSUE TITLE
Trouble with subgraph method

### ISSUE THREAD

**Issue by maximesahagian** [staudenmeir/laravel-adjacency-list#160]
Hello @staudenmeir !

I usually use the package to use the trees, this package is fabulous, thank you!
But this time, I need to have several parents and several children at the same time. So I saw the "Graphs", which is perfect for me.

However, on an already existing project, with a lot of composer dependencies, I have a problem with the "subgraph" method.

When I run it I get this error: 
`Unknown database type enum requested, Doctrine\\DBAL\\Platforms\\MariaDb1027Platform may not support it.`

The code is simple as it:
```
$constraint = function ($query) use ($request) {
   $query->where('company_id', $request->company_id);
};

$companyGroups = CompanyGroup::subgraph($constraint)->get();
```

Do you have an idea?
Thank you!

**Comment by staudenmeir** [comment]
Hi @maximesahagian,
Please share the migration of the pivot table.

**Comment by maximesahagian** [comment]
@staudenmeir thank you!

    ```
public function up()
    {
        Schema::create('company_group_edges', function (Blueprint $table) {
            $table->foreignId('parent_id')->references('id')->on('company_groups');
            $table->foreignId('child_id')->references('id')->on('company_groups');
        });
    }

    
    public function down()
    {
        Schema::dropIfExists('company_group_edges');
    }
```

I have added this to CompanyGroup model:

```
public function getPivotTableName(): string
    {
        return 'company_group_edges';
    }
```

The "descendants" function has no issue, only the subgraph... But here, I need to build a "tree"

Thanks!

**Comment by staudenmeir** [comment]
Please share the `CompanyGroup` model and the exception's whole stacktrace.

**Comment by maximesahagian** [comment]
@staudenmeir 

Stacktrace: [laravel-2023-03-07.log](https://github.com/staudenmeir/laravel-adjacency-list/files/10905781/laravel-2023-03-07.log)

Model:
`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasGraphRelationships;

class CompanyGroup extends Model
{
    use HasFactory;
    use HasGraphRelationships;

    protected $fillable = [
        'parent_id',
        'company_id',
        'name',
        'type'
    ];

    public const STATUS_BUSINESS_UNIT = 'business_unit';
    public const STATUS_ENTITY = 'entity';
    public const STATUS_REGION = 'region';
    public const STATUS_COST_CENTER = 'cost_center';
    public const STATUS_SITE = 'site';

    public const STATUSES = [
        self::STATUS_BUSINESS_UNIT,
        self::STATUS_ENTITY,
        self::STATUS_REGION,
        self::STATUS_COST_CENTER,
        self::STATUS_SITE,
    ];

    public function getPivotTableName(): string
    {
        return 'company_group_edges';
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }

    public function managers(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'company_group_manager');
    }

    public function connectors(): BelongsToMany
    {
        return $this->belongsToMany(Connector::class);
    }

    public function getRecursiveConnectors()
    {
        $connectors = collect();

        foreach($this->descendantsAndSelf as $companyGroup){
            foreach ($companyGroup->connectors as $connector) {
                if (!$connectors->contains('id', $connector->id)) {
                    $connectors->push($connector);
                }
            }
        }

        return $connectors;
    }
}
`

**Comment by staudenmeir** [comment]
Thanks. Please also share the migration of the `company_groups` table.

**Comment by maximesahagian** [comment]
```
public function up()
    {
        Schema::create('company_groups', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->enum('type', ['business_unit', 'entity', 'region', 'cost_center', 'site'])->default('business_unit');
            $table->unsignedInteger('company_id');
            $table->foreign('company_id')->references('id')->on('companies');
            $table->foreignId('parent_id')->nullable()->references('id')->on('company_groups')->nullOnDelete();
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('company_groups');
    }
```

The parent_id column is no longer used, it was for the tree feature, but now I need a graph

Thank you for your reactivity @staudenmeir !

**Comment by staudenmeir** [comment]
What version of MariaDB are you using?

**Comment by maximesahagian** [comment]
Since i have this issue, i've upgraded it to the last one, and nothing changed (10.11.2)

**Comment by staudenmeir** [comment]
As a temporary workaround, please try adding this before the `subgraph()` call:

```php
\DB::getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
```

I'll look into a proper fix.

**Comment by maximesahagian** [comment]
Thank you! It works with this workaround!

How can I build a "graph" with this subgraph method? I want only first depth CompanyGroups with their children recursively

Here's what I do:
```
$constraint = function ($query) use ($request) {
            $query->where('company_id', $request->company_id);
        };

        \DB::getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');

        return CompanyGroup::subgraph($constraint)->get();
```

But it returns everything at the same level in the JSON

**Comment by maximesahagian** [comment]
Yes exactly, like the `toTree()`.
I don't want to rebuild the tree on the frontend.

I want the nested result exactly as the `toTree()`, so like this:
```
[
{
	"id":15048,
	"name":"Default",
	"depth":0,
	"path":"15048",
	"children": [
		{
			"id":15923,
			"name":"Testaa",
			"depth":1,
			"path":"15048.15923",
			"children": []
		}
	]
}
]
```

instead of this:
```
[
{
	"id":15048,
	"name":"Default",
	"depth":0,
	"path":"15048"
},
{
	"id":15923,
	"name":"Testaa",
	"depth":1,
	"path":"15048.15923"
}
]
```

**Comment by maximesahagian** [comment]
It's okay @staudenmeir, I've rebuilt the tree on the frontend part, but it could be a nice-to-have feature :)

Also, I want all recursive relationships, and I've seen that there is no `belongsToManyOfDescendantsAndSelf` relation, is it normal? How to have all the recursive belongsToMany here?

Thank you for everything.

**Comment by staudenmeir** [comment]
I'm still working on `belongsToManyOfDescendantsAndSelf()` and its equivalents. Everything is more complicated with graphs than trees...

**Comment by staudenmeir** [comment]
There's now a `toTree()` method for graphs:
https://github.com/staudenmeir/laravel-adjacency-list?tab=readme-ov-file#graphs-nested-results

**Comment by staudenmeir** [comment]
I've released a new version that allows you to define `BelongsToManyOfDescendantsAndSelf` relationships:
https://github.com/staudenmeir/laravel-adjacency-list?tab=readme-ov-file#graphs-deep-relationship-concatenation

```php
class CompanyGroup extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function recursiveUsers()
    {
        return $this->hasManyDeepFromRelations(
            $this->descendantsAndSelf(),
            (new static)->users()
        );
    }
}
```
