### ISSUE TITLE
With Siblings issue in addEagerConstraints(array $models) function

### ISSUE THREAD

**Issue by deepakchhapru** [staudenmeir/laravel-adjacency-list#163]
The where condition getting generated when used $modelQuery->with('siblings') has issue. when there are **Null** values in keys

Current Code:

![image](https://user-images.githubusercontent.com/37204040/228185974-060dd698-0281-469b-b7d4-cffeed56a60f.png)

Example: I have lead model which has merge_id as local key. 
if there are duplicate leads based on mobile number, merge_id is updated of parent else it is null

Example Rows:

leads
---
| id | company_id | name | email | mobile | state | country | merge_id | parent_id | agent_id | agent_first_assigned | sales_converted | is_invalid | remarks | is_active | create_id | update_id | created_at | updated_at | 
| -: | -: | - | - | - | - | - | -: | -: | -: | - | -: | -: | - | -: | -: | -: | - | - | 
| 27198 | 1 | Abhi | xyz@xyz.com | 4561237890 |  |  |  |  | 19 | 2023-02-28 00:00:00 | 0 | 0 | [] | 1 | 1 | 1 | 2023-03-23 12:50:42 | 2023-03-23 12:50:42 | 
| 33509 | 1 | Abhishek | abc@abc.com | 1234567890 |  |  |  |  | 22 | 2023-02-28 00:00:00 | 0 | 0 | [] | 1 | 1 | 1 | 2023-03-23 12:50:58 | 2023-03-23 12:50:58 | 
| 61358 | 1 | abhishek Abhishek | xyz@xyz.com | 1234567890 |  |  | 33509 |  | 22 | 2023-02-28 00:00:00 | 0 | 0 | [] | 1 | 5 | 5 | 2023-03-23 15:13:57 | 2023-03-23 15:13:57 | 

Laravel Code:

![image](https://user-images.githubusercontent.com/37204040/228185787-761c829b-4340-49fc-86d6-fb2f53c1d781.png)

Query Generated:

![image](https://user-images.githubusercontent.com/37204040/228185276-739bea15-41c5-4796-a15c-306fec97baab.png)

This query gives all rows where merge_id (local Key) is null. These rows are not related to that mobile no

Instead code should be

![image](https://user-images.githubusercontent.com/37204040/228185475-ab488454-92da-49dd-8531-67d4510b052b.png)

Query Generated with corrected code:

![image](https://user-images.githubusercontent.com/37204040/228184814-5ea3dffe-e887-492f-b1e5-d5700ce25aad.png)

**Comment by staudenmeir** [comment]
Thanks, good point. I released new versions for Laravel 9 and 10. What Laravel version are you using?
