### ISSUE TITLE
Unknown column 'categories.id' in 'where clause' (SQL: with recursive laravel_cte..

### ISSUE THREAD

**Issue by vuevel** [staudenmeir/laravel-adjacency-list#164]
Hello @staudenmeir,

I usually use the package to build a tree structure, thank you!
But now i faced an issue when create complex query using Eloquent ORM.

`### This code is working fine.`
```
$categories = Category::where('provider_id', $request->provider_id)
->tree(3)
->get()
->toTree();

```
**But when I run this code I get this error:**
```
$categories = Category::where('provider_id', $request->provider_id)
                    ->when(!empty($request->search_word), static function (Builder $query) use ($request){
                        $query->where(static function (Builder $qquery) use ($request){
                           $qquery->where('name', 'LIKE', '%'.$request->search_word.'%');
                        });
                    })->when(isset($request->type), static function (Builder $query) use ($request){
                        $query->where('type', $request->type);
                    })->tree(3)->get()->toTree();
```

`Unknown column 'categories.id' in 'where clause' (SQL: with recursive `laravel_cte``

Any advice?
Regards!

**Comment by staudenmeir** [comment]
Hi @vuevel,
Please share the whole error message.

**Comment by vuevel** [comment]
@staudenmeir 

`Column not found: 1054 Unknown column 'categories.id' in 'where clause' (SQL: with recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from `categories` where `parent_id` is null) union all (select `categories`.*, `depth` + 1 as `depth`, concat(`path`, ., `categories`.`id`) from `categories` inner join `laravel_cte` on `laravel_cte`.`id` = `categories`.`parent_id`)) select * from `laravel_cte` where `provider_id` = 1 and exists (select * from `companies` where `categories`.`id` = `category_id` and `company_id` in (1,2) and `status` = 1 and `companies`.`deleted_at` is null) and `status` = 1 and `laravel_cte`.`deleted_at` is null) at vendor\\illuminate\\database\\Connection.php:760)`

**Comment by staudenmeir** [comment]
Please post it inside a code block or a upload a text file.

**Comment by vuevel** [comment]
```
Column not found: 1054 Unknown column 'categories.id' in 'where clause' (SQL: with recursive laravel_cte as ((select *, 0 as depth, cast(id as char(65535))
 as path from categories where parent_id is null) union all (select categories.*, depth+ 1 as depth, concat(path, ., categories.id)
 from categories inner join laravel_cte on laravel_cte.id=categories.parent_id)) select * from laravel_cte where provider_id= 1 
and exists (select * from companies where categories.id=category_id and company_id in (1,2) and status= 1 and companies.deleted_at is null)
 and status= 1 and laravel_cte.deleted_at is null)
 at vendor\\illuminate\\database\\Connection.php:760)
```

[Unknown column 'categories.id'.txt](https://github.com/staudenmeir/laravel-adjacency-list/files/11183011/Unknown.column.categories.id.txt)

**Comment by staudenmeir** [comment]
> and exists (select * from companies where categories.id=category_id and company_id in (1,2) and status= 1 and companies.deleted_at is null)

Where is this subquery coming from? I don't see in your query code. Did you register a global scope for the `Category` model?

**Comment by vuevel** [comment]
@staudenmeir 
Sorry!

**This is the updated query**

```
Category::where('provider_id', $request->provider_id)
                    ->when(!empty($request->company_ids), static function (Builder $query) use ($request){
                        $query->whereHas('companies', static function (Builder $query) use ($request){
                           $query->whereIn('company_id', $request->company_ids)
                              ->when(isset($request->status), static function(Builder $query) use ($request){
                                  $query->where('status', $request->status);
                              });
                        });
                    })
                    ->when(!empty($request->search_word), static function (Builder $query) use ($request){
                        $query->where(static function (Builder $qquery) use ($request){
                           $qquery->where('name', 'LIKE', '%'.$request->search_word.'%');
                        });
                    })->when(isset($request->type), static function (Builder $query) use ($request){
                        $query->where('type', $request->type);
                    })->tree(3)->get()->toTree();
```

Without this line `->tree(3)->get()->toTree();` the query works correctly without problems.

**Comment by staudenmeir** [comment]
Please try putting the `tree(3)` call first:

```php
Category::tree(3)->where(...)->...->get()->toTree()
```

**Comment by hansajith1998** [comment]
Hello @staudenmeir,

cCant we use whereHas with descendants ? 

`\App\Models\User::whereHas('descendants')->get()`

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.id' in 'where clause'`

```sql
select * from `users` where exists (with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `users` as `laravel_reserved_0` where `laravel_reserved_0`.`parent_id` = `users`.`id`) union all (select `laravel_reserved_0`.*, `depth` + 1 as `depth`, concat(`path`, ., `laravel_reserved_0`.`id`) from `users` as `laravel_reserved_0` inner join `laravel_cte` on `laravel_cte`.`id` = `laravel_reserved_0`.`parent_id`)) select * from `laravel_cte` where `laravel_cte`.`deleted_at` is null) and `users`.`deleted_at` is null
````

![image](https://user-images.githubusercontent.com/64520856/231878560-e83a5b1b-4233-4f95-82ea-bd8998749e7f.png)

**Comment by staudenmeir** [comment]
@hansajith1998 Please open a separate issue for this. Are you using MariaDB?
