### ISSUE TITLE
Column not found: 1054 Unknown column 'users.id' in 'where clause'

### ISSUE THREAD

**Issue by hansajith1998** [staudenmeir/laravel-adjacency-list#165]
Hello @staudenmeir,

Cant we use whereHas with descendants? 

`\App\Models\User::whereHas('descendants')->get()`

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.id' in 'where clause'`

```sql
select * from `users` where exists (with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `users` as `laravel_reserved_0` where `laravel_reserved_0`.`parent_id` = `users`.`id`) union all (select `laravel_reserved_0`.*, `depth` + 1 as `depth`, concat(`path`, '.', `laravel_reserved_0`.`id`) from `users` as `laravel_reserved_0` inner join `laravel_cte` on `laravel_cte`.`id` = `laravel_reserved_0`.`parent_id`)) select * from `laravel_cte` where `laravel_cte`.`deleted_at` is null) and `users`.`deleted_at` is null
````

![image](https://user-images.githubusercontent.com/64520856/231878560-e83a5b1b-4233-4f95-82ea-bd8998749e7f.png)

_Originally posted by @hansajith1998 in https://github.com/staudenmeir/laravel-adjacency-list/issues/164#issuecomment-1507587811_

**Comment by staudenmeir** [comment]
Are you using MariaDB?

**Comment by hansajith1998** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/64520856/231879710-15563c33-e6a9-40a3-b162-08b2ed7b77c1.png)

**Comment by staudenmeir** [comment]
Unfortunately, MariaDB doesn't support this kind of query yet:
https://jira.mariadb.org/browse/MDEV-19077

> \App\Models\User::whereHas('descendants')->get()

Is that your actual query or a simplified version?

**Comment by hansajith1998** [comment]
ohh.😴 


This is a simplified version. I was trying to execute this type of query

```php
    // User.php
    public function descendantPackages(): \Staudenmeir\LaravelAdjacencyList\Eloquent\Relations\HasManyOfDescendants
    {
        return $this->hasManyOfDescendants(PurchasedPackage::class, 'user_id', 'id');
    }
 
    // Rank.php
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id')->withDefault();
    }

    // Controller 
    Rank::whereHas('user.descendantPackages', function ($query) {
        $query->selectRaw('SUM(amount) as total')->havingRaw('total > 1000');
    })
```

**Comment by staudenmeir** [comment]
Unfortunately, there's no good workaround for a query like this. You need to split it up into multiple separate queries (or change the database).
