### ISSUE TITLE
How to select specific columns

### ISSUE THREAD

**Issue by Propaganistas** [staudenmeir/laravel-adjacency-list#167]
Hello

First of all thank you for this great package and the effort you put into this.

I'm wondering how I can make the package work with basic column selection using `select($columns)` or `get($columns)`?

```php
User::tree()->get([
    'id', 'parent_id', 'name',
]);
```

This overwrites the generated select query generated by the package, and as a result `depth` and other internal stuff is lost. Calling `toTree()` then renders a flat tree instead of a nested one.

Any pointers?

My use case: a big tree of a model featuring a data-heavy column which is useless for the tree itself. So I'd like to omit overhead columns at SQL-level already.

**Comment by staudenmeir** [comment]
Hi @Propaganistas,
You need to add the internal columns that are required in this case:

```php
User::tree()->get([
    'id', 'parent_id', 'name', 'depth'
]);
```

I decided not to enforce the internal columns so users can omit them if they don't need them.

**Comment by Propaganistas** [comment]
Thanks!
