### ISSUE TITLE
Path separator replacement - minor bug

### ISSUE THREAD

**Issue by cmsedore** [staudenmeir/laravel-adjacency-list#168]
At present, in BuildsAdjacencyListQueries.php, this function:

```
    protected function replacePathSeparator(array $items, $path, $separator)
    {
        foreach ($items as $item) {
            $item->$path = str_replace(
                ',',
                $separator,
                substr($item->$path, 1, -1)
            );
        }
    }
```

is used to replace the comma that is used by Postgresql to separate path items.  Unfortunately, this approach also replaces commas inside any quoted parts of the path, so if you happen to have a comma somewhere in a path column, you replace it, which yields odd looking results.

I overrode the delivered trait function and class and used this version of the function instead:

```
    protected function replacePathSeparator(array $items, $path, $separator)
    {
        foreach ($items as $item) {
            $item->$path=preg_replace('/(?!\B"[^"]*),(?![^"]*"\B)/',$separator,substr($item->$path, 1, -1));
        }
    }
```

(For those interested, I solved for this by extending the Staudenmeir\LaravelAdjacencyList\Eloquent\Builder class, including the function above inside to override the delivered function, then adding a function like this to model with that was the origin of the path:

```
    public function newEloquentBuilder($query)
    {
        return new \App\VendorOverrides\MyLALBuilder($query);
    }
```
)

**Comment by staudenmeir** [comment]
Your workaround doesn't deal with the enclosing quotes, right?

If you have a path segment with a comma like `foo,bar`, the resulting path is `"foo,bar"/baz`.

Do you not mind the quotes or even require them?

**Comment by cmsedore** [comment]
> Your workaround doesn't deal with the enclosing quotes, right?
> 
> 
> 
> If you have a path segment with a comma like `foo,bar`, the resulting path is `"foo,bar"/baz`.
> 
> 
> 
> Do you not mind the quotes or even require them?

The quotes are not a problem for my application at this point, so I didn't run them down.  Ideally, they'd be optional or removable (or maybe the path could come back as an array so that you could implode it).

thanks for your work on this package--I've been using it quite a bit lately.

**Comment by staudenmeir** [comment]
I looked into it, but I don't see a way to provide a universal implementation. Working with PostgreSQL arrays in PHP is quite the nightmare.

Instead, I recommend that you define an [accessor](https://laravel.com/docs/10.x/eloquent-mutators#defining-an-accessor) in your model to take care of the replacing: 

```php
class YourModel extends Model
{
    protected function path(): Attribute
    {
        $separator = ''; // TODO

        return Attribute::make(
            get: function (string $value) use ($separator) {
                return preg_replace('/(?!\B"[^"]*),(?![^"]*"\B)/', $separator, substr($value, 1, -1));
            }
        )->shouldCache();
    }
}
```

Does that work for you?

**Comment by cmsedore** [comment]
Very helpful--thanks.
