### ISSUE TITLE
Graph relationships with uuid primary keys

### ISSUE THREAD

**Issue by cmsedore** [staudenmeir/laravel-adjacency-list#169]
When using graph relations (with cycle detection) with models with primary keys, the PostgresGrammar.php file does the following:

```
    public function compileCycleDetection(string $localKey, string $path): string
    {
        $localKey = $this->wrap($localKey);
        $path = $this->wrap($path);

        return "$localKey = any($path)";
    }
```

unfortunately, that produces this outcome:

```
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: uuid = character varying [...]
```

This happens because the path column in the laravel_cte CTE is this expression 

```
array[(table_name.id || '')::varchar) as path
```

I believe the correct fix would be to change to this to cast the key as a varchar:

```
    public function compileCycleDetection(string $localKey, string $path): string
    {
        $localKey = $this->wrap($localKey);
        $path = $this->wrap($path);

        return "$localKey::varchar = any($path)";
    }
```

This definitely fixes the problem for me.

-Chris

**Comment by staudenmeir** [comment]
Hi @cmsedore,
Thanks, I'll look into it.

**Comment by staudenmeir** [comment]
I released a new version that fixes this issue.

**Comment by cmsedore** [comment]
Confirmed -- this is fixed -- thanks!
