### ISSUE TITLE
Scoping relationships

### ISSUE THREAD

**Issue by Alig96** [staudenmeir/laravel-adjacency-list#17]
How would I query a relationship like `whereDescendantOf($node)` using qbuilder?

**Comment by staudenmeir** [comment]
Can you please provide more details?

**Comment by patrickomeara** [comment]
We do it like this, I hope it helps.

```php
Node::query()->whereIn('parent_id', $node->descendantsAndSelf()->select('id')->getQuery())
```

**Comment by Alig96** [comment]
> Can you please provide more details?

I'm currently testing performance between this package and 
https://github.com/lazychaser/laravel-nestedset to see which is best for my situation. The linked package defines some additional query builder methods for finding nodes that are the descendant/ancestor of a given node. What would be the equivalent of these constraints for this package?

> We do it like this, I hope it helps.
> 
> ```
> Node::query()->whereIn('parent_id', $node->descendantsAndSelf()->select('id')->getQuery())
> ```

My issue with this is that this requires 2 queries to execute, would preferably have them combined.

My scenario is that I have 2 Models:
- Post
- Category (Uses the trait)

I'm defining a query scope on my post for `scopeCategorizedBy($query, $category)`. This will return a collection of posts that has a category of the given category or any of its descendants. I was using the method `whereDescendantOrSelf` on the package. Need a similar constraint.

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
Can you share the implemention of `scopeCategorizedBy()` with nested sets and `whereDescendantOrSelf()`?

**Comment by Alig96** [comment]
```
    public function scopeCategorizedBy(Builder $query, Category $category) : Builder
    {
        $query = $query->whereHas('categories', static function (Builder $query) use ($category) : void {
            $query->whereDescendantOrSelf($category->id);
        });

        return $query;
    }
```

https://github.com/lazychaser/laravel-nestedset/blob/f6f6d7368ef7aeadbffa288ce7454c22d7ad3160/src/QueryBuilder.php#L272
