### ISSUE TITLE
DecendantsAndSelf with pagination

### ISSUE THREAD

**Issue by shauns2007** [staudenmeir/laravel-adjacency-list#173]
Me again :)

Is it possible to use `descendantsAndSelf` with `paginate` to get paginated results?

Trying to achieve something like this

`$users = $request->user()->descendantsAndSelf()
                ->paginate(10)
                ->get(['id', 'email',  'genealogy_address', 'username', 'avatar_id', 'created_at']);`

I know you can use, as an example, `->whereDepth('<', 3)` to go down to a max of 3 levels but is it then possible to achieve something like `->whereDepth('>', 3)->whereDepth('<', 7)`

**Comment by shauns2007** [comment]
![image](https://github.com/staudenmeir/laravel-adjacency-list/assets/10954105/5a59f1d3-64ee-49ca-8a96-c6f790a6983c)

Both of these functions return the exact result set, where I want the `getAdditionalUsers` in this example, I want to get the tree for the user I pass to the method.

**Comment by staudenmeir** [comment]
> $users = $request->user()->descendantsAndSelf() ->paginate(10) ->get(['id', 'email',  'genealogy_address', 'username', 'avatar_id', 'created_at']);

Use `paginate()` _instead of_ `get()`:

```php
$users = $request->user()->descendantsAndSelf()
    ->paginate(10, ['id', 'email', 'genealogy_address', 'username', 'avatar_id', 'created_at']);
```

> I know you can use, as an example, ->whereDepth('<', 3) to go down to a max of 3 levels but is it then possible to achieve something like ->whereDepth('>', 3)->whereDepth('<', 7)

That should work, have you tried it?

> Both of these functions return the exact result set, where I want the getAdditionalUsers in this example, I want to get the tree for the user I pass to the method.

Use `treeOf()`:

```php
User::treeOf($user, 1)->select(...)->...
```

`genealogy_address` is a unique column, right? Then you can also save one query:

```php
User::treeOf(fn($query) => $query->where('genealogy_address', $genealogy_address), 1)->select(...)->...
```

**Comment by shauns2007** [comment]
Thanks :)
