### ISSUE TITLE
Tree method

### ISSUE THREAD

**Issue by Darvin02** [staudenmeir/laravel-adjacency-list#174]
It looks like a bug. When using the tree() method, if the table has a depth column, it gives the error "Duplicate column name 'depth'". How can this be resolved?

**Comment by staudenmeir** [comment]
Hi @Darvin02,
In this case, you need to change the package's column name by overriding `getDepthName()`:
https://github.com/staudenmeir/laravel-adjacency-list#depth

**Comment by staudenmeir** [comment]
> get a "Column not found" error

Please share the whole error message. What does your `getDepthName()` method look like?

**Comment by Darvin02** [comment]
First case. There is a depth column in the table, called "depth". I don't override getDepthName() so it implies that the standard column name is "depth".
`$bestDeal = BestDeal::tree()->get()->toTree();` cause error "Column already exists: 1060 Duplicate column name 'depth'"
But this code `$bestDeal = BestDeal::whereDepth('=', '3')->get();` work as properly. See 1 image.

Second case. The "depth" column is missing in the table. Everything is fine when using this code. `$bestDeal = BestDeal::tree()->get()->toTree();` 
But this code gives an error `$bestDeal = BestDeal::whereDepth('=', '3')->get();` "Column not found: 1054 Unknown column 'depth' in 'where clause'"
See 2 image.

![image](https://github.com/staudenmeir/laravel-adjacency-list/assets/88323253/ebc1ae01-c418-470c-bf51-17f4637aa97d)
![image](https://github.com/staudenmeir/laravel-adjacency-list/assets/88323253/e0b7b055-17c3-4977-961a-e1823970d7b8)

**Comment by staudenmeir** [comment]
> "Column not found: 1054 Unknown column 'depth' in 'where clause'"

Please share the whole message with the whole SQL query.

**Comment by Darvin02** [comment]
> Please share the whole message with the whole SQL query.

For the 1 case th error is:
 "SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'depth' in field list is ambiguous (Connection: mysql, SQL: with recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from `best_deals` where `parent_id` is null) union all (select `best_deals`.*, `depth` + 1 as `depth`, concat(`path`, ., `best_deals`.`id`) from `best_deals` inner join `laravel_cte` on `laravel_cte`.`id` = `best_deals`.`parent_id`)) select * from `laravel_cte`)"

For the 2 case:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'depth' in 'where clause' (Connection: mysql, SQL: select * from `best_deals` where `depth` = 3)

**Comment by staudenmeir** [comment]
Case 1: If you have your own `depth` column, you need to change the package's column name.

```php
class BestDeal extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function getDepthName()
    {
        return '_depth';
    }
}
```

Case 2: If you don't have have your own `depth` column, you can't use `whereDepth()` on its own. You need to combine it with `tree()` or a [relationship](https://github.com/staudenmeir/laravel-adjacency-list#included-relationships).

 ```php
BestDeal::tree()->whereDepth('=', '3')->get();

BestDeal::find($id)->descendants()->whereDepth('=', '3')->get();
BestDeal::find($id)->descendantsAndSelf()->whereDepth('=', '3')->get();
// ...
```

**Comment by Darvin02** [comment]
@staudenmeir Got it! Thank for your help and your time!
