### ISSUE TITLE
get two or multiple relations with condition in one query?

### ISSUE THREAD

**Issue by hossein-holy** [staudenmeir/laravel-adjacency-list#175]
if needed to get (for example) children + siblings together (also may be there are condition).
in this code i'm need bloodline and siblings of user how can i get them without merge. (in one query)
`$user->dsu->bloodline()->notMe()->get()->merge($user->dsu->siblings)->sortBy('id')`

**Comment by staudenmeir** [comment]
Hi @hossein-holy,
You can combine them with a [`UNION`](https://laravel.com/docs/10.x/queries#unions) query, but I wouldn't necessarily recommend that:

```php
$user->dsu->bloodline()->notMe()->union( // or unionAll()
    $user->dsu->siblings()->selectRaw('*, null, null')
)->orderBy('id')->get(),
```

Why do you need to combine them into a single query?

**Comment by hossein-holy** [comment]
very well!
it's required in my project.
do you read my [Idea](https://github.com/staudenmeir/laravel-adjacency-list/discussions/176)?

**Comment by staudenmeir** [comment]
I did and I will look into it when I find the time.
