### ISSUE TITLE
Empty collection when using $with attribute to eager load hasManyOfDescendantsAndSelf relationship

### ISSUE THREAD

**Issue by Naghal** [staudenmeir/laravel-adjacency-list#178]
Hi, I am unsure if this is a bug or myself not correctly using the package.

Given I want to eager load a `hasManyOfDescendantsAndSelf` relation using the `$with` attribute on the model, the relationship is an empty collection. However, if I do it like this: `$customer->managedCustomers()->get()`, I get the correct result.

If I remove the `managedCustomers` from the `$with` array, I can call `$customer->managedCustomers` and get the proper result.

The code looks like this:
```php
class Customer extends Model
{
    use HasRecursiveRelationships;

    protected $with = [/*'managedCustomers', 'managedCustomers.configs.config'*/];

    public function getParentKeyName()
    {
        return 'MainCustomerID';
    }

    public function getLocalKeyName()
    {
        return 'ID';
    }
    public function managedCustomers()
    {
       return $this->hasManyOfDescendantsAndSelf(self::class, 'MainCustomerID');
    }
}
```

Am I doing it correctly?

**Comment by staudenmeir** [comment]
Hi @Naghal,

> Given I want to eager load a hasManyOfDescendantsAndSelf relation using the $with attribute on the model, the relationship is an empty collection.

What query are you executing in this case?

**Comment by Naghal** [comment]
Hi,
simply `$customer->managedCustomers`.

However, it seems that my the problem was with my global scope.
It is now working after I changed it from

```php
public function apply(Builder $builder, Model $model)
{
    $baseSelectables = (new $model)->getSelectables();
    $allSelectables = $this->addAuthorizedFields($model, $baseSelectables);
    $builder->select($allSelectables);
}
```

To

```php
public function apply(Builder $builder, Model $model)
{
    if ($model->getTable() === 'laravel_cte') { // Neccesary fix to make adjency list work
        return;
    }
    
    if (empty($builder->getQuery()->bindings['select'])) {
        $baseSelectables = (new $model)->getSelectables();
        $allSelectables = $this->addAuthorizedFields($model, $baseSelectables);
        $qualifiedSelectables = collect($allSelectables)->map(fn ($selectable) => $model->getTable().'.'.$selectable);
        $builder->select($qualifiedSelectables->toArray());
    }
}
```

**Comment by staudenmeir** [comment]
Hi @Naghal,

> However, it seems that my the problem was with my global scope.
It is now working after I changed it from

But you need this global scope to be applied, right? Have you compared the SQL that gets executed before and after your change?
