### ISSUE TITLE
recursive seems not working

### ISSUE THREAD

**Issue by ftb** [staudenmeir/laravel-adjacency-list#18]
Hi Jonas.
It seems something is broken. All queries that tries to go recursive I have error:
Illuminate/Database/QueryException with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) a' at line 1 (SQL: with recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from `categories` where `parent_id` is null) union all (select `categories`.*, `depth` + 1 as `depth`, concat(`path`, '.', `categories`.`id`) from `categories` inner join `laravel_cte` on `laravel_cte`.`id` = `categories`.`parent_id`)) select * from `laravel_cte` where `laravel_cte`.`deleted_at` is null)'. 
Ancestors(), children(), parent(), siblings() are ok. 
in my category model, I use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships; with softdelete
I'm using laravel 6.8. Category table fields are id, name and parent_id. with 40 records.

**Comment by staudenmeir** [comment]
Are you using MySQL or MariaDB? What version?

**Comment by ftb** [comment]
mysql 5.7.24

**Comment by staudenmeir** [comment]
The package requires MySQL 8.0+: https://github.com/staudenmeir/laravel-adjacency-list#compatibility

Unfortunately, older versions of  MySQL don't support common table expressions.

You can still use the `children`, `parent` ahd `siblings` relationships, but `ancestors` and `descendants` don't work.

**Comment by ftb** [comment]
I miss that... thanks Jonas

**Comment by ftb** [comment]
me again... just my two cents..
MariaDB 10.4.11 -> all ok
mysql CE 8.0.18 -> I need some test. just installed and the problem remain. tomorrow i'll try again

**Comment by staudenmeir** [comment]
Can you confirm the database version with `DB::getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION)`?

**Comment by ftb** [comment]
version confirmed, but not confirmed iussue. Yesterday install of 2 DB, probably had caused some problems. Today fresh install and no problem at all.
thanks again 
ftb
