### ISSUE TITLE
Empty result when using custom local key name and parent key name

### ISSUE THREAD

**Issue by killallskywalker** [staudenmeir/laravel-adjacency-list#180]
```
Staudenmeir\LaravelAdjacencyList\Eloquent\Collection {#1290 ▼ // routes/web.php:117
  #items: []
  #escapeWhenCastingToString: false
}
```

Im creating a custom local key name and parent key name as below 

```
    public function getLocalKeyName()
    {
        return 'position_no';
    }

    public function getParentKeyName()
    {
        return 'reporting_to_position_no';
    }
```

However it always returning empty array , this my sample strcture 

position_no | reporting_to_position_no
100000001  | null
100000002 | 100000001

the result it still returning empty array .

**Comment by staudenmeir** [comment]
Hi @killallskywalker,
What query are you executing in `routes/web.php:117`?

**Comment by pieinn** [comment]
Same issue

**Comment by staudenmeir** [comment]
@pieinn What query are you executing in `app/Http/Controllers/Api/CategoryController.php:20`? What does your recursive model look like?

**Comment by pieinn** [comment]
> @pieinn What query are you executing in `app/Http/Controllers/Api/CategoryController.php:20`? What does your recursive model look like?

use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class Category extends Model
{
    use
        HasFactory,
        SoftDeletes,
        HasRecursiveRelationships,
        HasTranslations,
        EscapeUniCodeJson;

    public $translatable = ['name', 'description'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'slug',
        'parent_id',
        'description',
        'seo_title',
        'seo_description',
        'is_visible'
    ];

    protected $table = 'categories';

    /**
     * @var array<string, string>
     */
    protected $casts = [
        'is_visible' => 'boolean',
    ];

    public function children(): HasMany
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function parent(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function featuredImage(): BelongsTo
    {
        return $this->belongsTo(Media::class, 'featured_image', 'id');
    }
}

**Comment by pieinn** [comment]
> > @pieinn What query are you executing in `app/Http/Controllers/Api/CategoryController.php:20`? What does your recursive model look like?
> 
> `use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;
> 
> class Category extends Model { use HasFactory, SoftDeletes, HasRecursiveRelationships, HasTranslations, EscapeUniCodeJson;
> 
> ```
> public $translatable = ['name', 'description'];
> 
> /**
>  * The attributes that are mass assignable.
>  *
>  * @var array<int, string>
>  */
> protected $fillable = [
>     'name',
>     'slug',
>     'parent_id',
>     'description',
>     'seo_title',
>     'seo_description',
>     'is_visible'
> ];
> 
> protected $table = 'categories';
> 
> /**
>  * @var array<string, string>
>  */
> protected $casts = [
>     'is_visible' => 'boolean',
> ];
> 
> public function children(): HasMany
> {
>     return $this->hasMany(Category::class, 'parent_id');
> }
> 
> public function parent(): BelongsTo
> {
>     return $this->belongsTo(Category::class, 'parent_id');
> }
> 
> public function featuredImage(): BelongsTo
> {
>     return $this->belongsTo(Media::class, 'featured_image', 'id');
> }
> ```
> 
> }
> 
> `

Sorry, in my case is issue in Category Resource)
