### ISSUE TITLE
Question: Can I filter through a relationship?

### ISSUE THREAD

**Issue by GabrielSchenato** [staudenmeir/laravel-adjacency-list#182]
Hello, to exemplify I have the following situation.

A table of categories following this format:

id | name                        | parent_id
----------------------------------------
1  | Category 1               | NULL
2  | Category 2               | 1
3  | Category 3               | 2
4  | Category 4               | 2
5  | Category 5               | NULL
6  | Category 6               | 5
7  | Category 7               | 6
8  | Category 8               | 6

And a table of products following this format:

id | name                        | category_id
----------------------------------------
1  | Product 1                 | NULL
2  | Product 2                 | 4
3  | Product 3                 | 7
4  | Product 4                 | 8

What I want is to be able to filter the products that somehow have a connection with the category "Category 1" because in the product table it has no direct connection with this category, but with the child categories "Category 4".

In the same way, I would like to filter the products that are linked to the category "Category 6", is this possible through the product model?

**Comment by staudenmeir** [comment]
Hi @GabrielSchenato,
Take a look at `HasManyOfDescendants` relationships:
https://github.com/staudenmeir/laravel-adjacency-list#hasmanyofdescendants

```php
class Category extends Model
{
    public function recursiveProducts()
    {
        return $this->hasManyOfDescendantsAndSelf(Product::class);
    }
}

$products = Category::find(1)->recursiveProducts;

$products = Category::find(6)->recursiveProducts;
```

**Comment by GabrielSchenato** [comment]
Hi @staudenmeir thanks for the answer.

I believe that it would not be quite in this scenario that I would like to arrive at, it would be possible to do the following:

`class Product extends Model
{
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

$products = Product ::whereCategoryId(1);

$products = Product ::whereCategoryId(6);`


For example I would like to filter through the product model so that pagination is possible or if there is another way to achieve the same result.

**Comment by GabrielSchenato** [comment]
Perfect then, I believe that with this already solves my problem, thank you very much and I would like to say that this is a great package @staudenmeir
