### ISSUE TITLE
Call to undefined method App\Models\User::withMaxDepth()

### ISSUE THREAD

**Issue by CoderPlusFromNowhere** [staudenmeir/laravel-adjacency-list#183]
The following error happens when I use withMaxDepth():

`Call to undefined method App\Models\User::withMaxDepth()`

Code:

```
$ancestors = User::withMaxDepth(-5, function () {
            return User::find(10)->ancestors;
        });
```

Composer require: "staudenmeir/laravel-adjacency-list": "^1.13"

**Comment by staudenmeir** [comment]
Hi @CoderPlusFromNowhere,
What Laravel version are you using?

**Comment by CoderPlusFromNowhere** [comment]
Hello. 10.19.0

**Comment by CoderPlusFromNowhere** [comment]
Hello. 10.19.0

-- edit
I moved the withMaxDepth() function from HasGraphAdjacencyList to HasAdjacencyList and solved the problem. I cant submit a pull request because I'm not sure if this is the correct solution, and i'm a little bit confused with both traits. Thanks

**Comment by staudenmeir** [comment]
I released a new version that adds `withMaxDepth()` to tree relationships like yours. The method had only been for graph relationships.
