### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by duc-nhat38** [staudenmeir/laravel-adjacency-list#184]
I followed the setup instructions, when I got the tree data, I got the following error:
`Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;./tmp/#sql1_1c_0&#039; doesn&#039;t exist (SQL: with recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from `rooms` where `parent_id` is null) union all (select `rooms`.*, `depth` + 1 as `depth`, concat(`path`, ., `rooms`.`id`) from `rooms` inner join `laravel_cte` on `laravel_cte`.`id` = `rooms`.`parent_id`)) select * from `laravel_cte` where `laravel_cte`.`deleted_at` is null) in file /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 759`

**Comment by staudenmeir** [comment]
What database and version are you using?

**Comment by duc-nhat38** [comment]
@staudenmeir I am using MySQL version 8.0.31.Do I have to grant any privileges?

**Comment by staudenmeir** [comment]
I've never seen an error like this.

> Do I have to grant any privileges?

The `SELECT` privilege is enough.

The `rooms` table does exist, right?
