### ISSUE TITLE
Pagination with children and withSum of relationship

### ISSUE THREAD

**Issue by guratr** [staudenmeir/laravel-adjacency-list#187]
I'm trying to create comment section for posts with pagination. every comment can be child of another, and can have votes.
First approach i tried was 
```
$comments = Comment::tree()
    ->where('post_id', $post->id)
    ->withSum('votes as sum_vote', 'vote')
    ->with(['commenter'])
    ->paginate($perPage)
    ->withQueryString();
    
$comments->setCollection(
    $comments->toTree('replies')
);
```

And it works inconsistent for some $perPage values, for example if last comment on the last page has children, they won't load and pagination wont show them.
Also theres  obvious problem with showing replies on the new page.

The second approach was 
```
$comments = $post->comments()
    ->whereNull('parent_id')
    ->with(['commenter', 'descendants', 'descendants.commenter'])
    ->withSum('votes', 'vote')
    ->paginate($perPage)
    ->withQueryString();
    
 $comments->through(fn($item) => groupDescendants($item, $direction));   
```
The groupDescendants function is a similar one to toTree i wrote for building a tree out of descendants.
With this the problem with pagination is mostly solved for me, because we paginate through only top level comments and then getting all their descendants. 
But now withSum('votes', 'vote') works only for top level comments.
I would like to do something like this ->withSum('descendants.votes', 'vote') but it doesn't work.

i also tried adding additional scope to descendants relationship

```
class Comment
{
    use HasRecursiveRelationships {
        descendants as public traitDescendants;
    }

    public function descendants()
    {
        return $this->traitDescendants()->withSum('votes', 'vote');
    }

    public function descendantsVotes()
    {
        return $this->hasManyOfDescendants(CommentVote::class);
    }
```
But i get an error 

```
1051 Unknown table 'comments' (Connection: mysql, SQL: with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `comments` where `comments`.`parent_id` in (94, 112, 113, 114, 115, 116, 117, 118, 119, 129)) union all (select `comments`.*, `depth` + 1 as `depth`, concat(`path`, ., `comments`.`id`) from `comments` inner join `laravel_cte` on `laravel_cte`.`id` = `comments`.`parent_id`)) select `comments`.*, (select sum(`comment_votes`.`vote`) from `comment_votes` where `comments`.`id` = `comment_votes`.`comment_id`) as `votes_sum_vote` from `laravel_cte`)
```
i also tried ->withSum('descendantsVotes', 'votes') but doesn't include sum for children, only adds their sums to parents.

The only solution i could think of is just retrieving all comment ids from collection, and then manually calculating votes for them with single query and recursively adding them to the main collection.

But i have a filling i'm missing something and there may be a way to do this with the library.

**Comment by staudenmeir** [comment]
Hi @guratr,

> i also tried adding additional scope to descendants relationship

Revert that and try this query instead:

```php
$comments = $post->comments()
                 ->whereNull('parent_id')
                 ->with([
                    'commenter',
                    'descendants' => fn($query) => $query->withSum('votes', 'vote')->with('commenter'),
                 ])
                 ->withSum('votes', 'vote')
                 ->paginate($perPage)
                 ->withQueryString();  
```

Your approach and `'descendants' => fn($query) => $query->withSum('votes', 'vote')` are (or should be) equivalent but somehow behave slightly differently and your version produces incorrect SQL. This must be an issue deep in the Laravel core...

**Comment by guratr** [comment]
That works! 
Thanks a lot, with this my code is much simpler, and reducing queries count is always welcome.
