### ISSUE TITLE
get parent and siblings and self.

### ISSUE THREAD

**Issue by mansoorkhan96** [staudenmeir/laravel-adjacency-list#189]
Is it possible to get the parent, siblings and self?

or any possibility to merge `siblingsAndSelf` and `parent` relation.

**Comment by staudenmeir** [comment]
Hi @mansoorkhan96,
Do you just want to get the results with a single query or merge `siblingsAndSelf` and `parent` into a new relationship that you can use for eager loading etc.?

You can build the query with [`UNION`](https://laravel.com/docs/10.x/queries#unions), but I don't see a way to merge them into a new relationship.

**Comment by mansoorkhan96** [comment]
Hello @staudenmeir , I'm seeking advice on merging two relationships into one and passing it to another package. This is being applied to the comments table, where I'm aiming to display the parent record in the first row and its children below. Currently, `$ownerRecord->childrenAndSelf` serves well when the owner record is a top-level comment. However, I'm facing challenges when the `$ownerRecord` isn't a top-level comment. To address this, I'm attempting to combine `siblingsAndSelf` with `parent`. 

I found a solution/work-around which is perfect for now, I'm fetching the top-level comment each time and chaining it with `$ownerRecord->topLevel()->childrenAndSelf()`.
