### ISSUE TITLE
Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by sdudasko** [staudenmeir/laravel-adjacency-list#19]
When I try to fetch data such as:
`dd(ConfluencePage::with('descendants')->first());` I get this error

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) a' at line 1 (SQL: with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `confluence_pages` where `confluence_pages`.`parent_confluence_page_id` in (1)) union all (select `confluence_pages`.*, `depth` + 1 as `depth`, concat(`path`, '.', `confluence_pages`.`id`) from `confluence_pages` inner join `laravel_cte` on `laravel_cte`.`id` = `confluence_pages`.`parent_confluence_page_id`)) select * from `laravel_cte`)
```

I checked for special column names that could violate syntax but no success there. In model I just used the package trait and overridden `getParentKeyName()` method:

```
public function getParentKeyName()
{
    return 'parent_confluence_page_id';
}
```

**Comment by staudenmeir** [comment]
Your version of MySQL/MariaDB is not supported by the package, it requires MySQL 8.0/MariaDB 10.2:
https://github.com/staudenmeir/laravel-adjacency-list#compatibility

Unfortunately, older versions of MySQL/MariaDB don't support common table expressions.

**Comment by sdudasko** [comment]
@staudenmeir thanks. I am calling this query only one time and I know it is not the best solution but could you advise me how to correct the query to satisfy the syntax?

**Comment by staudenmeir** [comment]
What version of MySQL/MariaDB are you using?

**Comment by sdudasko** [comment]
It's MySQL 5.7

**Comment by staudenmeir** [comment]
It's not possible to use the package with MySQL 5.7.

You would need to upgrade to MySQL 8.0 or use a different database engine.
