### ISSUE TITLE
Support to Firebird

### ISSUE THREAD

**Issue by gssj85** [staudenmeir/laravel-adjacency-list#197]
Hi,

I would like to contribute with support to Firebird however this would be my very first contribution I'm not sure where to start, I'm a mid-level developer but with some guidance I could make the adjustments to add Firebird, they look minor.

**Comment by staudenmeir** [comment]
Hi @gssj85,
The first step would be to add support for Firebird to the underlying CTE package:
https://github.com/staudenmeir/laravel-cte

Are you using https://github.com/harrygulliford/laravel-firebird to connect to Firebird?

**Comment by gssj85** [comment]
> Hi @gssj85, The first step would be to add support for Firebird to the underlying CTE package: https://github.com/staudenmeir/laravel-cte
> 
> Are you using https://github.com/harrygulliford/laravel-firebird to connect to Firebird?

Thanks for the guidance and yes I'm using https://github.com/harrygulliford/laravel-firebird

**Comment by staudenmeir** [comment]
Just in the last few weeks, the CTE package added support for new database drivers. Take inspiration from them:
https://github.com/staudenmeir/laravel-cte/pull/48/files
https://github.com/staudenmeir/laravel-cte/pull/50/files

**Comment by staudenmeir** [comment]
And let me know if you have any questions.

**Comment by staudenmeir** [comment]
https://github.com/staudenmeir/laravel-cte/issues/54

**Comment by staudenmeir** [comment]
What part of the package would you like to use with Firebird? [Trees](https://github.com/staudenmeir/laravel-adjacency-list?tab=readme-ov-file#trees-one-parent-per-node-one-to-many) or [graphs](https://github.com/staudenmeir/laravel-adjacency-list?tab=readme-ov-file#graphs-multiple-parents-per-node-many-to-many)?

**Comment by gssj85** [comment]
> What part of the package would you like to use with Firebird? [Trees](https://github.com/staudenmeir/laravel-adjacency-list?tab=readme-ov-file#trees-one-parent-per-node-one-to-many) or [graphs](https://github.com/staudenmeir/laravel-adjacency-list?tab=readme-ov-file#graphs-multiple-parents-per-node-many-to-many)?

I did implement "manually" the tree functionality I needed, the crucial logic I got from your lib by inspecting the code (thank you very much).

If I can suggest I think it's most important to get the CTE working first, look at what I had to do without laravel-cte haha:

`return '(WITH '
            . "conta_receber_query AS ($conta_receber), "
            . "conta_pagar_query AS ($conta_pagar)"
            . PHP_EOL
            . "$acrescimo_desconto) as CONTAS";`
            
I put that inside a ->from()

But if you can get this working too, kudos to you, just think the most "urgent" is the CTE...

**Comment by staudenmeir** [comment]
I've released a new version with support for Firebird.

**Comment by gssj85** [comment]
Nice, thank you. Unfortunatelly I'm on Laravel 9 still so no CTE to me hehe but I think we will be upgrading the project to 10 or 11 "soon". =)
