### ISSUE TITLE
Data too long for column 'path' at row 1

### ISSUE THREAD

**Issue by jnbn** [staudenmeir/laravel-adjacency-list#2]
If you're using MySQL in strict mode I think recursive query results an error if it has more than x characters.

I managed to fix it when I changed the query for casting 255 characters but it may end up with just getting ie 50-60 results which we don't prefer.

Any suggestions on how to fix it without disabling the strict mode?

**Comment by staudenmeir** [comment]
I've released a new version that sets the string length to 65535. I hope that's sufficient for all use cases.

**Comment by jnbn** [comment]
Thanks a lot 👍
