### ISSUE TITLE
Tree with orderBy

### ISSUE THREAD

**Issue by sagar-noovosoft** [staudenmeir/laravel-adjacency-list#20]
Hi 👋 

I'm trying to use `orderBy` with `tree()`

### Code
```
Product::query()
            ->tree()
            ->whereNull('parent_id')
            ->orderBy(\DB::raw('FIELD(type, "type1", "type2", "type3")'))
            ->orderBy('name')
            ->get()
```

In above code if I do not specify condition for `parent_id` then it returns all records at first level

Also no effect of orderBy in the result of above query

**Comment by staudenmeir** [comment]
> In above code if I do not specify condition for parent_id then it returns all records at first level

This is actually the expected behavior of the `tree()` scope.

You can get nested results with a recursive relationship:

```php
class Product extends Model
{
    public function children()
    {
        return $this->hasMany(self::class, 'parent_id')->with('children');
    }
}

Product::whereNull('parent_id')->with('children')->get();
```

You would need to add the `orderBy()` clauses to the query and the relationship.

**Comment by sagar-noovosoft** [comment]
Thanks @staudenmeir 🙂
