### ISSUE TITLE
column not found hasManyOfDescendantsAndSelf

### ISSUE THREAD

**Issue by hamadaacc** [staudenmeir/laravel-adjacency-list#200]
public function recursiveEmployees(): \Staudenmeir\LaravelAdjacencyList\Eloquent\Relations\HasManyOfDescendants
    {
        return $this->hasManyOfDescendantsAndSelf(Employee::class,'entity_id','id');
    }

 $this->treeOfEntity = Entity::withCount('recursiveEmployees')->get();

        dd($this->treeOfEntity);

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entities.id' in 'where clause'

what i'm missing here ? 
thank you

**Comment by hamadaacc** [comment]
SELECT
  `entities`.*,
  (
    WITH RECURSIVE `laravel_cte` AS (
      (
        SELECT
          *,
          1 AS `depth`
        FROM
          `entities` AS `laravel_reserved_0`
        WHERE
          `laravel_reserved_0`.`parent_id` = `entities`.`id`
      )
      UNION ALL
      (
        SELECT
          `entities`.*,
          `depth` + 1 AS `depth`
        FROM
          `entities`
          INNER JOIN `laravel_cte` ON `laravel_cte`.`id` = `entities`.`parent_id`
      )
    )
    SELECT
      count(*)
    FROM
      `employees`
    WHERE
      `employees`.`entity_id` IN (
        SELECT
          `id`
        FROM
          `laravel_cte`
      )
  ) AS `recursive_employees_count`
FROM
  `entities`

**Comment by staudenmeir** [comment]
Hi @hamadaacc,
Are you using MariaDB?

**Comment by hamadaacc** [comment]
Mysql

**Comment by hamadaacc** [comment]
![image](https://github.com/staudenmeir/laravel-adjacency-list/assets/71518973/d19dd089-0442-46b1-9d17-c050588bdea7)

**Comment by hamadaacc** [comment]
composer.json

**Comment by hamadaacc** [comment]
![image](https://github.com/staudenmeir/laravel-adjacency-list/assets/71518973/2c6b30d5-3979-47b1-8778-ddb930ca2a34)

**Comment by staudenmeir** [comment]
You are using MariaDB, not MySQL. Unfortunately, MariaDB doesn't support this kind of query yet:
https://jira.mariadb.org/browse/MDEV-19077

**Comment by hamadaacc** [comment]
thank you for your kind support

**Comment by Napsty** [comment]
@staudenmeir We've experienced a similar issue with laravel-adjacency-list with MariaDB 10.5 due to the usage of external table reference (as you mentioned in your comment). I suggest to remove or at least adjust MariaDB listed as compatible on the README:

![image](https://github.com/staudenmeir/laravel-adjacency-list/assets/3702203/e4a246d3-aea4-4005-a241-181c1bcc1aee)

Maybe an older version, before using these kind of queries referencing another table, was working correctly with MariaDB.

**Comment by staudenmeir** [comment]
The package didn't change here. Queries like yours that require CTEs with external references have never worked on MariaDB. All other queries work fine.
