### ISSUE TITLE
ModelName::tree()->get() gives "SQLSTATE[HY093]: Invalid parameter number"

### ISSUE THREAD

**Issue by kde99** [staudenmeir/laravel-adjacency-list#204]
Hello everyone!

I just added this package to my Laravel project (currently on 10.28, laravel-adjacency-list version is 1.13.9). I have added  
```php
use HasRecursiveRelationships;

protected function getPathSeparator(): string
{
    return "'/'";
}
```
to my model class.

When I try to run a simple query against it such as:
```php
TicketEsemenyek::tree()->get()

OR

TicketEsemenyek::withRecursiveQueryConstraint(function (Builder $query) {
    $query->where("ticket_esemenyek.ticket_id", "=", 2);
}, function () {
    return TicketEsemenyek::tree()->get();
});
```

I get the following error: `SQLSTATE[HY093]: Invalid parameter number`. I have tried to run the generated query (shown on the debug screen up top) and it works, and gives the correct results when ran in the mysql console (I am running dolt, but it is mysql compatible). 
The query the debug screen is showing is (this is already prepared I assume):
```sql
WITH RECURSIVE `laravel_cte` AS (
  (
    SELECT
      *,
      0 AS `depth`,
      cast(`id` AS char(65535)) AS `path`
    FROM
      `ticket_esemenyek`
    WHERE
      `parent_id` IS NULL
  )
  UNION ALL
  (
    SELECT
      `ticket_esemenyek`.*,
      `depth` + 1 AS `depth`,
      concat(`path`, '/', `ticket_esemenyek`.`id`)
    FROM
      `ticket_esemenyek`
      INNER JOIN `laravel_cte` ON `laravel_cte`.`id` = `ticket_esemenyek`.`parent_id`
  )
)
SELECT
  *
FROM
  `laravel_cte`
```
And at the bottom the RAW SQL is given as: 
```sql
with recursive `laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from `ticket_esemenyek` where `parent_id` is null) union all (select `ticket_esemenyek`.*, `depth` + 1 as `depth`, concat(`path`, ?, `ticket_esemenyek`.`id`) from `ticket_esemenyek` inner join `laravel_cte` on `laravel_cte`.`id` = `ticket_esemenyek`.`parent_id`)) select * from `laravel_cte`
```

I have tried with and without strict_mode: it makes no difference. What could be causing the issue?

Thank you for your replies

**Comment by staudenmeir** [comment]
Do you have a way to connect your app to a MySQL database and test the query with that?

If not, please put `dd($query, $bindings);` in line `800` of `L:\partneroldal\vendor\laravel\framework\src\Illuminate\Database\Connection.php` and run the query again.
