### ISSUE TITLE
Get descendants based on children existence 

### ISSUE THREAD

**Issue by tiagomatosweb** [staudenmeir/laravel-adjacency-list#205]
Hi, 
I have fetched the model Category previously.
This model Category hasMany Products

How would I get all the descendants tree that have at least one children or one Product?

Currently I'm going this
```$category->descendants->load(['products'])->toTree();```

However, it is bringing the "Category C" which doesn't have either children or product. 

```
[
    {
        "id": 1,
        "name": "Category A",
        "children": [],
        "products": [
            {
                "id": 1,
                "name": "Iphone"
            }
        ]
    },
    {
        "id": 2,
        "name": "Category B",
        "children": [
            {
                "id": 3,
                "name": "Category C",
                "children": [],
                "products": []
            }
        ],
        "products": [
            {
                "id": 2,
                "name": "Macbook"
            }
        ]
    }
]
```

Much appreciated

**Comment by staudenmeir** [comment]
Hi @tiagomatosweb,
Use [`has()`](https://laravel.com/docs/10.x/eloquent-relationships#querying-relationship-existence):

```php
$category->descendants()
    ->where(
        fn($query) => $query->has('children')->orHas('products')
    )->get()
    ->load(['products'])
    ->toTree();
```

**Comment by tiagomatosweb** [comment]
I swear to got I did this, buuuuuuut I missed the get() part! 😁

That worked, tks a lot @staudenmeir
