### ISSUE TITLE
Parent has many Children trees 

### ISSUE THREAD

**Issue by KarlisJ** [staudenmeir/laravel-adjacency-list#206]
I'm struggling to understand how to set up my use case.

I have `Registry` hasMany `Component`s hasMany `Field`s. 

```php
class Registry extends Model {
   public function components(): HasMany {
      return $this->hasMany(Components::class);
   }
}

class Component extends Model {
   public function fields(): HasMany {
      return $this->hasMany(Field::class);
   }
}
```
I'm querying single `Registry` like this
```php
Registry::with('components.fields')->first();
```
and then I can build out the Registry form with 2 foreach loops
```php
foreach ($registry->components as $component) {
    // Build component element
    foreach ($component->fields as $field) {
        // Add fields to component element
    }
}
```

I want to use this package make Components a nested tree. The end goal would be to still query the full tree of `Registry -> Components Tree -> Fields` and recursively build the elements for form with the unknown depth of components.

However, I need help defining the relationships to fetch the registry with the whole tree. At this point everything I've tried has yielded results that quite honestly doesn't make sense to me which points that I'm failing to understand something fundamental in how the package should be used.

**Comment by staudenmeir** [comment]
Hi @KarlisJ,
Please share the structure/migrations of all three tables.

**Comment by KarlisJ** [comment]
@staudenmeir thank you for looking into my case. 

Providing a stripped version of migrations. 
```php
Schema::create('registries', function (Blueprint $table) {
    $table->id();
    $table->string('name');
   // ..
});

Schema::create('components', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->unsignedInteger('registry_id');
    $table->unsignedInteger('parent_id');
   // ..
});

Schema::create('fields', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->unsignedInteger('component_id');
   // ..
});
```
It could be that I'll need to set the `components.registry_id` to `nullable()` so that something like `Registry::first()->components` returns only the root level components for the tree, but ideally, I'd like to have an option to access all components as flat list as well. 

To illustrate the expected structure I've set up a dummy database seeder
```php
public function run(): void
{
    $registry = Registry::factory()->create();

    $roots = Component::factory()
        ->count(4)
        ->create([
            'registry_id' => $registry->id
        ]);

    foreach ($roots as $root) {
        $second_levels = Component::factory()
            ->count(3)
            ->create([
                'registry_id' => $registry->id,
                'parent_id' => $root->id
            ]);
        foreach ($second_levels as $second_level) {
            $third_levels = Component::factory()
                ->count(3)
                ->create([
                    'registry_id' => $registry->id,
                    'parent_id' => $second_level->id
                ]);
            foreach ($third_levels as $third_level) {
                Field::factory()
                    ->count(2)
                    ->create([
                        'component_id' =>$third_level->id
                    ]);
            }
        }

        $second_level_with_fields = Component::factory()
            ->create([
                'registry_id' => $registry->id,
                'parent_id' => $root->id
            ]);

        Field::factory()
            ->count(2)
            ->create([
                'component_id' =>$second_level_with_fields->id
            ]);
    }
}
```

In this seeder, I create 
- a single Registry 
- component three consisting of 
    - 4 root components (depth 1) 
    - each root has 3 components (depth 2)
    - each has 2 more components (depth 3)
- fields are attached to some depth = 2 and all depth = 3 components.

Note that a component can have child components or fields but never both. However, this is a logic that I plan to handle at the application level. 

I intend to query the entire tree most efficiently and cache the results. The cached results are then used in two ways
- recursively walk through the tree and dynamically create web form consisting of components and fields.
- walk through all fields (flat, not caring about the tree structure) and build a table header from them. 

I hope this helps to understand my case.

**Comment by staudenmeir** [comment]
Thanks.

> I want to use this package make Components a nested tree.

Do you have a specific structure in mind that the query result should have?

> and then I can build out the Registry form with 2 foreach loops

How would you look like to loop over the tree?

> At this point everything I've tried

Can you share your tries and why they didn't work?
