### ISSUE TITLE
Problem with custom path

### ISSUE THREAD

**Issue by byChamaco** [staudenmeir/laravel-adjacency-list#208]
Hello,

When I make a custom path for a relationship that has a multiples ancestors, the new field that is created has a max characters which causes the path to be cut.
For example: "Car > Motorbike > Bus > Airplane"   it transforms in  "Car > Motorbike > Truck > Airp".

This happens because when a varchar is cast, by default SQL adds a maximum of 30 characters.

So that there is no maximum number of characters, you should replace the varchar with varchar(max) in the following file src/Query/Grammars/SqlServerGrammar.php and mainly this part:

![image](https://github.com/staudenmeir/laravel-adjacency-list/assets/73342186/54b6a6b1-6c15-41af-bdf5-3a35adba1d70)

Thank you so much

Greetings

**Comment by staudenmeir** [comment]
Hi @byChamaco,
Thanks, I released a new version.

**Comment by byChamaco** [comment]
Hi @staudenmeir,
Perfect, thank you very much.
