### ISSUE TITLE
Polymorphic self referencing support

### ISSUE THREAD

**Issue by obtoon** [staudenmeir/laravel-adjacency-list#21]
I assume this package doesn't support this, and I'll have to use the laravel cte package directly.

Let's say I have two classes: Parent and Child. The Child class either belongs to a Parent, or another Child, through a polymorphic relationship.

Parent
id - integer

Child
id - integer
groupable_id - integer
groupable_type - string (either Child or Parent).

The problem with this is, when I use HasRecursiveRelationships on the Child model, and return groupable_id from getParentKeyName(), using $child->descendants; will also return any other Child models that have groupable_id that is equal to $child->id, even though that groupable_id may be referencing a Parent model and not $child.

Any support for this currently?

**Comment by obtoon** [comment]
Not to worry, my current solution is to override each of the trait methods, and just add a local scope to each of them with ->where('groupable_type', 'Child');

**Comment by staudenmeir** [comment]
No, this kind of relationship is not supported. Does your current solution work for all use cases?

**Comment by obtoon** [comment]
Not sure, going to write a couple of tests to make sure and I'll get back to you.

**Comment by obtoon** [comment]
Didn't manage to solve this easily. I got most of the way, but it ended up being way to unmaintainable. I just ended up changing my implementation by having separate fields for the self relation and the parent one.

Thanks.
