### ISSUE TITLE
Has many of a model where ancestors may belong to it.

### ISSUE THREAD

**Issue by saade** [staudenmeir/laravel-adjacency-list#210]
I am currently working on a scenario where I have a Subject model with a hierarchical structure, and each subject belongs to a Department. But also, a Subject may heve its `department_id` null but one of its ancestors have the foreign key to the Department.

In my use case, I need to retrieve subjects that belong to a specific department, as well as subjects that have a department_id of null but their ancestors have a filled department_id.

Here's my. table structure:

Departments table
| id | other_columns |
|----|---------------|
| 1  | ...           |
| 2  | ...           |
| 3  | ...           |

Subjects Table
| id | parent_id | department_id | other_columns |
|----|-----------|---------------|---------------|
| 1  | null      | 1             | A           |
| 2  | 1         | null          | A.A           |
| 3  | 1         | null          | A.B           |
| 4  | 2         | 2             | A.A.A           |
| 5  | 2         | null          | A.A.B           |
| 6  | 4         | null          | A.A.A.A           |

With the following query:
```php
Departments::find(1)->subjects
```

i want to retrieve the `A`, `A.A` and `A.B` event though `A.A` and `A.B` doesnt have the `department_id` filled (but one of its ancestors have).

I also need the inverse relationship:
```php
Subject::find('A.B')->department // Department 1 event though department_id is null.
```

I know its sounds much, but i'm willing to pay for your help, thank you!

**Comment by staudenmeir** [comment]
Hi @saade,
Shouldn't this be `4`?

![Bildschirmfoto 2023-11-25 um 15 26 30](https://github.com/staudenmeir/laravel-adjacency-list/assets/1853169/025bfd4b-8ccb-4761-9eff-30427f8dc7a4)

**Comment by saade** [comment]
I dont think so? A.A.A and A.A.B are siblings

**Comment by staudenmeir** [comment]
> i want to retrieve the A, A.A and A.B

I asked because you didn't include `A.A.B` here. Why should it not be part of this result despite belonging to department `1` (as a descendant of subject `1`)?

**Comment by saade** [comment]
> > i want to retrieve the A, A.A and A.B
> 
> I asked because you didn't include `A.A.B` here. Why should it not be part of this result despite belonging to department `1` (as a descendant of subject `1`)?

oh, yeah my bad mate, it should include a.a.b too 😅

**Comment by saade** [comment]
Just to be completly clear:

It should not include `A.A.A` nor `A.A.A.A` even though `A.A.A`'s parent belongs to department 1. Because `A.A.A` belongs to department `1` so it overrides its parent department `1`.

**Comment by saade** [comment]
Made a little visual representation =)

<img width="1053" alt="image" src="https://github.com/staudenmeir/laravel-adjacency-list/assets/14329460/0924179d-c497-4c82-82a1-3491f17c5157">

**Comment by staudenmeir** [comment]
> Departments::find(1)->subjects

It's not possible to define a relationships here, but you can run a "normal" query:

```php
$department = Departments::find(1);

$subjects = Subject::withRecursiveQueryConstraint(function (Builder $query) {
    $query->whereNull('subjects.department_id');
}, function () use ($department) {
    $constraint = function ($query) use ($department) {
        $query->where('department_id', $department->id);
    };

    return Subject::treeOf($constraint)->get();
});
```

> Subject::find('A.B')->department // Department 1 event though department_id is null.

You can define a relationship for this case using [concatenation](https://github.com/staudenmeir/laravel-adjacency-list#concatenation):

```php
class Subject extends Model
{
    // Install https://github.com/staudenmeir/eloquent-has-many-deep
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    public function rootDepartment()
    {
        return $this->hasOneDeepFromRelations(
            $this->ancestorsAndSelf(),
            (new static)->department()
        )->orderByDesc('depth');
    }
}

$department = Subject::find('A.B')->rootDepartment;
```

**Comment by saade** [comment]
Hey! Thanks for that!

I didnt have the time to test it as i'm on another part of the project, but i'll let you know. Did you have a sponsor profile?

**Comment by staudenmeir** [comment]
I have a PayPal page: https://paypal.me/JonasStaudenmeir
