### ISSUE TITLE
limit hasManyOfDescendants depth

### ISSUE THREAD

**Issue by ccerrillo** [staudenmeir/laravel-adjacency-list#213]
Hi

is it possible to limit the depth of a hasManyOfDescendants relationship?

What I'm trying to achieve is to get all users with the operations of their 'children' up to a depth of 3. For example:

Given this user tree:

```mermaid
graph LR;
    1-->1.2;
    1.2-->1.2.3;
    1.2.3-->1.2.3.4;
    1.2.3.4-->1.2.3.4.5;
    1.2.3.4.5-->1.2.3.4.5.6;
```

I should get:

| User       | Operations                                               |
|------------|----------------------------------------------------------|
| 1          | All operations of users 1.2, 1.2.3, and 1.2.3.4         |
| 1.2        | All operations of users 1.2.3, 1.2.3.4, and 1.2.3.4.5   |
| 1.2.3      | All operations of users 1.2.3.4, 1.2.3.4.5, and 1.2.3.4.5.6 |
| 1.2.3.4    | All operations of users 1.2.3.4.5 and 1.2.3.4.5.6       |
| 1.2.3.4.5  | All operations of users 1.2.3.4.5.6                     |
| 1.2.3.4.5.6| No operations 

Here's the schema:

```
Schema::create('users', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->unsignedBigInteger('parent_id')->nullable();
    $table->timestamps();
    $table->foreign('parent_id')->references('id')->on('users');
});

Schema::create('operations', function (Blueprint $table) {
    $table->id();
    $table->string('product');
    $table->decimal('price', 10, 2);
    $table->unsignedBigInteger('user_id');
    $table->timestamps();
    $table->foreign('user_id')->references('id')->on('users');
});
```

And this is the User model:

```
class User extends Eloquent
{

    public function operations()
    {
        return $this->hasMany(Operations::class);
    }

    public function recursiveOperations()
    {
        return $this->hasManyOfDescendants(Operations::class);
    }

    public function users()
    {
        return $this->hasManyOfDescendants(self::class);
    }

}
```

And here's my attempt, which works if applied to a single user but not for all users:

```
$operations = User::with(["recursiveOperations" => function ($query) {
    $query->withIntermediateScope(
        'depth',
        function ($query) {
            $query->whereDepth('<=', 3);
        }
    );
}])->get();
```
I've also tried using hasManyDeepFromRelations without any luck. Hope you can shed some light on this for me.

**Comment by ccerrillo** [comment]
This looks like I've got it sorted out, does it seem good to you?

```
$operations = User::with(["descendants"=>function($query) {
    $query->whereDepth('<=', 3)->with("operations");
}])->get();
```

**Comment by staudenmeir** [comment]
Yes 👍
