### ISSUE TITLE
Larastan types `ancestorsAndSelf` property as `Model|null` instead of Collection

### ISSUE THREAD

**Issue by calebdw** [staudenmeir/laravel-adjacency-list#216]
Hello!

Larastan is unable to detect that the `Ancestors` relation is plural and it incorrectly types the property as `Model|null` instead of `Collection<int, Model>`>

It appears that the convention is to use `Many` and `MorphTo` in the relation class names to denote the special types ([laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) also does this):

https://github.com/larastan/larastan/blob/6c656c7f7f15e0e5340f7afff263f9b0a720a056/src/Properties/ModelRelationsExtension.php#L113-L141

Granted, this is a rather brittle approach but not sure if it would be easier to rename the relation to something like `HasManyAncestors` or to update Larastan to be more robust. 

CC: @canvural

Thanks!

**Comment by staudenmeir** [comment]
Hi @calebdw,
Are you using the package's model hook?
https://github.com/staudenmeir/laravel-adjacency-list#included-relationships

> Note: If you are using [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper), this package provides a [model hook](https://github.com/barryvdh/laravel-ide-helper#model-hooks) that will correctly add relations when generating the type hints. To get the correct type hints, in the [ide-helper.php](https://github.com/barryvdh/laravel-ide-helper/blob/master/config/ide-helper.php) config file, add \Staudenmeir\LaravelAdjacencyList\IdeHelper\RecursiveRelationsHook::class to the model_hooks array.

**Comment by canvural** [comment]
Probably we can change Larastan to use the types rather than checking the class names. `Ancestors` extends `HasMany` so we should be able to detect. I don't remember why did we do the checks with the class names instead of types.

**Comment by calebdw** [comment]
@staudenmeir, 

I am using model hooks for the `ide-helper` package, however, Larastan is completely unrelated to the `ide-helper` package and they can have negative interactions with each other. Because of this, the `ide-helper` output is written to a hidden file that is not analyzed by larastane

**Comment by staudenmeir** [comment]
> Granted, this is a rather brittle approach but not sure if it would be easier to rename the relation to something like HasManyAncestors or to update Larastan to be more robust.

This needs to be changed in Larastan. Renaming the relations would be a major breaking change.
