### ISSUE TITLE
escapeWhenCastingToString ?

### ISSUE THREAD

**Issue by alextanasa91** [staudenmeir/laravel-adjacency-list#218]
can you tell me what i do wrong please?
i try to use this package with eloquent outside of laravel (codeigniter 4) and i m facing this error 

Staudenmeir\LaravelAdjacencyList\Eloquent\Collection Object ( [items:protected] => Array ( ) [escapeWhenCastingToString:protected] => )

my code looks like 

use Illuminate\Database\Eloquent\Model as Eloquent;

use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class Categories extends Eloquent
{
    use HasRecursiveRelationships;
    protected $fillable = [
        'cat_name', 'parent_id'
    ];

 }

and in controller
 public function index()
    { 
        $data = Categories::tree()->get()->toTree();
        print_r($data);

or 
 $cat = Categories::tree()->get();
        $tree = $cat->toTree();
        print_r($tree);

        
    }
the error persist and i can't figure out what im doing wrong?

**Comment by staudenmeir** [comment]
Hi @alextanasa91,
What exactly is the error? That the result is empty?
