### ISSUE TITLE
[Question] Get level of node

### ISSUE THREAD

**Issue by vanthao03596** [staudenmeir/laravel-adjacency-list#22]
Can i get level of single node ?

**Comment by patrickomeara** [comment]
https://github.com/staudenmeir/laravel-adjacency-list#depth

**Comment by staudenmeir** [comment]
Do you want to get the (relative) level of a node in a query result (see @patrickomeara's link)?

Or do you want to get the (absolute) level from a node's ID/model instance?

**Comment by vanthao03596** [comment]
@staudenmeir I want get node ID 10 info with level.

**Comment by staudenmeir** [comment]
You can only get the node's level from its root ancestor:

```php
$node = YourModel::find(10);
$level = abs($node->ancestors->last()->depth);
````

**Comment by vanthao03596** [comment]
Thanks @staudenmeir 
I tried Taxon::tree()->where('id', 51)->first() and get correct result
Here is my tree
![1](https://user-images.githubusercontent.com/34786441/77218032-bddf2280-6b59-11ea-9a88-1484524285b9.png)
Here is tinker result
![2](https://user-images.githubusercontent.com/34786441/77218043-d3ece300-6b59-11ea-8c76-7e63e9d69b56.png)
Here is generate query by debugbar
![Screenshot from 2020-03-21 09-55-54](https://user-images.githubusercontent.com/34786441/77218082-4fe72b00-6b5a-11ea-8e9f-a3d1848dc814.png)

**Comment by staudenmeir** [comment]
This also works, but the query will take longer the bigger your tree gets (the query needs to build the _whole_ tree just to return a single node).

The approach I posted executes two queries, but their runtime is stable.

**Comment by vanthao03596** [comment]
Thank for help. You are amazing
Keep up the good work !
