### ISSUE TITLE
toTree on graph ancestors not working properly

### ISSUE THREAD

**Issue by mathiasoem** [staudenmeir/laravel-adjacency-list#220]
I might be missing something here, but do you have any means of making toTree work on a collection of ancestors?

When calling `$child->ancestors->toTree()` the tree will create an endless loop of the top parent, caused by improper (reverse) pivot relations.

The model relationship is a simple pivot with parent_id, child_id.

The use case:

I want to show a tree with both ancestors and descendants of a given model. I only want ancestors related to the given model contained in the tree, and therefore cannot call `->descendants->toTree()` on the top level parent.

**Comment by Thanzex** [comment]
@mathiasoem This does not seem resolved, any reason why the issue was closed?
