### ISSUE TITLE
How to recursively replicate models

### ISSUE THREAD

**Issue by sts-ryan-holton** [staudenmeir/laravel-adjacency-list#229]
I'm wondering how I can reliably duplicate/replicate models in Laravel with this package. I'll attach my model structure and how it might look below. I essentially need to be able to clone a whole `MarketingAutomation` model. My `MarketingAutomationAction` model is the one that utilises this package and has the following key relationships:

```php
/**
 * Get the children of the action
 */
public function children(): HasMany
{
    return $this->hasMany(MarketingAutomationAction::class, 'parent_id');
}

/**
 * Get the conditions for the action
 */
public function conditions(): HasMany
{
    return $this->hasMany(MarketingAutomationActionCondition::class);
}
```

The `children` relationship is the one that is effectively the "tree"

I have three models:

- `MarketingAutomation`
- `MarketingAutomationAction`
- `MarketingAutomationActionCondition`

Based on these models, the `MarketingAutomationAction` is the model which contains the `parent_id` table and functionality around that package. In addition, this model also a foreign id column to `marketing_automation_id`.

`MarketingAutomationActionCondition` models are linked to actions. So in the end, we may end up with the following hierarchy:

- Marketing automation
  - Marketing automation action
    - Marketing automation action condition
    - Marketing automation action condition
  - Marketing automation action
    - Marketing automation action
      - Marketing automation action condition
    - Marketing automation action
      - Marketing automation action
  - Marketing automation action

**Comment by staudenmeir** [comment]
How is `MarketingAutomation` related to `MarketingAutomationAction`?

**Comment by sts-ryan-holton** [comment]
`MarketingAutomation`:

```php
/**
 * Get the marketing automation actions that this model has
 */
public function parentActions(): HasMany
{
    return $this->hasMany(MarketingAutomationAction::class, 'marketing_automation_id', 'id')
        ->whereNull('parent_id');
}

/**
 * Get the marketing automation actions that this model has
 */
public function actions(): HasMany
{
    return $this->hasMany(MarketingAutomationAction::class, 'marketing_automation_id', 'id')
        ->orderBy('processing_order', 'asc');
}
```

`MarketingAutomationAction`

```php
/**
 * Get the marketing automation that owns this model
 */
public function marketingAutomation(): BelongsTo
{
    return $this->belongsTo(MarketingAutomation::class);
}
```

**Comment by staudenmeir** [comment]
You want to clone the `MarketingAutomation` model's actions and _all_ of their descendants (recursive children)?

**Comment by sts-ryan-holton** [comment]
That's correct. For each action there could be one or more `MarketingAutomationActionCondition` models. My action model has the `marketing_automation_id` column and the `parent_id` column.

**Comment by staudenmeir** [comment]
Can the actions of a `MarketingAutomation` model be related to each other?

For example: The model is associated to the actions `1` and `2`. Can `2` be a descendant of `1`? Or do they _always_ belong to different trees (i.e. have different roots)?
