### ISSUE TITLE
Search/Filter nested list

### ISSUE THREAD

**Issue by vatsake** [staudenmeir/laravel-adjacency-list#238]
Is it possible to search/filter nested items that match a criteria and return from root to the child item?

For example if I have the following data, and I search for "Doe". It should return from 1 to 4 (tree) and excluding item with ID 3.
| id | parent_id | name |
| --- | --- | --- |
| 1 | null | John |
| 2 | 1 | Hussein |
| 3 | 1 | Applepie |
| 4 | 2 | Doe |

**Comment by staudenmeir** [comment]
Do you want to merge all results into a single tree?

**Comment by staudenmeir** [comment]
You need write a recursive method to merges the trees level by level. There's no easier way, unfortunately.

**Comment by devhammed** [comment]
I don't know if you have solved this using your own custom filter function but I solved this using the `treeOf` and `withRecursiveQueryConstraint` methods of the package:

<img width="917" alt="image" src="https://github.com/user-attachments/assets/bcc2bed4-f9ee-4186-ae20-86b06b4d4b12">

<img width="604" alt="image" src="https://github.com/user-attachments/assets/1b565e80-0159-45ff-a382-75698606ec0f">
