### ISSUE TITLE
Error  This database engine does not support inserting while ignoring errors after add this package

### ISSUE THREAD

**Issue by budiardianata** [staudenmeir/laravel-adjacency-list#239]
Hi @staudenmeir. 
I've install fresh laravel 11 project include jetstream scafolding and i use SQL Server 2022 for the database. 
it work fine before i add this package. 
after i add this package i've error `  **RuntimeException  This database engine does not support inserting while ignoring errors.**`  on authentication page.
![image](https://github.com/staudenmeir/laravel-adjacency-list/assets/17608807/900dc56b-2045-4e07-af97-eaac9ccb1457)

**Comment by staudenmeir** [comment]
Hi @budiardianata,
I looked into it and found that this is a bug in Laravel. I'll submit a PR.

**Comment by staudenmeir** [comment]
The [PR](https://github.com/laravel/framework/pull/51547) got merged and will get released with the next version.

**Comment by budiardianata** [comment]
Hi @staudenmeir, Laravel has been released new version and this issues solved. Thanks.
