### ISSUE TITLE
[Feature Request] Customisable path key name

### ISSUE THREAD

**Issue by mdpoulter** [staudenmeir/laravel-adjacency-list#24]
Sorry, me again!

It doesn't appear to be possible currently, but I'm wondering if it would be possible to add an additional customisation to the generated `path` field, specifically a way to set the key name to be used in the path.

My use case is to generate slug-based URLs which include all ancestors' slugs, for example `slug-one/slug-two/slug-three`. I am currently doing this after the database query has been run, but this increases the number of hydrated models quite quickly.

I imagine it would require a new method which would look something like this:

```php
class Page extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function getPathKeyName()
    {
        return 'slug';    // This would default to 'id' if not set
    }

    public function getPathSeparator()
    {
        return '/';    // To create the URL from the example above
    }
}
```

Is this possible to do without breaking the current functionality? I'd be happy to try put together a PR for it if you'd like, but my knowledge of CTEs is quite limited!

Thank you!

**Comment by staudenmeir** [comment]
It's not possible to customize the existing path variable like this because it's used internally, but I can add a new feature for additional custom paths. I'll look into it.

How are you querying the pages in your case?

**Comment by mdpoulter** [comment]
Ah I see! I think it would be a great addition 👍 

I'm currently using something like this:

```php
$page = Page::with('ancestorsAndSelf')->first();

$path = $page->ancestorsAndSelf->implode('slug', '/');
```

This, however, hydrates the models of all the ancestors, so when I want to do this with several pages, it starts to add up!

**Comment by staudenmeir** [comment]
The latest release adds custom paths:
https://github.com/staudenmeir/laravel-adjacency-list#custom-paths

```php
class Page extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function getCustomPaths()
    {
        return [
            [
                'name' => 'slug_path',
                'column' => 'slug',
                'separator' => '/',
            ],
        ];
    }
}
```

**Comment by sagar-noovosoft** [comment]
@staudenmeir do you have any idea how we can get custom path from root node to current node?

**Comment by staudenmeir** [comment]
@sagar-noovosoft Are you only retrieving a single node?

**Comment by sagar-noovosoft** [comment]
@staudenmeir I've tried both of the following but nothing seems working for me,

- $product = Product::find(7)->descendantsAndSelf;

I'm expecting
```
echo $product[0]->slug_path; // product-1/product-4/product-7
```
but getting,
```
echo $product[0]->slug_path; // product-7
```

- $product = Product::find(7)->ancestorsAndSelf;

Output,
```
echo $product[0]->slug_path; // product-7
```

@staudenmeir how can I get full custom path from root node to current node?

**Comment by staudenmeir** [comment]
`slug_path` can only contain the whole path if you run a query like `Product::tree()->get()`. You could use `Product::tree()->find(7)`, but that would be quite inefficient (it builds the whole tree internally).

In your case, you would need to build slug path manually (the second option is slightly faster):

```php
$path = $product->ancestorsAndSelf()->pluck('slug')->reverse()->implode('/');
$path = $product->ancestors()->pluck('slug')->reverse()->add($product->slug)->implode('/');
```
