### ISSUE TITLE
Incorrect count for belongsToManyOfDescendants

### ISSUE THREAD

**Issue by mansoorkhan96** [staudenmeir/laravel-adjacency-list#240]
I have a category model with `HasRecursiveRelationships` trait and i am trying the get descendant count. 

```php
Category::query
  ->withCount([
        'children',
        'descendantPosts'
    ])
   ->get()
```

```php
class Category extends Model
{
    use HasRecursiveRelationships;
    public function posts(): BelongsToMany
    {
        return $this->belongsToMany(Post::class);
    }

    public function descendantPosts()
    {
        return $this->belongsToManyOfDescendants(Post::class);
    }
}
```

Am i missing something?

**Comment by staudenmeir** [comment]
Hi @mansoorkhan96,

> count with ->distinct() is 41 and
> without without ->distinct() is 42

What value are you expecting?

> // i have tried ->distinct() here but it partially works

What do you mean by "partially"?

**Comment by mansoorkhan96** [comment]
> Hi @mansoorkhan96,
> 
> > count with ->distinct() is 41 and
> > without without ->distinct() is 42
> 
> What count are you expecting?
> 
> > // i have tried ->distinct() here but it partially works
> 
> What do you mean by "partially"?

Sorry, the count is same with or without discount. I have updated the post.

I am expecting 32 results
and confirm 32 results this way.

```php
public function childrenPostsCount()
{
    return Post::query()
        ->whereHas('categories', function ($query) {
            $query->whereIn('categories.id', $this->children->pluck('id'));
        })
        ->published()
        ->count();
}
```
Also, I tried to load all the descendantPosts along with the count and it load correct record which is 32 but the count is 41

```php
Category::query
  ->with('descendantPosts') // it loads 32 records
  ->withCount([
        'children',
        'descendantPosts' // the count is 41
    ])
   ->get()
```

**Comment by staudenmeir** [comment]
> ->with('descendantPosts') // it loads 32 records

Does the `descendantPosts` relationship include `->distinct()` in this case?

**Comment by mansoorkhan96** [comment]
I might end up using following but i am not sure how to select only required columns, because adding select method returns 0 results.

```php
->with([
'children',
'descendantActivities' => fn ($query) => $query->published()->distinct()->select('activities.id')
])
```

**Comment by mansoorkhan96** [comment]
> > ->with('descendantPosts') // it loads 32 records
> 
> Does the `descendantPosts` relationship include `->distinct()` in this case?

No, let me try that.

**Comment by mansoorkhan96** [comment]
Tried removing from $query->... and added it to the relationship but still same.

**Comment by mansoorkhan96** [comment]
Let me know if i should create a reproduction repo, if that helps.

**Comment by staudenmeir** [comment]
Yes, please. A database dump would also be enough, if that's easier for you.

**Comment by mansoorkhan96** [comment]
Repo: https://github.com/mansoorkhan96/laravel-adjacency-list-issue

It includes model, migration, factories and the seeder. So if you run the `php artisan migrate:fresh --seed` command it should do it.

once you have setup the app, if you visit `/` route it should dd the query result. 

I have seeded 1 parent category, 10 child categories and 100 posts with different/random child categories. 

Expected result: it should show that the parent cateogry has 100 decendantposts but it shows 300+. However the db has only 100 posts.



Here is the dump file

[laravel-adjacency-list-issue.gz](https://github.com/staudenmeir/laravel-adjacency-list/files/15417712/laravel-adjacency-list-issue.gz)

Here is the sql query that i have on `/` route.

```sql
select "categories".*, (select count(*) from "categories" as "laravel_reserved_0" where "categories"."id" = "laravel_reserved_0"."parent_id") as "children_count", (with recursive "laravel_cte" as (select * from (select "laravel_reserved_1".*, 1 as "depth" from "categories" as "laravel_reserved_1" where "laravel_reserved_1"."parent_id" = "categories"."id") union all select "categories".*, "depth" + 1 as "depth" from "categories" inner join "laravel_cte" on "laravel_cte"."id" = "categories"."parent_id") select count(*) from "posts" inner join "category_post" on "posts"."id" = "category_post"."post_id" where "category_id" in (select "id" from "laravel_cte")) as "descendant_posts_count" from "categories" where "parent_id" is null
```

**Comment by staudenmeir** [comment]
This is the same topic as #201. That was my initial thought, but the difference between `with()` and `withCount()` threw me off. The result of `with()` is actually the wrong one.

The value of `withCount()` is higher than the number of posts in your case because some posts are connected to the category on different levels of the hierarchy and so are _different_ in that sense. If you have additional columns in the `category_post` pivot table, they can also be different for "duplicate" posts.

Use this to count distinct posts:

```php
Category::query
  ->with('descendantPosts')
  ->withCount([
        'children',
        'descendantPosts' => function ($query) {
            $query->select(DB::raw('count(distinct "posts"."id")'));
        }
    ])
   ->get()
```

**Comment by mansoorkhan96** [comment]
Right that could be it. I am away from my desk but tempted to try it right away. 

Isn't the hierarchy same for children?.  They all belong to the same parent and are siblings at the same level?

Now that you have seen the DB schema and models, do you think the approach is incorrect. Any feedback or an alternative way to achieve the same.

Thanks

**Comment by mansoorkhan96** [comment]
Just tried the query and wow it works man!

Thank you so much!

**Comment by mstaack** [comment]
thanks! had the same count issue and with the distinct clause it works now!
