### ISSUE TITLE
"Column already exists: 1060 Duplicate column name..."   WHEN depthName exist also in db- table

### ISSUE THREAD

**Issue by cmendez2121** [staudenmeir/laravel-adjacency-list#241]
Hi there,  after the last update i got an error.

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name '**nivel**',  According to the package all is good  i customized depth name  in my model
```
    public function getDepthName()
    {
        return 'nivel';
    }
```
but turns out that IF i also have that field **nivel** in the database table ( i want to store the depth) of the record/model 
and when i try to get all the Tree i get the full error as follows : 
```
"SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'nivel' (Connection: mariadb_conta, SQL: with recursive `laravel_cte` as ((select `aocg_catalogodecuentas`.*, 0 as `nivel`, cast(`id` as char(65535)) as `path` from `aocg_catalogodecuentas` where `parent_id` is null) union all (select `aocg_catalogodecuentas`.*, `nivel` + 1 as `nivel`, concat(`path`, ., `aocg_catalogodecuentas`.`id`) from `aocg_catalogodecuentas` inner join `laravel_cte` on `laravel_cte`.`id` = `aocg_catalogodecuentas`.`parent_id`)) select * from `laravel_cte`)",
```

So the generated query  is crashing for some ambiguous field names  such as "nivel" 

select `aocg_catalogodecuentas`.*.    (i have "nivel" included) and then again  (0 as nivel)
So far checking the query made some adjustments on the sql part. 
- changed nivel as nivel_depth
- on the second query in recursive code   "specified table for "nivel" due  ambiguous field name  and changed nivel to nivel_depth"

![Screenshot 2024-05-24 at 6 23 02 p m](https://github.com/staudenmeir/laravel-adjacency-list/assets/17038315/bb2e41d8-d1d0-41eb-9991-636dc00d34dc)

Now if i remove the getDepthName or leave as  return 'depth'  despite having  nivel , it works  fine , so this would be nice to mention on the documentation (possible crash on existing depth field)
```
    public function getDepthName()
    {
        return 'depth';  // this way works cause  depth does not exist on table 
    }
```
So it would be nice to let specify an existing field on the model/table  
something like 
```
    public function hasDepthField()
    {
        return true ; // True or false 
    }
```
So the package will know the depth field exist in the table and when generating the query it can avoid the query error as in my case

I'm not too god yet for package development or making PR's so that's why i'm reporting instead of doing a PR

**Comment by staudenmeir** [comment]
Hi @cmendez2121,

> Now if i remove the getDepthName or leave as return 'depth' despite having nivel , it works fine , so this would be nice to mention on the documentation (possible crash on existing depth field)

Good point, I'll add that.

> So it would be nice to let specify an existing field on the model/table

The column name that is defined by `getDepthName()` cannot exist in your database table. If you have a column with the same name as the default name `depth`, overriding `getDepthName()` is the only possible solution.

> I'm not too god yet for package development or making PR's so that's why i'm reporting instead of doing a PR

No worries.
