### ISSUE TITLE
Is it possible to use a Tree and Graph on the same model?

### ISSUE THREAD

**Issue by brecht-vermeersch** [staudenmeir/laravel-adjacency-list#243]
Hi, we have a use case where we need both, but the traits conflict.

Our current workaround is two models.

**Comment by staudenmeir** [comment]
Hi @brecht-vermeersch,
I don't see a better solution, unfortunately. It might be possible to resolve the trait conflicts, but that would require _a lot_ of work and you would still have naming conflicts (like what `$model->descendants` is referring to).

**Comment by brecht-vermeersch** [comment]
No problem, thanks!
