### ISSUE TITLE
Undefined array key 3867 (or any other number)

### ISSUE THREAD

**Issue by ali-ghanati** [staudenmeir/laravel-adjacency-list#258]
hello guys i'm having a problem when trying to modify query on eager load in most cases i fixed it with separating query in 2 parts but this time I don't know what to do

here's my code
`        $ounits = $user->activeRecruitmentScripts()
            ->whereHas('issueTime', function ($query) {
                $query->where('issue_times.title', 'شروع به همکاری');
            })
            ->with([
                'ounit.descendants' => function ($query) {
                    $query->where('unitable_type', VillageOfc::class)
                        ->with('ancestors');
                }
            ])
            ->get();`

in every scenario that i try to modify query inside closure function for this package's methods i get error undefined array key

**Comment by ali-ghanati** [comment]
oh, i forgot to say i'm on laravel 10.42 and package version is 1.13

**Comment by ali-ghanati** [comment]
even writing this way didn't help

`        $ounits = $user->activeRecruitmentScripts()
            ->whereHas('issueTime', function ($query) {
                $query->where('issue_times.title', 'شروع به همکاری');
            })
            ->with('ounit')
            ->get();

        $ounits->each(function ($script) {
            $script->ounit->load(['descendants' => function ($query) {
                $query->where('unitable_type', VillageOfc::class)
                    ->with('ancestors');
            }]);
        });`

**Comment by staudenmeir** [comment]
Hi @ali-ghanati,
Please share the whole error with its stacktrace.
