### ISSUE TITLE
[Feature request] Recursive relationships defined in related table

### ISSUE THREAD

**Issue by ipimpat** [staudenmeir/laravel-adjacency-list#26]
It would be super awesome if the recursive relationships could be defined in a related table, so a model could have multiple parents.

the nodes table:

```
+-------+------------------+------+-----+---------+----------------+
| Field | Type             | Null | Key | Default | Extra          |
+-------+------------------+------+-----+---------+----------------+
| id    | int(11) unsigned | NO   | PRI | NULL    | auto_increment |
| name  | varchar(100)     | NO   |     | NULL    |                |
+-------+------------------+------+-----+---------+----------------+
```

parent/child relationship table:

```
+-----------+------------------+------+-----+---------+-------+
| Field     | Type             | Null | Key | Default | Extra |
+-----------+------------------+------+-----+---------+-------+
| id        | int(11)          | NO   |     | NULL    |       |
| parent_id | int(11) unsigned | NO   | MUL | NULL    |       |
| child_id  | int(11) unsigned | NO   |     | NULL    |       |
+-----------+------------------+------+-----+---------+-------+
```

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by jonagoldman** [comment]
Arrived here searching for an implementation of the 'Closure Table' pattern.
The table structure is similar, just without the 'parent_id' column. All relations are handled in the relations table, so the nodes are not mixed with the relations (or edges). This also allows for multiple parents.

The original implementation of the Closure Table pattern involves storing all possible paths, not just those with a direct parent-child relationship, but using CTE you can avoid this just store direct relations.

Here is an example of how to avoid storing all paths: https://dwbi1.wordpress.com/2017/10/18/hierarchy-with-multiple-parents/

**Comment by staudenmeir** [comment]
Thanks, I'll take a look.

**Comment by staudenmeir** [comment]
Can you both share details about your use cases (e.g. migrations)?

**Comment by jonagoldman** [comment]
A good example is a product catalog where a product can also be a bundle or contain other products:

- Bar
  - Drinks
    - Tonic Water
    - Orange Juice
    - Gin
    - Bitter Blossom
      - Tonic Water
      - Orange Juice
      - Gin

Bar and Drinks are categories. All drinks can be bought individually, also the Bitter Blossom recipe contains multiple drinks.

Assuming MySQL is used, this can be represented like this:

```sql
create table products
(
    id      int        not null,
    name    varchar    not null,
    primary key (id)
);

create table product_hierarchy
(
    id           int    not null,
    source_id    int    null,
    target_id    int    not null,
    primary key (id),
    constraint foreign key (source_id) references products (id),
    constraint foreign key (target_id) references products (id)
);
```

Data:
```sql
insert into products (name) values
('Bar'), ('Drinks'), ('Tonic Water'), ('Orange Juice'), ('Gin'), ('Bitter Blossom');

insert into product_hierarchy (source_id, target_id) values
(null, 1), (1, 2), (2, 3), (2, 4), (2, 5), (2, 6), (6, 3), (6, 3), (6, 5);
```

An adjacency list with a parent_id column can be generated with a join and union:
```sql
select p.id, h.source_id as parent_id
    from products p
    join product_hierarchy h on p.id = h.source_id
    where h.source_id is null
union
select p.id, h.source_id as parent_id
    from products p
    join product_hierarchy h on p.id = h.target_id;
```

You could also generate the path and depth like this:
```sql
with recursive
t1 (source_id, target_id, path) as (
    select source_id, target_id, json_array(target_id) as path
        from product_hierarchy
        where source_id is null
    union all
    select t.target_id, h.target_id, json_array_append(path, '$', h.target_id)
        from product_hierarchy h
        join t1 t on h.source_id = t.target_id
)
select *, json_length(t1.path) as depth
from t1;
```

This structure is not really a tree, is more like a graph. In this case is useful not only for normalization, but for other business requirements like tracking inventory.
For example if a Bitter Blossom is bought, the inventory for Tonic Water, Orange Juice and Gin is reduced. Also if any of those is not in stock, then Bitter Blossom is not in stock. Of course that logic is outside of the scope of the example.

**Comment by ipimpat** [comment]
My table structure is very similar to @jonagoldman's example.

I think this is also called Bill of materials: https://www.vertabelo.com/blog/identifying-the-bill-of-materials-bom-structure-in-databases/ ?

I use it to store food recipes / ingredients and then estimate the weight of "raw"/"base" ingredients in the recipe.

Take for instance a ham sandwich, which consists of some ham meat, two slices of bread etc..  

I also store the the weight of each "ingredient" needed to make the this sandwich, all the way down to it's "raw"/"base ingredient, like raw meat, flour and water in the bread.

The weight is stored in the with the parent/child ids (@jonagoldman's hierarchy table)  along with other information. e.g. how the ingredient is prepared (baked, boiled, fried etc..).

- A tasty Ham Sandwich
  - Slice of ham (25g)
    - Ham (1kg)
      - Raw meat (1kg)
  - Slice of bread (25g)
    - Bread Loaf (1kg)
      - Yeast (10g)
      - Flour (1kg)
      - Water (1kg)
      - ... etc
  - Slice of bread (25g)
    - Bread Loaf (1kg)
      - Yeast (10g)
      - Flour (1kg)
      - Water (1kg)
      - ... etc
  - Other stuff you like in your sandwich (+25g)

Then I can estimate how much of the "raw"/"base" ingredients, like raw meat, yeast, flour, water (the leafs nodes) there is in 100g of "A tasty Ham Sandwich"

**Comment by jonagoldman** [comment]
Exactly the same thing @ipimpat! I store the capacity of each bottle in millilitres and the amount required for each drink. Then I calculate the total amount used for each product and divide that by the capacity of the bottle so I know how many bottles where used in total, and how many I have left in stock.

**Comment by toyi** [comment]
I need this as well, it would be awesome. I currently also have recursive relationships where the children can have multiple parents. Any chance of seeing an update on this issue in a more or less near future ? Anyway, great package 👍

**Comment by staudenmeir** [comment]
@toyi Can you also provide your migrations?

**Comment by toyi** [comment]
Of course

```php
Schema::create('products', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    // some other columns...
});

Schema::create('product_bundles', function (Blueprint $table) {
    $table->unsignedBigInteger('parent_id')->index();
    $table->unsignedBigInteger('child_id')->index();
    $table->primary(['parent_id', 'child_id']);
            
    $table->foreign('parent_id')->references('id')->on('products')->onDelete('cascade');
    $table->foreign('child_id')->references('id')->on('products')->onDelete('cascade');
});
```

In Laravel terms, it's the same as a parent retrieved via a `belongsTo` / children with `hasMany`... but with a `belongsToMany` for both.

The idea is that some products can act as a parent for some other products (these products are some kind of bundles).
It's just like the food examples given earlier but applied on products.

Let's take a simple example with a videogames bundle.

* Mario bundle is parent of Mario Kart
* Mario Kart is also sold within the Racing bundle
* The Switch can be sold with both Mario Kart and Zelda... which can be in an Adventure Bundle.

In this configuration, Mario Kart has 3 parents (Mario bundle, Racing bundle and the Switch), Zelda has two parents... I'll not go further but Zelda could be parent of some accessories and so on...

To be honest I did some cleaning and my use case is not about videogames, but it is about products and bundles used in that way.

Since a bundle is a product, with it's own reference, price, pictures, description... it totally made sense (not to mention that the code base was designed to order products only, so using this architecture permitted to avoid massive changes) but it adds the complexity of handling multiple parents and children. Not impossible - it works fine - but it could clearly be more performant and cleaner.

I think this, combined with an other issue of retrieving a nested list in a similar fashion that nesting a relation with `with` does (https://github.com/staudenmeir/laravel-adjacency-list/issues/33#issuecomment-633074081), could make this package a real gem (I'm joking, it already is, but it could be a bigger and brigther gem 🥇 ).

**Comment by staudenmeir** [comment]
Thanks, I'll look into it.

**Comment by vlados** [comment]
Any updates?

**Comment by staudenmeir** [comment]
This is a huge feature and I've been working on it for months, but it will still take some time.

**Comment by coclav** [comment]
Adding my use case to this list, our migration would look like the first message in the thread.

```
Schema::create('boxes', function (Blueprint $table) {
    $table->bigIncrements('id');
    // some other columns... such as
    $table->text('type');
});
Schema::create('lines', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->foreignId('source_id')->constrained('boxes');
    $table->foreignId('target_id')->constrained('boxes');
    // possibly some additional properties for the pivot in the future
});
```

Our use case is a diagraming / process mapping tool where we traverse a graph to run analytics. This is directed graph, and the capability that this traversal algorithm brings is the ability to understand the relationship between a starting point the result. In the current implementation we have "ancestors" and "descendants" and "depth". This is the difference with a traditional query that would output the result, but without context of the position within a graph.

* Traverse the graph to find the next/previous box of type X
* Traverse the graph find all upstream / downstream boxes of type X (or limit by a given "depth" to only find the X next/previous)

Just that feature would be amazing on its own.

Now, (as i'm here to share my use cases), still our process flow. Boxes represent "activities" and they have many "roles" and many "systems. It's a process flow in the sense that there is a start and and end to the process, it is a directed graph.  

One of our use case is to find the relationships between these artefacts.

* For a given `role` in a process, find all other `roles` used in the same graph. This query starts from the `role`, finds its `boxes`, traverses the graphs up, and down to collect all the other `roles` involved upstream and downstream and how "remote" (the depth) they are from the starting point. We can they find out "in this process ROLE_A will receive work done by LIST_OF_UPSTREAM_ROLES and ROLE_A work will impact LIST_OF_DOWNSTREAM_ROLES

* For a given `role`, find all `systems` used in the same process, again, doing that with a graph allows us to find if systems  upstream or downstream. Again, the analytics insights are amazing in terms of understanding the impact of change of a system on a process and its role.

If all that was possible, we are approaching the use case of "native" graph databases (arango, neo4j) !

**Comment by staudenmeir** [comment]
> One of our use case is to find the relationships between these artefacts.
> For a given role in a process...
> For a given role, find all systems used in the same process...

@coclav Can you share some sample data (as Laravel code or a database dump) for these use cases and examples of expected query results?

**Comment by staudenmeir** [comment]
I released `v1.11` with support for graphs relationship (Laravel 9). Please test it and see what features/helpers are missing for your use cases.

**Comment by staudenmeir** [comment]
@ipimpat 

```php
class Recipe extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasGraphRelationships;

    public function getPivotTableName(): string
    {
        return 'recipe_ingredients';
    }

    public function getParentKeyName(): string
    {
        return 'recipe_id';
    }
  
    public function getChildKeyName(): string
    {
        return 'ingredient_id';
    }

    public function getPivotColumns(): array
    {
        return ['brutto', 'netto'];
    }
}
```

In your case, `descendants` are the recursive ingredients.

**Comment by staudenmeir** [comment]
@jonagoldman 

```php
class Product extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasGraphRelationships;

    public function getPivotTableName(): string
    {
        return 'product_hierarchy';
    }

    public function getParentKeyName(): string
    {
        return 'source_id';
    }
  
    public function getChildKeyName(): string
    {
        return 'target_id';
    }
}
```

**Comment by staudenmeir** [comment]
@toyi 

```php
class Product extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasGraphRelationships;

    public function getPivotTableName(): string
    {
        return 'product_bundles';
    }
}
```

**Comment by staudenmeir** [comment]
@coclav 

```php
class Box extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasGraphRelationships;

    public function getPivotTableName(): string
    {
        return 'lines';
    }

    public function getParentKeyName(): string
    {
        return 'source_id';
    }
  
    public function getChildKeyName(): string
    {
        return 'target_id';
    }
}
```

**Comment by toyi** [comment]
@staudenmeir Thanks, nice feature. It could take some time but I'll surely test this.

**Comment by coclav-skore** [comment]
This bring the package to another level. Can't wait to try it out ! thanks @staudenmeir

**Comment by ipimpat** [comment]
@staudenmeir thank you very much, I can't wait to try it out.

**Comment by daninfocus** [comment]
Hi, you have put in the readme:
> You can also use the package to traverse graphs with multiple parents per node that are defined in a pivot table. Use cases might be a bill of materials (BOM) or a **family tree**.
Does this apply for a family tree with mother_id and father_id, instead of just a parent_id? In a pivot table for example.
