### ISSUE TITLE
n+1 queries 

### ISSUE THREAD

**Issue by quality-center-lk** [staudenmeir/laravel-adjacency-list#261]
Here i am Facing n+1 queries issue 
 
 ``public` function groupHierarchyItems(Request $request) 
    {
        try {  
            $uuid = $request->uuid;
            $group = Group::where('uuid', $uuid)->first();

            $ancestors = $group->rootAncestor()->with('children')->get();

            $groupService = new GroupService;
            $formattedAncestors = $groupService->formatgroups($ancestors, $group->id);

            return response(['status' => true, 'data' => $formattedAncestors], 200);

        } catch (Exception $e) {
            Log::channel('database')->error($e->getMessage());

            return response(['status' => false, 'message' => __('something_went_wrong')], 400);
        }
    }
    
    
     public function formatgroups($ancestors, $own = null)
    {
        $formattedAncestors = [];

        foreach ($ancestors as $ancestor) {
            $formattedAncestor = [
                'id' => $ancestor->id,
                'title' => $ancestor->title,
                'isDisabled' => $ancestor->id == $own,
                'isDefaultExpanded' => $ancestor->id == $own,
            ];
        
            if ($ancestor->children->count() > 0) {
                $formattedAncestor['children'] = $this->formatgroups($ancestor->children, $own);
            }
        
            $formattedAncestors[] = $formattedAncestor;
        }
        
        return $formattedAncestors;
    }``

**Comment by quality-center-lk** [comment]
SELECT * FROM `groups` WHERE `groups`.`parent_id` = 6 and `groups`.`parent_id` IS not NULL and `groups`.`deleted_at` IS NULL

this querie running n+1 time

**Comment by staudenmeir** [comment]
Hi @quality-center-lk,

> SELECT * FROM groups WHERE groups.parent_id = 6 and groups.parent_id IS not NULL and groups.deleted_at IS NULL
> this querie running n+1 time

From which line of your code does this query come from?

**Comment by quality-center-lk** [comment]
from 

$formattedAncestor['children'] = $this->formatgroups($ancestor->children, $own);

**Comment by quality-center-lk** [comment]
i have fixed with bloodline thanks for response

**Comment by longkhan786** [comment]
How did you fix it? Can I see your code?

**Comment by quality-center-lk** [comment]
Sure! 

$group->bloodline()->get()->toTree();

**Comment by longkhan786** [comment]
ok Thanks
