### ISSUE TITLE
Find products in categories

### ISSUE THREAD

**Issue by CrazyTapok-bit** [staudenmeir/laravel-adjacency-list#274]
We have the following plates:

**```products```**
```
id | name |
---+------+
```

**```categories```**
```
id | name | parent_id |
---+------+-----------+
```

**```product_categories```**
```
id | product_id | category_id |
---+-----------+-------------+
```

`category_id` - contains a link to the categories table but can contain any id from this tree.

The question arises, how to find all products belonging to certain categories? Of course, taking into account that category_id can point to some final category as well as to the parent, that is, it will have an indirect connection with child subcategories. But during the search, we can specify a list of any ids to search, and if one of them is a parent, then all its child categories should be considered during the search

Thanks

**Comment by staudenmeir** [comment]
Hi @CrazyTapok-bit,
You can fetch the recursive products of a category with a deep relationship: 
https://github.com/staudenmeir/laravel-adjacency-list?tab=readme-ov-file#deep-relationship-concatenation

```php
class Category extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function recursiveProducts(): \Staudenmeir\EloquentHasManyDeep\HasManyDeep
    {
        return $this->hasManyDeepFromRelations(
            $this->descendantsAndSelf(),
            (new static)->products()
        );
    }
    
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

$categories = Category::with('recursiveProducts')->findMany($ids);

foreach ($categories as $category) {
    dump($category->recursiveProducts);
}
```

Is that what you are looking for?

**Comment by CrazyTapok-bit** [comment]
Greetings. Thanks for the answer

You get the categories you want and all the products in them, but I'm looking for something a little different. I need to get all products that belong to certain categories. It may sound similar, but it has a completely different meaning.

Example:
```php

use Illuminate\Database\Eloquent\Model;
use Staudenmeir\EloquentHasManyDeep\HasRelationships;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class Category extends Model
{
    use HasRelationships;
    use HasRecursiveRelationships;
}
```

```php

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Product extends Model
{
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(
            Category::class,
            'product_categories',
            'product_id',
            'category_id',
        );
    }
}
```

If I didn't use depth, my implementation would look like this:
```php
$ids = [220, 346];

Product::query()->whereHas('categories', function(Builder $builder) use($ids) {
    $builder->whereIn('category_id', $ids);
})->get();
```

However, how to get all products that have categories 220 and 346 including their child categories in the entire depth?

**Comment by staudenmeir** [comment]
It's not the most efficient approach, but you can extend this query (not supported by MariaDB):

```php
Product::query()->whereHas('categories.ancestorsAndSelf', function(Builder $builder) use($ids) {
    $builder->whereIn('id', $ids);
})->get();
```

**Comment by CrazyTapok-bit** [comment]
> It's not the most efficient approach

Hi @staudenmeir! Thanks for the answer. I don't know why this is not the most efficient solution, because it is a very useful feature and it helps a lot when working with filters. I hope that it will develop and work stably on large volumes of data. Thanks again

**Comment by staudenmeir** [comment]
Queries with `whereHas()` use subqueries are typically slower for large datasets than queries with `JOIN` clauses.

The query I suggested in https://github.com/staudenmeir/laravel-adjacency-list/issues/274#issuecomment-2495560534 uses `JOIN` clauses. If you merge all the values of `$category->recursiveProducts` into a single collection, you get the same result as with the second query.
