### ISSUE TITLE
[Error] Recursive queries when using "Eager Loading By Default"

### ISSUE THREAD

**Issue by lopezdonaque** [staudenmeir/laravel-adjacency-list#28]
Version: 1.3
Laravel version: 6.x
Expected: Only one CTE query is executed

When using a default relation it causes that more than one query is executed.

```
    /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = ['author'];
```

**Comment by staudenmeir** [comment]
What are the executed queries?

**Comment by lopezdonaque** [comment]
I have the table "location" with a "parent_id".
When I find a single location with "ancestors" as default eager loading it executes the next queries:

`Location::query()->find(1812)`

![error_locations](https://user-images.githubusercontent.com/735972/78578486-e476ac00-782f-11ea-95a7-c24fc43f60fb.png)

**Comment by staudenmeir** [comment]
Please post the whole `Location` model.

**Comment by lopezdonaque** [comment]
I have only a Location model. 
The author is just the example from Laravel documentation.

```
CREATE TABLE `location` (
  `location_id` int(11) unsigned NOT NULL,
  `parent_id` int(11) unsigned DEFAULT NULL,
  `name` varchar(255) NOT NULL
)
```

```
<?php
use Illuminate\Database\Eloquent\Model;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class LocationTest extends Model
{
    use HasRecursiveRelationships;
    protected $table = 'location';
    protected $primaryKey = 'location_id';
    protected $with = [
      'ancestors',
    ];
}

```

**Comment by staudenmeir** [comment]
This is the correct behavior: When you load the ancestors of location `1812`, `$with` is applied to every one of them and all _their_ ancestors are loaded. This continues recursively until there are no more ancestors to load.

In general, I advise against using `$with`. I would add eager loading to the query:

```php
$location = Location::with('ancestors')->find(1812);
```

**Comment by lopezdonaque** [comment]
Then, in general, it's not the same to use eager loading in the query builder and in the default section of the model?
I think it should be the same.

**Comment by staudenmeir** [comment]
In a "normal" case (like the example from the documentation), they basically behave the same way.

What makes your situation special, is the fact that the related model is the same as the parent model. I would say that `$with` is more or less unusable for recursive relationships.

**Comment by lopezdonaque** [comment]
Understood.
You could close the issue.
Thanks and nice work with this and your other repositories!

**Comment by staudenmeir** [comment]
Thanks!
