### ISSUE TITLE
Control maximum depth inside the recursive query

### ISSUE THREAD

**Issue by nonovd** [staudenmeir/laravel-adjacency-list#29]
## Problem

When limiting the depth with `whereDepth()`, the CTE will still first build the entire tree which can lead to a big performance hit.

## Thoughts

I feel it would be better to be able to break out of the recursive query.

It can be done by moving the where clause into the recursive query:

```sql
union all (
   select ...
   inner join "laravel_cte" on "laravel_cte"."id" = "nodes"."parent_id"1
   where "depth" + 1 < MAX_DEPTH
)
```

We would have to change the api, for example:

```php
public function scopeTree(Builder $query, int $maxDepth=null)
```

## Perspective

More generally, I think we should be able to manipulate both the initialQuery and the recursiveQuery so we can apply conditions on them and limit performance issues.

**Comment by staudenmeir** [comment]
Thanks, I'll look into it.

**Comment by patrickomeara** [comment]
I agree, it would be nice to manipulate the queries, adding joins would be beneficial in our app.

I would consider this feature a more advanced use case though. The out of the box simplicity of this package is still important.

**Comment by staudenmeir** [comment]
> adding joins would be beneficial in our app.

@patrickomeara Could you provide details about your use case?

**Comment by patrickomeara** [comment]
You can ignore my comment @staudenmeir 

We went back to the drawing board with our issue and came up with a more performant way to get the data we needed.

**Comment by nonovd** [comment]
Let's say we have a Comment model where every comment can reply to any other comment and we want to build the comments tree, 

Well easy, we can just:

```php
Comment::query()
    ->tree()
    ->get();
```

Now let's assume we have a 20-level deep tree, but I just want the first 2 levels:

```php
Comment::query()
    ->tree()
    ->whereDepth('<', 2)
    ->get()
````

It works but SQL is building the entire 20-level deep tree anyway (see first message).

Now a real-life use case would be to get the comments tree only for a certain post:

```php
$post->comments()
    ->tree()
    ->whereDepth('<', 2)
    ->get()
````
This doesn't work so as a workaround, we can:

```php
Comment::query()
    ->where('commentable_id', $post->id)
    ->where('commentable_type', $post->getMorphClass())
    ->tree()
    ->whereDepth('<', 2)
    ->get()
````

I put the where clauses before the tree method on purpose, this is misleading because the conditions only apply at the very last.

If I have 150,000 comments, I'm building a tree with 150,000 nodes on 20 levels, only to maybe display 10 comments on 2 levels for this $post.

Now maybe we have a reaction system which allows to like and dislike comments, and we'd like to get the count for every comments:

```php
Comment::query()
    ->where('commentable_id', $post->id)
    ->where('commentable_type', $post->getMorphClass())
    ->tree()
    ->whereDepth('<', 2)
    ->joinReactionCounterOfType('Like')
    ->joinReactionCounterOfType('Dislike')
    ->get()
```

You can see where this is going. I think we need to be able to manipulate at least the initialQuery so we can have the appropriate subset and build the tree from it.

**Comment by staudenmeir** [comment]
@nonovd There is a workaround for queries like this and I'm working on a better solution:
https://github.com/staudenmeir/laravel-adjacency-list/issues/8#issuecomment-552595588

**Comment by staudenmeir** [comment]
My current plan is a `subtree()` scope that allows users to provide their own constraints for the initial query. The scope could also support relationships and build the initial constraint from it:

```php
Comment::subtree(
        $post->comments()
    )
    ->whereDepth('<', 2)
    ->get();
```

`$post->comments()->tree()` would be nicer, but I don't see a good way to implement that.

**Comment by staudenmeir** [comment]
@nonovd Regarding your example with posts and comments: You have a similar use case in your application, right? Could you share details?

**Comment by staudenmeir** [comment]
The latest release adds a `treeOf()` scope and a parameter for limiting the maximum depth:

```php
$constraint = function ($query) use ($post) {
    $query->where('commentable_id', $post->id)
        ->where('commentable_type', $post->getMorphClass())
};

$comments = Comment::treeOf($constraint, $maxDepth)->get();

```
