### ISSUE TITLE
ErrorException (E_ERROR): "'concat' is not a recognized built-in function name."

### ISSUE THREAD

**Issue by ferox** [staudenmeir/laravel-adjacency-list#30]
**SGBD: SQL Server 2008r2**

* ErrorException (E_ERROR): "SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'concat' is not a recognized built-in function name."

**Comment by staudenmeir** [comment]
Can you please test this fix before I release it? I don't have an SQL Server 2008 installation.

Replace `compileRecursivePath()` in `vendor/staudenmeir/laravel-adjacency-list/src/Query/Grammars/SqlServerGrammar.php` with this:

```php
public function compileRecursivePath($column, $alias, $separator)
{
    $alias = $this->wrap($alias);

    return "cast($alias + '$separator' + cast(".$this->wrap($column)." as varchar) as varchar) as $alias";
}
```

**Comment by ferox** [comment]
Yeah, it works like a charm!!!!

Thanks.

**Comment by staudenmeir** [comment]
Thanks, I've released a new version.
