### ISSUE TITLE
Conflict with illuminate/database dependency

### ISSUE THREAD

**Issue by ferox** [staudenmeir/laravel-adjacency-list#31]
Laravel Framework v5.8.30.

I can't install 1.3.1 version it requires **illuminate/database ^6.0**.

See - **staudenmeir/laravel-adjacency-list v1.3.1** requires illuminate/database ^6.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].

I can only install the version 1.1.4

**Comment by staudenmeir** [comment]
Yes, every package version only works with a specific Laravel version.

With the installation command from the [README](https://github.com/staudenmeir/laravel-adjacency-list#installation), you always get the correct version:

```
composer require staudenmeir/laravel-adjacency-list:"^1.0"
```

Or do you explicitly need `v1.3.1`?

**Comment by ferox** [comment]
Well, the 1.3.1 version is the one that you add Support for SQL Server 2008r2.

Updating the composer,json file with the correct version (1.3.1) and then running composer update I got this error requiring illuminate/database ^6.0.

Can you update de version 1.1.4 with the support of SQL Server 2008r2?

**Comment by staudenmeir** [comment]
I've backported the fix and released `v1.1.5`.

**Comment by ferox** [comment]
Thanks man!!!

**Comment by ferox** [comment]
It works!
