### ISSUE TITLE
Multiple lists within one table

### ISSUE THREAD

**Issue by es-ka** [staudenmeir/laravel-adjacency-list#32]
Is it possible to handle more than one list within one database table? There's an extra column `list_id` indicating to which list each element belongs.

Getting descendants of a given element seems to work but getting the whole tree silently fails with an empty result.

**Comment by staudenmeir** [comment]
> getting the whole tree silently fails with an empty result.

Do you have root nodes with `parent_id = null`?

**Comment by es-ka** [comment]
> What does your query look like?
`Element::where('list_id', $id)->tree()->get()`
What should it look like?

> Do you have root nodes with `parent_id = null`?
My root nodes have `parent_id = 0`

**Comment by staudenmeir** [comment]
The `tree()` scope expects root nodes with `parent_id = null`.

You can get the tree like this:

```php
$constraint = function (Builder $query) use ($id) {
    $query->where('parent_id', 0)->where('list_id', $id);
};

$tree = Element::withRelationshipExpression('desc', $constraint, 0)->get();
```

This scope is only used internally, but I'm already working on a public version.

**Comment by es-ka** [comment]
That throws a type error:

`Argument 1 passed to App\Http\Controllers\ElementsController::App\Http\Controllers\{closure}() must be an instance of App\Http\Controllers\Builder, instance of Staudenmeir\LaravelAdjacencyList\Eloquent\Builder given, called in /MY_PATH/vendor/staudenmeir/laravel-adjacency-list/src/Eloquent/HasRecursiveRelationshipScopes.php on line 171`

Did I miss something?

**Comment by staudenmeir** [comment]
You need to import the `Builder` class at the top of the file (or remove the type hint):

```php
use Illuminate\Database\Eloquent\Builder;
```

**Comment by staudenmeir** [comment]
The latest release adds the `treeOf()` scope for custom constraints:

```php
$constraint = function (Builder $query) use ($id) {
    $query->where('parent_id', 0)->where('list_id', $id);
};

$tree = Element::treeOf($constraint)->get();
```

**Comment by es-ka** [comment]
That's great news. It works like a charm.
Thanks a lot!

**Comment by soundar8562** [comment]
HI, this is fine but what if I have multiple parent IDs at **different depths**? Like you said we have the parent id value Null but i have without null values too so is there any possibility to do?

**Comment by staudenmeir** [comment]
@soundar8562 Can you provide an example?

**Comment by soundar8562** [comment]
Below, tried before seeing this issue,

$demo_parent_id=[1,4,8,20]; // these IDs came from different depths
foreach($demo_parent_id as $key => $value){
                $demo_array[$key] = Demo::find($value['id'])
                    ->descendants()
                    ->whereDepth($result['depth'])
                    ->get();
            }

The code above works well for me, and we can use findMany also, that's not a matter, only thing is it takes more loading time,
So I tried to use this,

$constraint = function (Builder $query) use ($demo_parent_id) {
    $query->where('parent_id', 1)->where('id', $demo_parent_id);
};
$tree = Element::treeOf($constraint)->get();

It works only to the mentioned parent_id on the code **$query->where('parent_id', 1)**  but I have dynamic parent Ids
like, $demo_array[$key] = Demo::find(**$value['id']**)

---------------------------------------------------------------------------------
**Another query,** no matter if the above working or not,
I have a bunch of parent_ids, so how do I find their last level?
$demo_parent_id=[1,4,8,20];  // these IDs came from different depths

Thanks for your quick reply.
