### ISSUE TITLE
Is there a way to generate a nested list?

### ISSUE THREAD

**Issue by Rotario** [staudenmeir/laravel-adjacency-list#33]
Hi,
I love the library, just a quick question. Is there a way to generate a nested list for a given root ID please?
I've got a table like
Site table
id   |   name   | is_site_to

and getParentKeyName() to return is_site to, so that all works

But when I call

Site::find(1)->descendants->get()

Then I get a flat list of sites and their descendants, is there any way to make this nested please?

**Comment by staudenmeir** [comment]
It's not possible yet, but the feature is on my TODO list.

**Comment by Rotario** [comment]
Ah Thanks! I thought it worked, somehow I did it but I forgot. I will have to do it in javascript then.

**Comment by staudenmeir** [comment]
You can also get nested lists with recursive `HasMany` relationships:

```php
class Site extends Model
{
    public function children()
    {
        return $this->hasMany(self::class, 'is_site_to')->with('children');
    }
}

Site::find(1)->childrenRecursive;
```

Unlike the package, this solution executes multiple separate queries (depending on the tree's size).

**Comment by Rotario** [comment]
Yeah I was trying to do it in my API ResourceCollection, but that does some weird things with objects and arrays so I'm just doing it in the Controller

**Comment by iraklisg** [comment]
> It's not possible yet, but the feature is on my TODO list.

@staudenmeir I am really looking forward to this feature!

An option for getting the tree in the following format would be rather useful as It would facilitate the usage of popular frontend solutions for displaying hierarchical data like [Vuetify's TreeView component](https://vuetifyjs.com/en/components/treeview/) and [ElementUI's Tree component](https://element.eleme.io/#/en-US/component/tree) (_oh yes I :heart: Vue_)

```php
[
    [
        'id' => 1,
        'name' => 'Level 0-a',
        'children' => [
            [
                'id' => 3,
                'name' => 'Level 1-a',
                'children' => [
                    [
                        'id' => 5,
                        'name' => 'Level 2-a',
                        'children' => [...]
                    ],
                    ...
                ]
            ],
            [
                'id' => 4,
                'name' => 'Level 1-b',
                'children' => [
                    [
                        'id' => 1,
                        'name' => 'Level 2-a',
                        'children' => [...]
                    ]
                ],
            ],
            ...
        ]
    ],
    [
        'id' => 2,
        'name' => 'Level 0-b',
        'children' => [...]
    ],
    ...
];
```

For the time being I am relying on recursively parsing the data of database table on php (similarly to what @Rotario has proposed)

Thank you for your hard work on implementing this useful package

**Comment by andrew-connell** [comment]
For my use case it was more suitable to nest the items client side. It's actually very easy but it took me longer than I'd like to admit.
To save anyone else the hassle of coming up with it, here's the code

```
makeTree(items) {
      var map=new Map(),result = []
      for (var item of items) {
        var parent=item.parent_id?map.get(item.parent_id):result
        var itemCopy = Object.assign({children:[]}, item)
        parent.push(itemCopy)
        map.set(item.id,itemCopy.children)
      }
      return result
}
```

**Comment by GTCrais** [comment]
+1 for this feature request

**Comment by staudenmeir** [comment]
The latest release adds the ​`toTree()` method:

```php
$tree = Site::find(1)->descendants->get()->toTree();
```
