### ISSUE TITLE
Trouble overriding the parent key name on runtime

### ISSUE THREAD

**Issue by hfalucas** [staudenmeir/laravel-adjacency-list#36]
Hey there,

I've been trying with no success to understand what I'm doing wrong while overriding the 'parent key name' dynamically. For the sake of example lets say I have a 'Post' model with these fields `parent_id` and `original_post_id`. 
When I need to get the ancestors or children related with parent_id everything works fine, but when using the original_post_id everything breaks up.

```
// Post Model
class Post extends Model
{
    use HasRecursiveRelationships;

    protected $parentKey;

    public function getParentKeyName()
    {
        return $this->parentKey;
    }

    public function setParentKeyName($parentKey)
    {
        $this->parentKey = $parentKey;

        return $this;
    }
}

// usage
$posts = (new Post)->setParentKeyName('original_post_id')->with(['ancestors', 'some_other_suff'])->get();
```

I get the following error:
```
SQLSTATE[42601]: Syntax error: 7 ERROR: zero-length delimited identifier at or near """" LINE 1: ...posts" inner join "laravel_cte" on "laravel_cte"."" = "pos... ^ (SQL: with recursive "laravel_cte" as ((select *, -1 as "depth", array[("id" || '')::varchar] as "path" from "posts" where "posts"."id" in (680e8948-3932-4a31-86ba-a80914cbb9ae, b405eaa0-dd78-4bf7-bc50-3c0135e97307, f74c2829-f4d6-45ef-ab91-ab10804e1ce6)) union all (select "posts".*, "depth" - 1 as "depth"..., 
```
The strange thing is if the `getParentKeyName` method is hard coded to return 'original_post_id' it works fine.

Is it what I'm trying to do kinda stupid as in doesn't make sense or  impossible 😅 ?

Thank you in advance.

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by hfalucas** [comment]
Hey there again @staudenmeir after some more digging, seems like instantiating the model and then overriding the 
`getParentKeyName` doesn't take effect, the output of the method below is `posts.` and `getParentKeyName` is null.
```
    public function getQualifiedParentKeyName()
    {
        return (new static)->getTable() . '.' . $this->getParentKeyName();
    }
```

So the work around I found was overriding the `getParentKeyName` on the model by returning a value from a config file:
```
    // Post model
    public function getParentKeyName()
    {
        // Is set by default to 'parent_id'
        return config('app.adjacency-list.parent_key_name');
    }
    
   // Usage
   config(['app.adjacency-list.parent_key_name' => 'original_post_id']);
   $posts = Post::with(['ancestors', 'some_other_suff'])->get();
```
The above seems to work just fine. Dunno if this is relevant information, but just in case decided to drop it here :)

**Comment by staudenmeir** [comment]
You could so make `$parentKey` and `setParentKeyName()` `static`:

```php
class Post extends Model
{
    use HasRecursiveRelationships;

    protected static $parentKey;

    public function getParentKeyName()
    {
        return static::$parentKey;
    }

    public static function setParentKeyName($parentKey)
    {
        static::$parentKey = $parentKey;

        return new static;
    }
}

$posts = Post::setParentKeyName('original_post_id')->with(['ancestors', 'some_other_suff'])->get();
```

**Comment by hfalucas** [comment]
The only modification I did was setting `parent_id` to be the default value of `$parentKey` since I only need to override it in very few places of my app and when running my entire test suit seems like when the value is overridden it persists to rest of the tests, for example:

```php
     /** @test */
    public function test_one()
    {
         $post = factory(Post::class)->create();
         Post::setParentKeyName('original_post_id')->get()
         (...)
    }

     /** @test */
    public function test_two()
    {
         $post = factory(Post::class)->create();
         $post->getParentKeyName(); // outputs: 'original_post_id' instead of 'parent_id'
         (...)
    }
```
Note: I'm not overriding the key in the test, it was just for the sake of the example
