### ISSUE TITLE
Find depth by passing ID

### ISSUE THREAD

**Issue by soundar8562** [staudenmeir/laravel-adjacency-list#37]
Hi there, hope you are fine!
We are trying to find the depth by passing the id as below,

```
$id= 9;
$x= MissionTerritory::where('id', $id)->tree()->depthFirst()->first();
dd($x->depth);
```

The above method we can get the depth(loading time seems a little high) but is there any other better way?

**Comment by staudenmeir** [comment]
You can determine a node's depth from its root ancestor:

```php
$missionTerritory = MissionTerritory::find($id);

$depth = abs($missionTerritory->rootAncestor->depth);
```

**Comment by soundar8562** [comment]
Hi, this is fine, but what would you recommend when using multiple IDs to find depth?

$id=[1,2,3,4,5]
foreach($id as $value){
 $missionTerritory = MissionTerritory::find($value]);
}


As you suggested above, we can use the loop to get depth for multiple IDs, is there any other better solution?

**Comment by soundar8562** [comment]
Hi, this is fine, but what would you recommend when using multiple IDs to find depth?
As you suggested above, we can use the loop to get depth for multiple IDs, is there any other better solution?
Ex,
```
$id=[3,8];
foreach($id as $value){
    $query =MissionTerritory::find($value)->rootAncestor;
    $depth[]=abs($query->depth);
    $path[]=$query->path;
}
dd($depth,$path);
```
**Output**
**Depth**
array:2 [▼
  0 => 2
  1 => 2
]

**Path**
array:2 [▼
  0 => "2,1"
  1 => "7,1"
]

One more question, we need to split the path based on the depth level as following for the above output, Is there any way to do with the query itself?
array:2 [▼
  0 => "2,7"
  1 => "1"
]

**Note:** Right now we make use of for loop to get the above data format.

Thank you

**Comment by staudenmeir** [comment]
I would use the same approach and improve the performance with eager loading:

```php
$id=[3,8];
$missionTerritories = MissionTerritory::with('rootAncestor')->findMany($id);
foreach ($missionTerritories as $missionTerritory) {
    $query = $missionTerritory->rootAncestor;
    $depth[] = abs($query->depth);
    $path[] = $query->path;
}
```

I don't see a way to simplify this process.

**Comment by soundar8562** [comment]
Thanks man! Appreciate your help.
