### ISSUE TITLE
How to get total numbr of descendants ?

### ISSUE THREAD

**Issue by fullmad** [staudenmeir/laravel-adjacency-list#4]
Know we can get list of ancestors and descendants. But how to get counts of the total number of descendants or ancestors

**Comment by staudenmeir** [comment]
Use `count()`:

```php
$total = $model->descendants()->count();
```

**Comment by fullmad** [comment]
thanks a lot. However, if you mention this at readme file, it will be helpful for new developers like me. Anyway, very great script and helpful.

**Comment by staudenmeir** [comment]
I added an example to the README.
