### ISSUE TITLE
filter user descendants and show level/depth

### ISSUE THREAD

**Issue by whoami15** [staudenmeir/laravel-adjacency-list#41]
Laravel version: ^7.24
Package version: ~1.4
PHP version: 7.3

I need to get users where depth/level is `< 10` , and I want to filter or add a `where` condition on the `descendants`
which is `active = 1` and show their `depth/level` and `orderBy depth/level`

here is my query:
```php
$id = 1; // me
$users = User::find($id)->descendants()->whereDepth('<', 10)->get();
```

where I'm `user id 1`
```php
ID   |    Name   |     Parent ID    |   Depth/Level  
2        john            1                 1         
3        jane            2                 2             
```
Edit: I found out that adding `->depth` in the loop will show the `depth/level` now I only want to know how to add the `where` condition on the `descendants`

**Comment by staudenmeir** [comment]
Add the constraint to the query:

```php
$users = User::find($id)->descendants()->whereDepth('<', 10)->where('active', 1)->get();
```

**Comment by whoami15** [comment]
Thank you @staudenmeir , is it possible to group the depth/level?

**Comment by staudenmeir** [comment]
Do you mean something like `$users->groupBy('depth')`?

**Comment by whoami15** [comment]
yes @staudenmeir , and I wan to loop the depth to it will show like

```
Depth/Level 1
 - John

Depth/Level 2
 - Jane
```

**Comment by staudenmeir** [comment]
Have you tried looping over the result of `$users->groupBy('depth')`?

**Comment by whoami15** [comment]
I tried but it's showing  `Property [depth] does not exist on this collection instance.`

```
$users = User::find($id)->descendants()->whereDepth('<', 10)->where('active',1)->get();

@foreach($referrals->groupBy('depth') as $level)
        {{ $level->depth }}
@endforeach
```

**Comment by staudenmeir** [comment]
Take a look at `dd($users->groupBy('depth'));` and the [documentation](https://laravel.com/docs/8.x/collections#method-groupby).

**Comment by whoami15** [comment]
@staudenmeir  thank you.

**Comment by whoami15** [comment]
@staudenmeir  I solved it 👍 thank you. I will close this issue now.
