### ISSUE TITLE
Adding filter CTE

### ISSUE THREAD

**Issue by has5aan** [staudenmeir/laravel-adjacency-list#42]
Is there a possibility to add a filter to the cte block,
I have multiple hierarchies of companies, in a table contractor_hierarchy_relation with columns; 

- contractor_hierarchy_id
- contractor_id
- parent_contractor_id

**contractor_hierarchy_id** is a foreign key that I'd like to use in a where condition within the cte, while fetching the descendants and ascendants;
The query generated while fetching the descendants is;
`WITH RECURSIVE laravel_cte AS (
	(
		SELECT *,
			1 AS depth,
			cast(contractor_id AS char(65535)) AS path
		FROM contractor_hierarchy_relation
		WHERE contractor_hierarchy_relation.parent_contractor_id in (?)		
	)
	UNION ALL
	(
		SELECT contractor_hierarchy_relation.*,
			depth + 1 AS depth,
			concat(path, ?, contractor_hierarchy_relation.contractor_id)
		FROM contractor_hierarchy_relation
		INNER JOIN laravel_cte ON laravel_cte.contractor_id = contractor_hierarchy_relation.parent_contractor_id
	)
)
SELECT *
FROM laravel_cte

I'd like to add a filter for the contractor_hierarchy_id column in the cte as highlighted in the query below;
`WITH RECURSIVE laravel_cte AS (
	(
		SELECT *,
			1 AS depth,
			cast(contractor_id AS char(65535)) AS path
		FROM contractor_hierarchy_relation
		WHERE contractor_hierarchy_relation.parent_contractor_id in (?) AND 
                contractor_hierarchy_relation.contractor_hierarchy_id = (?)
	)
	UNION ALL
	(
		SELECT contractor_hierarchy_relation.*,
			depth + 1 AS depth,
			concat(path, ?, contractor_hierarchy_relation.contractor_id)
		FROM contractor_hierarchy_relation
		INNER JOIN laravel_cte ON laravel_cte.contractor_id = contractor_hierarchy_relation.parent_contractor_id
                AND contractor_hierarchy_relation.contractor_hierarchy_id = (?)
	)
)
SELECT *
FROM laravel_cte

Is there any provision to achieve this behavior?

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by has5aan** [comment]
Thanks a lot for your response.

To not get bogged down, my dirty workaround was to override these two functions within the model;

` 
 /**
     * Get the initial query for a relationship expression.
     *
     * @param ExpressionGrammar|Grammar $grammar
     * @param callable $constraint
     * @param int $initialDepth
     * @param string $from
     * @return Builder $query
     */
    public function getInitialQuery(ExpressionGrammar $grammar, callable $constraint, $initialDepth, $from)
    {
        $depth = $grammar->wrap($this->getDepthName());

        $initialPath = $grammar->compileInitialPath(
            $this->getLocalKeyName(),
            $this->getPathName()
        );

        $query = $this->newModelQuery()
            ->select('*')
            ->selectRaw($initialDepth . ' as ' . $depth)
            ->selectRaw($initialPath)
            ->from($from);

        foreach ($this->getCustomPaths() as $path) {
            $query->selectRaw(
                $grammar->compileInitialPath($path['column'], $path['name'])
            );
        }

        $constraint($query);

        $request = request()->all();

        if (!empty($request['contractor_hierarchy_id'])) {
            $query->where('contractor_hierarchy_relation.contractor_hierarchy_id', '=', $request['contractor_hierarchy_id']);
        }

        return $query;
    }

    /**
     * Get the recursive query for a relationship expression.
     *
     * @param ExpressionGrammar|Grammar $grammar
     * @param string $direction
     * @param string $from
     * @param int|null $maxDepth
     * @return Builder $query
     */
    public function getRecursiveQuery(ExpressionGrammar $grammar, $direction, $from, $maxDepth = null)
    {
        $name = $this->getExpressionName();

        $table = explode(' as ', $from)[1] ?? $from;

        $depth = $grammar->wrap($this->getDepthName());

        $recursiveDepth = $grammar->wrap($this->getDepthName()) . ' ' . ($direction === 'asc' ? '-' : '+') . ' 1';

        $recursivePath = $grammar->compileRecursivePath(
            $this->getQualifiedLocalKeyName(),
            $this->getPathName()
        );

        $recursivePathBindings = $grammar->getRecursivePathBindings($this->getPathSeparator());

        $query = $this->newModelQuery()
            ->select($table . '.*')
            ->selectRaw($recursiveDepth . ' as ' . $depth)
            ->selectRaw($recursivePath, $recursivePathBindings)
            ->from($from);

        foreach ($this->getCustomPaths() as $path) {
            $query->selectRaw(
                $grammar->compileRecursivePath(
                    $this->qualifyColumn($path['column']),
                    $path['name']
                ),
                $grammar->getRecursivePathBindings($path['separator'])
            );
        }

        if ($direction === 'asc') {
            $first = $this->getParentKeyName();
            $second = $this->getQualifiedLocalKeyName();
        } else {
            $first = $this->getLocalKeyName();
            $second = $this->qualifyColumn($this->getParentKeyName());
        }

        $query->join($name, function ($join) use ($name, $first, $second) {
            $request = request()->all();

            $join = $join->on($name . '.' . $first, '=', $second);

            if (!empty($request['contractor_hierarchy_id'])) {
                $join->where('contractor_hierarchy_relation.contractor_hierarchy_id', '=', $request['contractor_hierarchy_id']);
            }
        });

        if (!is_null($maxDepth)) {
            $query->where($this->getDepthName(), '<', $maxDepth);
        }

        return $query;
    }

These lines in both function, resulted in my desired behavior;
            **if (!empty($request['contractor_hierarchy_id'])) {
                $join->where('contractor_hierarchy_relation.contractor_hierarchy_id', '=', $request['contractor_hierarchy_id']);
            }
        });**

Probably there is an interface to add such constraints but I can't figure it out. Tried to add a query constraint with eager loading but it worked for the segment that selects records from CTE only.

**Comment by staudenmeir** [comment]
There is currently no other way than overriding these methods.

What you can do, is simplifying this part by reusing the package's methods. Take a look at https://github.com/staudenmeir/laravel-adjacency-list/issues/46#issuecomment-735271029.

The constraint on `contractor_hierarchy_relation.contractor_hierarchy_id` doesn't need to be inside the join clause, right?

**Comment by has5aan** [comment]
Absolutely.

Adding;
```php
    private static $hierarchyId;

    /**
     * Executes the query defined in the closure within the scope of provided hierarchy.
     * @param int $hierarchyId
     * @param callable $callback Closure returning a Model.
     * @return Model
     */
    public static function forHierarchy(int $hierarchyId, callable $callback): Model
    {
        static::$hierarchyId = $hierarchyId;

        return $callback();
    }
```
along with the proposed changes [here](https://github.com/staudenmeir/laravel-adjacency-list/issues/46#issuecomment-735271029) and with all my existing queries wrapped within the callback, does the job nicely and decouples request object from model.

Thanks a lot.
