### ISSUE TITLE
Legacy databases

### ISSUE THREAD

**Issue by robsontenorio** [staudenmeir/laravel-adjacency-list#44]
Nice work!

Woud you accept a PR for a legacy  database?

https://cedocs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=GIC_intro

We have made it work with Laravel

https://github.com/jeandormehl/laracache

**Comment by staudenmeir** [comment]
Have you already prepared the implementation?

**Comment by robsontenorio** [comment]
No, sorry. Closing for now.
