### ISSUE TITLE
belongsToMany Support?

### ISSUE THREAD

**Issue by veganista** [staudenmeir/laravel-adjacency-list#45]
Is there a way of suporting belongs to may relationships?

```php
class Group
{
    use HasRecursiveRelationships;

    public function students()
    {
        return $this->belongsToMany(Student::class);
    }
}
```

The group structure looks something like this:

```
- Darwin High School
    -- Monday
        --- Guitar
    -- Tuesday
        --- Ukele
``` 

A student would be able to be placed into both Guitar and Ukele classes.

I'd like to be able to get all students who are at Darwin High School.

**Comment by staudenmeir** [comment]
I'm already working on that.

**Comment by ldiebold** [comment]
Any updates on this?
I feel bad for even asking... This app has given me an insane amount of value!

**Comment by staudenmeir** [comment]
I'll try to finish it this month.

**Comment by vlados** [comment]
Any updates or if we can help?

**Comment by staudenmeir** [comment]
Still working on it but making good progress.

**Comment by chammeow** [comment]
hello... this is what I need too...

**Comment by ldiebold** [comment]
> Still working on it but making good progress.

Appreciate it! We did our own implementation at work and... it wasn't pretty :sweat_smile:

**Comment by ivanwitzke** [comment]
> > Still working on it but making good progress.
> 
> Appreciate it! We did our own implementation at work and... it wasn't pretty sweat_smile

Would you mind sharing how did you solve your problem? I have the same problem here...

**Comment by staudenmeir** [comment]
The latest release adds support for `BelongsToManyOfDescendants` relationships:
https://github.com/staudenmeir/laravel-adjacency-list#belongstomanyofdescendants

```php
class Group extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function recursiveStudents()
    {
        return $this->belongsToManyOfDescendantsAndSelf(Student::class);
    }
}
```
