### ISSUE TITLE
Error on: MySQL server version for the right syntax to use near 'recursive `laravel_cte`

### ISSUE THREAD

**Issue by slicksenses** [staudenmeir/laravel-adjacency-list#48]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) a' at line 1 (SQL: with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `members` where `members`.`parent_id` = 1 and `members`.`parent_id` is not null) union all (select `members`.*, `depth` + 1 as `depth`, concat(`path`, ., `members`.`id`) from `members` inner join `laravel_cte` on `laravel_cte`.`id` = `members`.`parent_id`)) select count(*) as aggregate from `laravel_cte`) (View: *****)

This error showed up when uploaded on the cpanel yet on my local machine it works perfectly. 
What must be the solution. Please help. Thank you in advanced.
 
Followup question: my cpanel is using 5.6 mysql version, is there any possibilities that these errors happens because of the version I am using?

**Comment by staudenmeir** [comment]
The package requires MySQL 8.0.

**Comment by Kakad3v** [comment]
My MySql version is 8+ and am still getting the same error

**Comment by staudenmeir** [comment]
@Kakad3v What's the result of `mysql --version` on your machine?

**Comment by slicksenses** [comment]
> The package requires MySQL 8.0.
though you did not ask this is what I get in my local machine: 
mysql  Ver 8.0.20 for macos10.15 on x86_64 (MySQL Community Server - GPL)
From online server: mysql  Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by slicksenses** [comment]
I have to close the issue. Since it was working I did upgrade the mysql version. Thank you
