### ISSUE TITLE
rootAncestor return null 

### ISSUE THREAD

**Issue by salarzaidi** [staudenmeir/laravel-adjacency-list#49]
Hey im tring to get rootAncestor from child category but its return null everytime 
 28 is a id of iPhone category which is Leaf node and its parent are Apple -> Laptop -> Electronics & Home Appliances 
 $mostParentAncestor = Category::find(28)->rootAncestor;
dd($mostParentAncestor); // returning null 

result should be **Electronics & Home Appliances**

laravel version 6
PHP 7.3.8

**Comment by staudenmeir** [comment]
Does `Category::find(28)->ancestors` give you the correct result?

**Comment by salarzaidi** [comment]
Yes

**Comment by staudenmeir** [comment]
Is `Electronics & Home Appliances` in `Category::find(28)->ancestors`?

What's the result of `dd(Category::find(28)->rootAncestor()->toSql());`?

**Comment by handhikadj** [comment]
I have this issue. @staudenmeir would you reopen this?
this is the `toSql` dump:

```
with recursive `laravel_cte` as ((select *, -1 as `depth`, cast(`id` as char(65535)) as `path` from `qbank_category` where `qbank_category`.`id` = ?) union all (select `qbank_category`.*, `depth` - 1 as `depth`, concat(`path`, ?, `qbank_category`.`id`) from `qbank_category` inner join `laravel_cte` on `laravel_cte`.`parent_id` = `qbank_category`.`id`)) select * from `laravel_cte` where `parent_id` is null
```

**Comment by staudenmeir** [comment]
@handhikadj Please create a new issue.

**Comment by handhikadj** [comment]
okay. what a quick response
