### ISSUE TITLE
 Unknown column 'laravel_cte.id' 

### ISSUE THREAD

**Issue by Vladislav009** [staudenmeir/laravel-adjacency-list#50]
Hello,
Here you can see my user table schema,
```
Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('surname');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->unsignedBigInteger('parent_id')->index()->nullable();
            $table->string('password');           
            $table->timestamps();
            $table->softDeletes();
        });

```
Here is my code,
```
 $qb = QueryBuilder::for(auth()->user()->descendants()->getQuery())->with([
            'roles',
            'phone',
            'agent:id,name,surname',
            'referral_tags' => fn($query) => $query->where([
                'user_id' => auth()->id(),
                'is_set' => 1,
            ]),
            'referral_tags.tags'
        ])->withCount('descendants')
            ->allowedFilters([
                AllowedFilter::callback('path', function ($query) use ($filter) {
                    $query->where('path', 'like', '%.' . $filter['path']);
                    $query->orWhere('path', 'like', '%.' . $filter['path'] . '.%');
                    $query->orWhere('path', 'like', $filter['path'] . '.%');
                    $query->orWhere('path', 'like', $filter['path']);
                    $query->where('path', '!=', null);
                }),
                AllowedFilter::callback('referral_tag_id', fn($query) => $query->whereHas('referral_tags', function ($q) use ($filter) {
                    $q->whereIn('id', explode(',', $filter['referral_tag_id']));
                })),
                AllowedFilter::callback('role_id', fn($query) => $query->whereHas('roles', function ($q) use ($filter) {
                    $q->whereIn('role_id', explode(',', $filter['role_id']));
                })),
                AllowedFilter::callback('phone', fn($query) => $query->whereHas('phone', function ($q) use ($filter) {
                    $q->where('phone', 'like', '%' . $filter['phones'] . '%');
                })),
                AllowedFilter::callback('name', function ($query) use ($filter) {

                    if (!isset($filter['path'])) {
                        $query->where('name', 'like', '%' . $filter['name'] . '%');
                        $query->orWhere('surname', 'like', '%' . $filter['name'] . '%');
                    } else {
                        $query->where('path', 'like', '%.' . $filter['path']);
                        $query->orWhere('path', 'like', '%.' . $filter['path'] . '.%');
                        $query->where('path', '!=', null);
                        $query->where(function ($query) use ($filter) {
                            $query->where('name', 'like', '%' . $filter['name'] . '%')
                                ->orWhere('surname', 'like', '%' . $filter['name'] . '%');
                        });
                    }


                }),
                AllowedFilter::callback('role', fn($query) => $query->whereHas('roles', function ($q) use ($filter) {
                    $q->whereIn('role_id', explode(',', $filter['role']));
                })),
                'email'
            ]);

        return $qb;
```

Erro:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'laravel_cte.id' in 'where clause' (SQL: with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `users` where `users`.`parent_id` = 2 and `users`.`parent_id` is not null) union all (select `users`.*, `depth` + 1 as `depth`, concat(`path`, ., `users`.`id`) from `users` inner join `laravel_cte` on `laravel_cte`.`id` = `users`.`parent_id`)) select `laravel_cte`.*, (with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `users` where `users`.`parent_id` = `laravel_cte`.`id`) union all (select `users`.*, `depth` + 1 as `depth`, concat(`path`, ., `users`.`id`) from `users` inner join `laravel_cte` on `laravel_cte`.`id` = `users`.`parent_id`)) select count(*) from `laravel_cte` where `laravel_cte`.`deleted_at` is null) as `descendants_count` from `laravel_cte` where exists (select * from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `laravel_cte`.`id` = `model_has_roles`.`model_id` and `model_has_roles`.`model_type` = App\Models\User and `roles`.`id` in (7)) and `laravel_cte`.`deleted_at` is null limit 15 offset `0)``

The test server does not have this error, the production has

Test server:
Laravel 8,
Php 7.4
mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)

Prod server 
Laravel 8,
Php 7.4
mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for Linux (x86_64) using readline 5.1

Thanks

**Comment by staudenmeir** [comment]
Unfortunately, MariaDB doesn't support this kind of query yet:
https://jira.mariadb.org/browse/MDEV-19077

**Comment by Vladislav009** [comment]
@staudenmeir Got it, thanks for the answer. I think in compatibility with MariaDB it is worth making a note that not all types of requests are supported. At the moment, it is baffling
