### ISSUE TITLE
Additional where condition for ancestors

### ISSUE THREAD

**Issue by VanoDevium** [staudenmeir/laravel-adjacency-list#51]
Hi, @staudenmeir
I want to thank you again for the wonderful library.

But I have next difficulty:
I store different binary structures in the **one table**. 

In this table I store every **person** as
- **ID** - his unique identifier for this table
- **GROUP_ID** - identifier of group (like identifier of binary structure)
- **USER_ID** - his real identifier from main business system
- **PARENT_ID** - unique identifier of his parent according to binary structure
- **REFERRER_ID** - real identifier of his referrer from main business system

So, table looks like 

<table>
<tr>
	<td>ID
	<td>PARENT_ID
    <td>GROUP_ID
	<td>USER_ID
	<td>REFERRER_ID
<tr>
	<td>1
	<td>null
	<td>1
    <td>200
	<td>null
<tr>
	<td>2
	<td>null
	<td>2
    <td>300
	<td>null
<tr>
	<td>3
	<td>2
	<td>2
    <td>301
	<td>300
<tr>
	<td>10
	<td>9
	<td>2
    <td>310
	<td>300
</table>

And now main question: 
I want to get all referrers of my last "node".
Of course, i have changed parentKey and localKey to USER_ID and REFERRER_ID accordingly.
But, as you can see in my case, I have to append to where conditions additional string.

I will try to explain as bold text:

with recursive "laravel_cte" as (
    select *
    from (
             select *, 0 as "depth", cast("user_id" as text) as "path"
             from "table"
             where "table"."user_id" = 309
			 **AND "table"."group_id" = 2**
         )
    union all
    select "table".*,
           "depth" - 1 as "depth",
           "path" || '.' || "table"."user_id"
    from "table"
             inner join "laravel_cte" on "laravel_cte"."referrer_id" = "table"."user_id"
             **AND "laravel_cte"."group_id" = "table"."group_id"**
)

Naturally, I clearly understand that my case is very rare, but maybe there is some solution?

**Comment by staudenmeir** [comment]
What does the PHP query look like?

**Comment by webdevium** [comment]
My class (extends basic model with your traits)
```
<?php

namespace App\Models;

class ReferralNode extends BinaryNode
{
    protected $guarded = [];

    /**
     * @return string
     */
    public function getParentKeyName(): string
    {
        return 'referrer_id';
    }

    /**
     * @return string
     */
    public function getLocalKeyName(): string
    {
        return 'user_id';
    }
}
```


And query from my controller/action:
```
$referral->ancestors()->get();
```

**Comment by staudenmeir** [comment]
Why are you using these custom local and parent keys?

**Comment by webdevium** [comment]
Because it is the main aim of business task: I have to retrieve levels of referrers (**user_id** as real user's ID of business system).

It sounds difficult :( 
User **with real ID 1** can be in different binary structures in the one table.
So, if I want to retrieve him as my referrer, I must make query with **where user_id = $myReferrerID and group_id = $myGroupID**

**Comment by staudenmeir** [comment]
> User with real ID 1 can be in different binary structures in the one table.

In this case, you would have multiple rows with the same `user_id`?

**Comment by webdevium** [comment]
@staudenmeir No. In this case I want to get unique users (by user_id as REAL ID) in my structure (by GROUP_ID) linked by user_id => referrer_id pairs.

**Comment by staudenmeir** [comment]
Can you share the table's migration?

**Comment by webdevium** [comment]
@staudenmeir Sure.
```
class BinaryTreeTable extends Migration
{
    public const TABLE = 'binary_tree';

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
        Schema::create(self::TABLE, function (Blueprint $table) {
            $table->integerIncrements(BinaryNode::ID);
            $table->unsignedInteger(BinaryNode::GROUP_ID)->index();
            $table->unsignedInteger(BinaryNode::USER_ID)->index();
            $table->unsignedInteger(BinaryNode::REFERRER_ID)->nullable()->index();
            $table->unsignedInteger(BinaryNode::PARENT_ID)->nullable()->index();
            $table->string(BinaryNode::BRANCH)->default(Branch::LEFT);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down(): void
    {
        Schema::dropIfExists(self::TABLE);
    }
}
```
