### ISSUE TITLE
Cannot install on Laravel 8.0

### ISSUE THREAD

**Issue by pda-code** [staudenmeir/laravel-adjacency-list#53]
Cannot install on Laravel 8.0

![image](https://user-images.githubusercontent.com/10973438/108859030-7a0c5d00-75f5-11eb-8c6f-8052f3eb76f7.png)

**Comment by staudenmeir** [comment]
Please try `composer require staudenmeir/laravel-adjacency-list:"^1.6"`.

**Comment by pda-code** [comment]
Worked fine!!! thanks !!!

P.S. Your packages are brilliant!

**Comment by Ariziky** [comment]
Hi, for me, there is no issue during installation; but the package is not installed at the end.
I'm using Laravel 9.17 and PHP 8.1.0.

Need help, please.

**Comment by staudenmeir** [comment]
@Ariziky Please create a new issue. What do you mean by "the package is not installed at the end"? Is there an error?
