### ISSUE TITLE
Additional relationships - hasManyOfAncestors, hasManyOfAncestorsAndDescendants, ancestorsAndDescendants etc.

### ISSUE THREAD

**Issue by kitbs** [staudenmeir/laravel-adjacency-list#55]
Hello @staudenmeir 

Thank you for such an excellent package!

The hasManyOfDescendants(AndSelf) relationship is so useful, and I wonder if you would consider implementing the following additional relationships:

- hasManyOfAncestors(AndSelf)
- hasManyOfAncestorsAndDescendants(AndSelf)
- ancestorsAndDescendants(AndSelf)

I hope the relationship names illustrate the potential use cases. For example, in this family tree, I would just be interested in the direct line of ancestors and descendants, and no siblings at the Self level or above.

- **Grandparent**
    - **Parent**
        - _**Self**_
            - **Child**
                - **Grandchild**
            - **Child**
        - ~~Sibling~~
            - ~~Nephew/Niece~~
    - ~~Uncle/Aunt~~
        - ~~Cousin~~
- ~~Great Uncle/Aunt~~

**Comment by staudenmeir** [comment]
> ancestorsAndDescendants(AndSelf)

You can now get this with the `bloodline()` relationship:
https://github.com/staudenmeir/laravel-adjacency-list#included-relationships

**Comment by staudenmeir** [comment]
> hasManyOfAncestors(AndSelf)
> hasManyOfAncestorsAndDescendants(AndSelf)

I released a new version that adds support for these relationships (and others) using [staudenmeir/eloquent-has-many-deep](https://github.com/staudenmeir/eloquent-has-many-deep):
https://github.com/staudenmeir/laravel-adjacency-list#concatenation

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function hasManyOfAncestors()
    {
        return $this->hasManyDeepFromRelations(
            $this->ancestors(),
            (new static)->posts()
        );
    }

    public function hasManyOfAncestorsAndSelf()
    {
        return $this->hasManyDeepFromRelations(
            $this->ancestorsAndSelf(),
            (new static)->posts()
        );
    }

    public function hasManyOfAncestorsAndDescendantsAndSelf()
    {
        return $this->hasManyDeepFromRelations(
            $this->bloodline(),
            (new static)->posts()
        );
    }
    
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}
```
