### ISSUE TITLE
[Question] How to get all child nodes for a specific branch?

### ISSUE THREAD

**Issue by nagsamayam** [staudenmeir/laravel-adjacency-list#57]
Hi, @staudenmeir  
Firstly, I wanted to thank you for this awesome package.

I have binary tree structure and table schema like below 
![binary-tree](https://user-images.githubusercontent.com/3983455/118396208-12056a00-b66c-11eb-8c6a-222182517b6d.jpeg)

![table-scheme](https://user-images.githubusercontent.com/3983455/118396632-04e97a80-b66e-11eb-847b-8c42dc6fcb73.jpeg)

How can I retrieve all descendants nodes a for a node for a specific branch(left or right). Can you please help me?
Eg: For node ID 2, I would like to retrive all left descendants i.e 4, 6, 7
      For node ID 3, I would like to retrive all right descendants i.e 9, 12, 13

Thank you

**Comment by staudenmeir** [comment]
That's not a trivial issue. You can use the `treeOf()` scope:

```php
$constraint = function ($query) {
    $query->where('parent_id', 2)->where('branch', 'left');
};

Node::treeOf($constraint)->get();
```

However, this doesn't work with eager loading. Do you also need that?

**Comment by nagsamayam** [comment]
> That's not a trivial issue. You can use the `treeOf()` scope:
> 
> ```
> $constraint = function ($query) {
>     $query->where('parent_id', 2)->where('branch', 'left');
> };
> 
> Node::treeOf($constraint)->get();
> ```
> 
> However, this doesn't work with eager loading. Do you also need that?

Thank you sooooo much for the swift response. I request you with eagar loading also

**Comment by staudenmeir** [comment]
I don't see a feasible way to define a direct relationship, but you can combine two relationships and simplify the usage with an accessor:

```php
class Node extends Model
{
    use HasRecursiveRelationships;

    public function getLeftDescendantsAttribute()
    {
        return $this->leftChild->descendantsAndSelf;
    }

    public function leftChild()
    {
        return $this->hasOne(static::class, 'parent_id')->where('branch', 'left');
    }
}

Node::find(2)->leftDescendants;

Node::with('leftChild.descendantsAndSelf')->find(2)->leftDescendants;
```

**Comment by nagsamayam** [comment]
> I don't see a feasible way to define a direct relationship, but you can combine two relationships and simplify the usage with an accessor:
> 
> ```
> class Node extends Model
> {
>     use HasRecursiveRelationships;
> 
>     public function getLeftDescendantsAttribute()
>     {
>         return $this->leftChild->descendantsAndSelf;
>     }
> 
>     public function leftChild()
>     {
>         return $this->hasOne(static::class, 'parent_id')->where('branch', 'left');
>     }
> }
> 
> Node::find(2)->leftDescendants;
> 
> Node::with('leftChild.descendantsAndSelf')->find(2)->leftDescendants;
> ```

Thanks a lot @staudenmeir. You made my day.
