### ISSUE TITLE
showing descendants of descendants

### ISSUE THREAD

**Issue by whoami15** [staudenmeir/laravel-adjacency-list#58]
Firstly, thank you @staudenmeir for making this package.

**Laravel version**: ^7.0
**Package version**: ~1.4

Hello @staudenmeir , is there any way to show the `descendants` of `descendants` and limiting the `depth`?

I have the below query which gets the `descendants` of the current user logged in. What I want to do is, also get the `descendants` of every `descendants` but only limit the `depth` to 3.

Query:
```php
$user = Auth::user();
$descendants = User::find($user->id)->descendants()->whereDepth('<', 11)->get();
```

Example:
```shell
-------------------------------
|  id  |  name  |  parent_id  |
|  1   |  John  |  NULL       |
|  2   |  Jane  |  1          |
|  3   |  Joe   |  2          |
|  4   |  Mae   |  3          |
|  5   |  Deric |  2          |
|  6   |  Cliff |  2          |
|  7   |  Koa   |  2          |
-------------------------------
```

Expected Result (the current logged user is John:  `Deric` , `Cliff` , `Coa` will show under `Jane's` Depth 1
```shell
| Depth  | Name  |
| -------|-------|
|  1     | Jane  |
------------------
|--------|  1   | Deric |
|--------|  1   | Cliff |
|--------|  1   | Koa   |
------------------
|  2     | Joe   |
|  3     | Mae   |
```

**Comment by staudenmeir** [comment]
> Result (the current logged user is John: Deric , Cliff , Coa will show under Jane's Depth 1

This is the result you are getting at the moment?

**Comment by whoami15** [comment]
@staudenmeir, sorry. that is the result I'm expecting.

**Comment by staudenmeir** [comment]
Sorry, I don't fully get the expected result:
How are `Deric`, `Cliff` and `Coa` different from `Joe`? Aren't they all direct children of `Jane`?

**Comment by whoami15** [comment]
Yes they are all children of `Jane`, `Deric`, `Cliff`, and `Koa`.
Sorry if it's confusing. I want to show the `descendants` of `John` and also show the `descendants`  of `descendants ` of `John` but only limiting the `depth` to 3.

Here's an example:
```
John's Descendants: ▶

"depth" => 1
"name" => Jane

    Jane's Descendants: ▶

        "depth" => 1
        "name" => Deric

        "depth" => 1
        "name" => Cliff

        "depth" => 1
        "name" => Koa

"depth" => 2
"name" => Joe

"depth" => 3
"name" => Mae
```

**Comment by staudenmeir** [comment]
Can you show me the difference between your expected result and the result of a query with `->descendants()->whereDepth('<=', 3)`?

**Comment by whoami15** [comment]
> Can you show me the difference between your expected result and the result of a query with ->descendants()->whereDepth('<=', 3)?

The result of that is:
```shell
John's Descendants: ▶

"depth" => 1
"name" => Jane

"depth" => 2
"name" => Joe

"depth" => 3
"name" => Mae
```

> Are you looking for a nested result instead of a flat list?

Yes, I am looking for the nested result.

**Comment by staudenmeir** [comment]
This functionality is not included yet, but I'm working on it (see also #33).

**Comment by whoami15** [comment]
I see, thank you very much for your hard work on this package.

**Comment by raphaelmsr** [comment]
Agreed, feature highly useful and again thank you sooo much for your contribution to the Laravel world

**Comment by staudenmeir** [comment]
The latest release adds the `toTree()` method:

```php
$tree = $descendants->toTree();
```

**Comment by raphaelmsr** [comment]
Simply the best out there, thanks Jonas !

**Comment by whoami15** [comment]
Thank you very much!
