### ISSUE TITLE
can you use with manyToMany?

### ISSUE THREAD

**Issue by justasSendrauskas** [staudenmeir/laravel-adjacency-list#59]
Hello,

so the example given in the readme is that if you have a table {id, parent_id }, though I am wondering if this can be used for manyToMany relationship having i.e.:

groups {id, name}
group_group { parent_id, child_id } 

?

Thank you very much,
Justas

**Comment by staudenmeir** [comment]
I'm working on that: #26

**Comment by justasSendrauskas** [comment]
you are brilliant Mr Jonas!
