### ISSUE TITLE
Collision with eloquent-eager-limit

### ISSUE THREAD

**Issue by tobyzerner** [staudenmeir/laravel-adjacency-list#6]
Getting this when I add both the `HasRecursiveRelationships` and `HasEagerLimit` to a model:

> Trait method newBaseQueryBuilder has not been applied, because there are collisions with other trait methods on App\Category

Any way to make the two play nice? I don't need them to work on the same relationship, but different relationships on the same model.

**Comment by staudenmeir** [comment]
Unfortunately, there's no elegant solution for this. Try the following, it should work with most setups.

Create your own `HasRecursiveRelationships` trait with the code from `Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships` *except* the line `use QueriesExpressions;`:

```php
trait HasRecursiveRelationships
{
    public function getParentKeyName()
    {
        return 'parent_id';
    }

    // TODO
}

class Category extends Model
{
    use \Your\Namespace\HasRecursiveRelationships, HasEagerLimit;
}
```

**Comment by tobyzerner** [comment]
I'm getting this:

> Call to undefined method Staudenmeir\LaravelAdjacencyList\Eloquent\Builder::withRecursiveExpression()

Any ideas? I guess it's looking like I'll need to implement my own Builder and Grammar classes...

**Comment by staudenmeir** [comment]
Yeah, I'm afraid so. I'll look into ways to simplify that.

**Comment by tobyzerner** [comment]
Thanks! Maybe if each package could expose a couple traits that can be used to compose the Builder/Grammar classes? Or something like that

**Comment by vanthao03596** [comment]
@staudenmeir any update status ?

**Comment by staudenmeir** [comment]
I'm still working on it.

**Comment by mrgodhani** [comment]
Experiencing similar issue when pairing with https://github.com/staudenmeir/eloquent-param-limit-fix

**Comment by tobyzerner** [comment]
@staudenmeir have you had any further thoughts about this?

**Comment by toyi** [comment]
@staudenmeir Any update on this issue?

**Comment by staudenmeir** [comment]
I've been trying to find a solution that doesn't a "merger" package for each combination of conflicting packages, but there doesn't seem to be a better way. So I'm working on these packages at the moment.

**Comment by staudenmeir** [comment]
I released a new package that merges `eloquent-eager-limit` and `laravel-adjacency-list`:
https://github.com/staudenmeir/eloquent-eager-limit-x-laravel-adjacency-list

**Comment by mrgodhani** [comment]
@staudenmeir Looking at the package it says supports only Laravel 9+. What about applications if we are still on Laravel 6? Is it backwards compatible?

**Comment by staudenmeir** [comment]
The package only supports Laravel 9+ because supporting older versions is not feasible for me. I already spent way too much time on this issue. Laravel 6 itself also doesn't get updates anymore (except for security fixes).
