### ISSUE TITLE
Getting siblings of normal belongsTo relation

### ISSUE THREAD

**Issue by amshehzad** [staudenmeir/laravel-adjacency-list#64]
Hi, first of all thank you for this great plugin! 

So I was thinking that it'll be great it we can use the concept for normal relations as well so for example let say we have this structure: 

`Company `→ has many → `Projects`

Now it would be nice if we can use the sibling concept here so we can get all projects for the same company from any project. 

currently I'm doing like this:

`$projects = $project->company->projects`

would be awesome if I can simply do: 

`$projects = $project->siblings`

Once again, thank you so much for your awesome plugins!

**Comment by staudenmeir** [comment]
Which of those two models uses the `HasRecursiveRelationships` trait?

**Comment by amshehzad** [comment]
None, I was thinking that if some how we can use the siblings concept ( which I like a lot ) on the other relations so for example if we add the trait on Project model and the project belongs to Company then we can get siblings of the project i.e Other projects from same company. not sure if it even make sense
