### ISSUE TITLE
[QUESTION] Get relation of root ancestor from relation of node of any depth.

### ISSUE THREAD

**Issue by waterbuckit** [staudenmeir/laravel-adjacency-list#67]
Hi, apologies for the rather unclear-sounding title. I have a database structure like the following:
Locations have many sub-locations, sub-locations are recursively related, sub-locations have many areas. I need to get the location from the root ancestor of the area's sub-location. 
I am using your HasManyDeep package for the simplicity of it's HasOneDeepFromRelations relation.
My area has the following relations:

```php
    public function sub_location(){
        return $this->belongsTo(SubLocation::class);
    }

    public function root_ancestor_sub_location(){
        if($this->sub_location->isRoot()->get()){
            return $this->sub_location();
        }
        return $this->hasOneDeepFromRelations($this->sub_location(), (new SubLocation())->rootAncestor());
    }

    public function location(){
        return $this->hasOneDeepFromRelations($this->root_ancestor_sub_location(), (new SubLocation())->location());
    }
```

Is there some way of doing this sensibly? I don't want to have to store the location id on the sub locations since it can be derived from the root ancestor, but if the area is related to the root ancestor, then I must check whether the area's sub location is a root. This works, but I do not want to have to do a query to be able to return a relation. I may be overcomplicating things. Thanks if you can help! Love your package!

**Comment by staudenmeir** [comment]
Can you share the structure/migrations of all three tables and some sample data?

**Comment by waterbuckit** [comment]
> Can you share the structure/migrations of all three tables and some sample data?

Sure! I'll cut out some of the fields that are there as they are irrelevant (address etc).

**locations**
```php
Schema::create('locations', function (Blueprint $table) {
    $table->id('id');
    $table->string('name');
    $table->timestamps();
    $table->softDeletes();
});
```

**sub_locations**
```php
Schema::create('sub_locations', function (Blueprint $table) {
    $table->id();
    $table->string('name')->nullable();
    $table->foreignId('location_id')->nullable()->constrained()->onDelete('cascade');
    $table->foreignId('sub_location_id')->nullable()->constrained()->onDelete('cascade');
    $table->softDeletes();
    $table->timestamps(); 
});
```

**areas**
```php
Schema::create('areas', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->foreignId('sub_location_id')->constrained()->onDelete('cascade');
    $table->softDeletes();
    $table->timestamps();
});
```

I don't precisely know how you want me to provide some sample data, but if it were me, I'd make it in `php artisan tinker`, running some commands like:
```php
$loc = Location::create(['name' => 'Test Location']);
```
```php
$subA = SubLocation::create(['name' => 'Test SubLocationA', 'location_id' => $loc->id]);
$subB = SubLocation::create(['name' => 'Test SubLocationB', 'sub_location_id' => $subA->id]);
```
```php
$areaA = Area::create(['name' => 'Test AreaA', 'sub_location_id' => $subA->id]);
$areaB = Area::create(['name' => 'Test AreaB', 'sub_location_id' => $subB->id]);
```
The idea is that I'd like to derive the Location from the root ancestor SubLocation of a given Area. I hope this makes sense? Thanks for your help! Hope this is sufficient, do let me know if I can provide anything else.

**Comment by staudenmeir** [comment]
How are you using the `location` relationship at the moment? It doesn't work with eager loading, right?

**Comment by waterbuckit** [comment]
Correct, it doesn't work with eager loading, obviously it does work with just `Area::first()->location`.

If my Area was related to a child node (of any depth below the root) of the root ancestor sublocation then my relation wouldn't need that extra 'isRoot' check, but if, for example, the area is related to the root ancestor sublocation, calling `rootAncestor` on that sublocation, as it is the root, will return null. If that makes any sense at all? Haha.

**Comment by staudenmeir** [comment]
Unfortunately, there is no realistic way to create a direct relationship that can you use for eager loading.

I suggest that you use separate relationships and simplify the usage with an accessor:

```php
class Area extends Model
{
    public function getLocationAttribute()
    {
        return $this->sub_location->rootAncestor->location ?? $this->sub_location->location;
    }
}

Area::with('sub_location.rootAncestor.location')->get();

$area->location
```

**Comment by waterbuckit** [comment]
Thanks for this suggestion! In the end, I've decided to store the location_id on each child sub_location. Just cuts down on the complexity, even if it does mean doing a bit of management. Makes it a lot easier to get at the location of an area.

```php
public function location(){
    return $this->hasOneDeepFromRelations($this->sub_location(), (new SubLocation())->location());
}
```
Then from my location, I can access all the bits I need:
```php
trait HasManySubLocations {
    public function sub_locations(){
        return $this->hasMany(SubLocation::class);
    }
    public function root_sub_locations(){
        return $this->sub_locations()->isRoot();
    }
    public function getSubLocationTreeAttribute(){
        return SubLocation::treeOf(function($query) {
            $query->whereNull('sub_location_id')->where('location_id', $this->id);
        });
    }
    public function areas(){
        return $this->hasManyThrough(Area::class, SubLocation::class);
    }
}
```
I did want to use the `descendantsAndSelf` custom relation but my Location model uses a bunch of other traits that end up colliding with some of the methods from this package so I settled for this. Seem sensible?

**Comment by staudenmeir** [comment]
Yes, absolutely.
