### ISSUE TITLE
[Discussion] Could this package be the base for graph traversal ?

### ISSUE THREAD

**Issue by coclav** [staudenmeir/laravel-adjacency-list#68]
Servus Jonas & Team, 

We love this package. 

This package works on the premise we are dealing with a **tree** : a node has one, and only one, parent. 

A (directed) **graph** differs in the fact that a node can have one, or more, "parents" (the term parent doesn't really make sense anymore though).

![image](https://user-images.githubusercontent.com/1837434/134237201-40f3c8db-a3c2-4a04-91aa-76cb675d9175.png)

This package already offers way to traverse this very specific kind of graph which is a tree.

Now i'm wondering if this package could be the base to do more advanced traversal where a given node can have several parents.

Because a given "node" can have several "parent" we'll need to have an additional table. 

Nodes

id |  ...columns 
------------ | ---
A| 
B | 
C |
D |
E |
F |

Edges (lines)

source_node_id | target_node_id
------------ | -------------
A | B
B | C
C | E
E | F
E | D
D | B

Alternatively, this could rely on your json-relationships package so that there is only one table

Nodes

id |  relation_ids | ...columns 
------------ | ---|---
A| [B]
B | [C]
C | [E]
D | [ B]
E | [D,F]
F | []

There is of course a number of issues to manage, loops, etc. 

Any thoughts ? 

I'd love to try contribute to implementation. I have tried to dissect the way it works but I still have lots of concepts to grasp not only with Eloquent but SQL! Amazing work.

**Comment by staudenmeir** [comment]
I've been working on #26 for a while. That's the same topic, right?

**Comment by coclav** [comment]
Yes indeed. How come I didn’t find it. Closing this one then.

**Comment by staudenmeir** [comment]
No worries. If you can, please add details about the features you would want/need from this implementation (relationships, scopes etc.). I'll see what the best way would be for you to contribute to the code.

**Comment by staudenmeir** [comment]
Thanks for your detailed posts. I hadn't fully realized the potential of this feature.

**Comment by coclav** [comment]
Yeah graph database are very powerful at traversing nodes/edges and finding a path in between items whatever their nature.  I think this package has some potential to cover some of the use cases!
