### ISSUE TITLE
error when model id with string(uuid)

### ISSUE THREAD

**Issue by loveyuxiao** [staudenmeir/laravel-adjacency-list#7]
```
class CreateUserGroupsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_groups', function (Blueprint $table) {
            if (env("DB_CONNECTION") == "mysql") {
                $table->engine = 'InnoDB';
            }
            $table->char('id', 32)->primary()->comment("UUID");
            $table->string('name')->unique();
            $table->string('desc')->nullable();
            $table->boolean('locked')->default(false);
            $table->softDeletes();
            $table->timestamps();
            $table->char('parent_id', 32)->nullable()->index();
            $table->foreign('parent_id')->references('id')->on('parent_id')->onDelete('cascade');
        });
    }
}
```

SQLSTATE[42804]: Datatype mismatch: 7 ERROR: recursive query "laravel_cte" column 13 has type character(32)[] in non-recursive term but type bpchar[] overall LINE 1: ...rsive "laravel_cte" as ((select *, -1 as "depth", array["id"... ^ HINT: Cast the output of the non-recursive term to the correct type. (SQL: with recursive "laravel_cte" as ((select *, -1 as "depth", array["id"] as "path" from "user_groups" where "user_groups"."id" = 8efec07320e744c9a17e7de5fca1bb6c) union all (select "user_groups".*, "depth" - 1 as "depth", "path" || "user_groups"."id" from "user_groups" inner join "laravel_cte" on "laravel_cte"."parent_id" = "user_groups"."id")) select * from "laravel_cte" where "laravel_cte"."deleted_at" is null)

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
The latest release fixes this.
