### ISSUE TITLE
N+1 problem

### ISSUE THREAD

**Issue by nezaboravi** [staudenmeir/laravel-adjacency-list#71]
If you create a component that will list 3 products from 6 categories, N+1 problem happens.
Say, we want to display Product breadcrumb
e.g.
`Vehicles | Leisure | SUV | Mitsubishi Pajero Sport`

Next component shows you another category:

`Equipment | Tractors | 2 WD Tractors | Ferguson M876`

How do you handle this without having N+1?

If i am to show 3 of each products, i will get this:
`N+1 queries: App\Models\Category::App\Models\Category loaded 18 times.`

It says that category model loading him self 18 times.

I have tried plenty of things, but cant get it working.
Last attempt:
```php
Category.php
public function breadcrumbs()
    {
        $root = $this->rootAncestor()->first();
        return $root->tree()->get();
    }
 
Products.php
protected $with = ['user', 'category', 'media'];

    public function breadcrumbs(){
        return $this->category->breadcrumbs();
    }
    
template.blade.php
    @foreach($products as $product)
    <x-product-card :product="$product">
    @endforeach

**Comment by staudenmeir** [comment]
What does the `$products` query look like?

You can use eager loading, but you need adjust the `breadcrumbs()` method:

```php
Category.php
public function breadcrumbs()
    {
        return $this->rootAncestor->tree;
    }
 
Products.php
protected $with = ['user', 'category.rootAncestor.tree', 'media'];

    public function breadcrumbs(){
        return $this->category->breadcrumbs();
    }
```

Do you actually need to fetch the root's ancestor's whole tree for the breadcrumbs? Or you can get only the category's ancestors and show them in reverse order?

**Comment by nezaboravi** [comment]
Hello @staudenmeir 
```php
class Product extends Model
{
    use HasFactory;
    use Searchable;
    protected $with = ['user', 'category', 'media', 'category.parent'];
...
}
```
The query is something like:

```php
Product::search()->paginate(3);
```
Gives back Laravel scout paginated object.
I will try not suggested approach and let you know, thank you :)

**Comment by nezaboravi** [comment]
@staudenmeir 
"Do you actually need to fetch the root's ancestor's whole tree for the breadcrumbs? Or you can get only the category's ancestors and show them in reverse order?"
I need to achieve this
1) Breadcrumbs:
Equipment / Tractors / 4WD Tractors  / Title- John Fergusson

So, when on product, i need that breadcrumb, anyway that is optmized. 
Thanks

**Comment by nezaboravi** [comment]
@staudenmeir any advise?

**Comment by staudenmeir** [comment]
Can you expand the `17 vendor frames...`?

From how I understood your code, I thought that something like `$product->category->ancestors->reverse()->pluck('name')->join(' / ')` would give you the required breadcrumbs.
