### ISSUE TITLE
Incorrect order by path (`depthFirst`)

### ISSUE THREAD

**Issue by amiranagram** [staudenmeir/laravel-adjacency-list#72]
Hi, I've noticed when ordering by path it's using natural sort which sorts them incorrectly.

This is how they are sorted:

```
  0 => "7"
  1 => "7.10"
  2 => "7.11"
  3 => "7.8"
  4 => "7.9"
```

This is how they should be sorted:

```
  0 => "7"
  1 => "7.8"
  2 => "7.9"
  3 => "7.10"
  4 => "7.11"
```

This is how I fixed it in my code:

```php
Chapter::query()
    ->with(['media' => fn ($query) => $query->orderBy('pivot_order', 'asc')])
    ->treeOf(function ($query) {
        $query->where('presentation_id', $this->presentation->id);
    })
    ->orderByRaw("REGEXP_REPLACE ( REGEXP_REPLACE ( REGEXP_REPLACE ( path, '^v', '' ), '(^|\\\\.)(\\\\d+)', '\\\\100000\\2' ), '0+(\\\\d{5})(\\\\.|$)', '\\\\1\\\\2' )")
    ->get()
```

Which is really messy but it does the job.

What it does is, it pads every segment between dots (`.`) in path to 5 numbers adding zeros where missing. Then it's really easy to sort if derived value looks like this:

```
  0 => "00007"
  1 => "00007.00008"
  2 => "00007.00009"
  3 => "00007.00010"
  4 => "00007.00011"
```

If you have a better solution, please let me know.
If you think this is a good solution I can PR.

Cheers.

**Comment by staudenmeir** [comment]
Thanks, I'll look into it. What database are you using?

**Comment by amiranagram** [comment]
@staudenmeir MariaDB 10.5

**Comment by staudenmeir** [comment]
Your regular expression doesn't seem to work for me:
https://dbfiddle.uk/?rdbms=mariadb_10.5&fiddle=ed1d6d8e329fad8c1c9f0f3f83981c75

What are you doing differently?

**Comment by amiranagram** [comment]
@staudenmeir You were missing a few slashes:

https://dbfiddle.uk/?rdbms=mariadb_10.5&fiddle=a3707d40dfe92efe014f53002f72946a

**Comment by amiranagram** [comment]
Not sure, maybe the snipped I posted above is wrong, but here is what I have now in my code, that is working:

```
public function scopeOrderByPath(Builder $query, string $direction = 'asc', int $padCount = 3): Builder
{
    return $query->orderByRaw(<<<SQL
        REGEXP_REPLACE(
            REGEXP_REPLACE(
                REGEXP_REPLACE(path, '^v', ''), '(^|\\\\.)(\\\\d+)', '\\\\100000\\\\2'
            ), '0+(\\\\d\{$padCount\})(\\\\.|$)', '\\\\1\\\\2'
        ) $direction
    SQL);
}
```

**Comment by staudenmeir** [comment]
Thanks. What cases does `REGEXP_REPLACE (..., '^v', '' )` take care of?

**Comment by amiranagram** [comment]
> Thanks. What cases does `REGEXP_REPLACE (..., '^v', '' )` take care of?

Oops. That part is unnecessary, I was using this same query to sort rows by version from a `packages` table I had in another project. That part is removing `v` in `v1.0.0`.

I updated the previous comment. @staudenmeir

**Comment by staudenmeir** [comment]
Thanks. I released a new version that fixes the issue with your regular expression (I added you as a co-author to the commit). It was a bit more complicated because MySQL requires a slightly different expression.

**Comment by amiranagram** [comment]
Thanks for your great work @staudenmeir :)
