### ISSUE TITLE
morphToMany equivalent of hasManyOfDescendantsAndSelf

### ISSUE THREAD

**Issue by toyi** [staudenmeir/laravel-adjacency-list#73]
Is there any support for an equivalent of `hasManyOfDescendantsAndSelf` for `morphToMany` relationships?

My use case is pretty straighforward: 

* `Article` can be associated with many other models. For instance, an `Article` can be associated to a `Category`, a `Product` and a `Destination`.
* I have a polymorphic many to many relationship defined (dedicated table with an `articlable_type` and `articlable_id` columns are defined).

The thing is, `Category` is recursive (each `Category` has a `parent_id` column). I would like to eager load (and/or count) all related `Article` , recursively. 

Said otherwise, if a `Category` has 10 children on 3 levels of depth, I would like this `Category` to eager load all `Article` of all these children. It's pretty much what `hasManyOfDescendantsAndSelf` seems to be doing, but applied to the polymorphic many to many relationship.

If there are no solution at the moment, do you have any workaround?

_Like many others before me, congratulation for this amazing package, it has so much value!_ :+1:

**Comment by staudenmeir** [comment]
Thanks! I'm working on that and will release it soon.

**Comment by toyi** [comment]
Thank you or the quick answer! To be honnest, I have to find a solution quickly, could you just tell me if I should expect the release within 1/2 weeks or if It's more something planned for early 2022 please? 

I'm not pushing you in any way of course, I'm just trying to have some visibility :)

**Comment by staudenmeir** [comment]
Within 1/2 weeks.

**Comment by staudenmeir** [comment]
The latest release adds support for `MorphToManyOfDescendants` relationships:
https://github.com/staudenmeir/laravel-adjacency-list#morphtomanyofdescendants

```php
class Category extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function recursiveArticles()
    {
        return $this->morphToManyOfDescendantsAndSelf(Article:class, 'articlable');
    }
}
```

**Comment by toyi** [comment]
Works perfectly, thank you it's awesome.

I guess we can close this issue, have a nice week!

**Comment by mstaack** [comment]
thanks for this feature! i had to use this:
```
public function providers(): MorphToMany
{
    return $this->morphedByMany(Provider::class, 'profile', 'category_profile');
}

public function recursive_providers(): MorphToManyOfDescendants
{
    return $this->morphToManyOfDescendantsAndSelf(Provider::class, 'profile', 'category_profile', relatedPivotKey: 'profile_id');
}
```
