### ISSUE TITLE
hasManyOfChildren

### ISSUE THREAD

**Issue by ccerrillo** [staudenmeir/laravel-adjacency-list#74]
In the docs explain how to get hasManyOfDescendants, but whereDepth is not available, How can i achieve hasManyOfChildren or use whereDepth with hasManyOfDescendants?

**Comment by staudenmeir** [comment]
What is your recursive (e.g. `User`) and your related model (e.g. `Post`)?

**Comment by ccerrillo** [comment]
For example, having this, i want to restrict recursivePosts to only direct user childs:

```
class User extends Eloquent
{

   public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function recursivePosts()
    {
        return $this->hasManyOfDescendants(Post::class);
    }

    public function users()
    {
        return $this->hasManyOfDescendants(self::class);
    }

}
```

**Comment by staudenmeir** [comment]
You can do that with a native `HasManyThrough` relationship:

```php
class User extends Eloquent
{
   public function childPosts()
    {
        return $this->hasManyThrough(Post::class, static::class, 'parent_id');
    }
}
```

**Comment by ccerrillo** [comment]
Hell! it was very easy, this is exactly what i need, thanks!

If you allow me to abuse a little more... how could the same thing be achieved but using depth, for example to filter up to depth 15?

**Comment by staudenmeir** [comment]
I released a new version that allows you to add intermediate depth constraints:

```php
$user->recursivePosts()
    ->withIntermediateScope(
        'depth',
        function ($query) {
            $query->whereDepth('<=', 15);
        }
    )->get();
```

**Comment by ccerrillo** [comment]
Great! Thanks!!
