### ISSUE TITLE
Getting tree via another model relationship

### ISSUE THREAD

**Issue by chrispage1** [staudenmeir/laravel-adjacency-list#8]
Hi,

Brilliant plugin! I'm having a bit of an issue where the resulting query generates an SQL error.

I have two models - `User` and `File` with corresponding tables, joined by a `FileUser` pivot model.

The `File` model has a parent_id and id and uses the `HasRecursiveRelationships` trait. So what I'm actually trying to do is grab files that are recursively owned by the user - 

```php
// get files recursively owned by the user
auth()->user()->files()->tree()->get();

// even better would be to further filter this tree
auth()->user()->files()->tree()->where('name', 'LIKE', '%testing%')->get();
```

However, when running either of the above the resulting query is - 

```sql
with recursive `laravel_cte` as (
    (
        select *, 0 as `depth`, cast(`id` as char(65535)) as `path`
        from `files`

        where `parent_id` is null)

    union all
    (
        select `files`.*,
               `depth` + 1 as `depth`,
               concat(`path`, '.', `files`.`id`)
        from `files`
                 inner join `laravel_cte` on `laravel_cte`.`id` = `files`.`parent_id`
    )
)
select `laravel_cte`.*,
       `file_user`.`user_id` as `pivot_user_id`,
       `file_user`.`file_id` as `pivot_file_id`
from `laravel_cte`
         inner join `file_user` on `files`.`id` = `file_user`.`file_id`

where `file_user`.`user_id` = '1'
  and `name` LIKE '%testing%'
  and `laravel_cte`.`deleted_at` is null
order by `name` asc
```
and an error is generated because of the join on line 21

```sql
inner join `file_user` on `files`.`id` = `file_user`.`file_id`
```

At this point in the query, it doesn't actually have access to the files table. Is querying in this way just not at all possible, or is this a slight bug in the plugin?

Thanks,
Chris.

**Comment by staudenmeir** [comment]
Unfortunately, this kind of query is not supported at the moment and I don't see a way to make it work.

You can get the desired result like this:

```php
$constraint = function (Builder $query) {
    $query->whereIn('id', auth()->user()->files()->pluck('id'));
    // Alternative: $query->whereIn('id', auth()->user()->files()->select('id')->getQuery())
};

$tree = File::withRelationshipExpression('desc', $constraint, 0)
    ->where('name', 'LIKE', '%testing%')
    ->get();
```

This scope is only used internally, but I could add a nice wrapper, something like `treeFrom()`.

**Comment by chrispage1** [comment]
Thank you! I thought it might be that it's a little tricky. That solution works nicely, my concern is that it might be a little inefficient when there's a lot of data (there could be hundreds of thousands of files!)

I wish I could work out a more efficient way of sharing a recursive file structure and checking the user has permission to a higher level folder!

**Comment by staudenmeir** [comment]
> That solution works nicely, my concern is that it might be a little inefficient when there's a lot of data (there could be hundreds of thousands of files!)

Do you mean this particular query or recursive CTEs in general?

**Comment by chrispage1** [comment]
Recursive CTE's in general - I'm not too sure how efficient they are?

**Comment by staudenmeir** [comment]
I don't think there is really an alternative for queries on this kind of structure (besides separate queries for each level).

I haven't tested them with large amounts of data, but I would expect them to run reasonably fast with proper indexing. It would great if you could report back with your experiences.

**Comment by chrispage1** [comment]
A bit of a long shot... but as I sole developer myself, I don't suppose I'd be able to talk an idea through with you and see if you have any suggestions on schema? I'm having real problems working out the ideal structure, perhaps even if relational is the way to go... thanks!

**Comment by staudenmeir** [comment]
Sure, can you write me an email with the requirements for application/schema?

**Comment by chrispage1** [comment]
Thank you - I've sent over an email. I appreciate the help!
