### ISSUE TITLE
How to get the tree without self

### ISSUE THREAD

**Issue by ayman-elmalah** [staudenmeir/laravel-adjacency-list#81]
When i'm getting the tree of object, it return the same object in the tree, i don't need the same object name

So if i have tree of phone

iphone will have the tree like

electronics > phones > iphone

I don't need iphone to be in the tree, i need the tree to be like electronics > phone

**Comment by ayman-elmalah** [comment]
$response = $model->tree()->get();

And for the model

public function getCustomPaths(): array
    {
        return [
            [
                'name' => 'slug_path',
                'column' => 'name',
                'separator' => ' > ',
            ],
        ];
    }

**Comment by staudenmeir** [comment]
`$model->tree()->get()` is equivalent to `YourModel::tree()->get()` and fetches the _whole_ tree of _all_ models.

What result are you expecting? "tree of object" sounds like you want to get the model's descendants: `$model->descendants`

> I don't need iphone to be in the tree, i need the tree to be like electronics > phone

This sounds like you want to get the model's ancestors: `$model->ancestors`

**Comment by ayman-elmalah** [comment]
No Model::tree()->get() 
will return in slug_path [electronics > phones > iphone]
ancestors will return the full list as relation, i need it like the tree because it's will be sorted in datatable, i just need the names not the full list, as tree

**Comment by ayman-elmalah** [comment]
I just need a way to get the tree or item without it self in slug path, just parents without it self, in same way as tree
In my question $model is Model it's a class, it just $model because of dependecy injection

**Comment by staudenmeir** [comment]
`$model` is the "iPhone" object, right? What result do you need here exactly? Only `electronics > phones` as the model's path without its slug?

**Comment by ayman-elmalah** [comment]
Yes that's right

**Comment by staudenmeir** [comment]
Use the `ancestors` relationship and build the slug path in PHP:

```php
$slugPath $model->ancestors()->pluck('name')->reverse()->implode(' > ')
```

**Comment by ayman-elmalah** [comment]
I already implement this solution before but it's not working on datatable search slug path work

**Comment by staudenmeir** [comment]
How do you mean that? Why is it not working?
