### ISSUE TITLE
Getting parents and the parents' siblings

### ISSUE THREAD

**Issue by developman-akl** [staudenmeir/laravel-adjacency-list#82]
Hi, 
Could you please give me an example how to implement in one query when need to retrive also the siblings of all parents using `ancestors` and `ancestorsAndSelf`? 
The `ancestorsAndSelf` itself works fine of course, but I would like to know how to combine it properly with the `siblings` for each parent level in one query.
Example:

```
id | parent_id
1  |  
2  | 
3  | 2
4  | 2
5  | 
6  | 4
7  | 6
8  | 6
9  | 5
10  | 8
11  | 8
```

Expected result when querying ID11 is: 
11, 10, 8, 7, 6, 4, 3, 2

Thank you!

**Comment by staudenmeir** [comment]
The package doesn't provide a relationship for this. Do you need a full relationship (e.g. for eager loading) or is query to just fetch the results sufficient?

**Comment by developman-akl** [comment]
Sorry for the late reply. Actually it is needed to create a report, not just for optics.
Is there another workaround with the existing relationships? No matter how ugly is that. :)

**Comment by staudenmeir** [comment]
How would you use the relationship? (Why) does it have be in one query?

**Comment by developman-akl** [comment]
It doesn't have to be one query, but needs to feed a server side Laravel Datatables which works faster with a query object rather than with a collection.
Like this:

`Datatables::of(User::query())->make(true)`

https://datatables.yajrabox.com/eloquent/basic-object

**Comment by staudenmeir** [comment]
You can do something like this to get a collection (depending on the expected order):

```php
$users = User::find(11)->ancestorsAndSelf()->with('siblings')->get();

$collection = $users->map(fn($u) => $u->siblings->prepend($u))->collapse();
```

A (raw) query would also be possible but is more complicated. I'll look into that.

> which works faster with a query object rather than with a collection.

Because of pagination?
