### ISSUE TITLE
Product categories handle string question

### ISSUE THREAD

**Issue by dellow** [staudenmeir/laravel-adjacency-list#85]
Hi,

Great package, I've been using this for a while but I'm not sure if I've been taking full advantage of its power.

If I have a store with a category URL like so: https://store.com/category/clothing/footwear/mens

Is there a suitable way to then query my `Category` model to find a category with the following parent/child hierarchy: "Clothing > Footwear > Mens"

No problem if not, I just wondered if I was missing something.

**Comment by staudenmeir** [comment]
Thanks. You want to find all categories that have these three categories as their ancestors?

Does `Footwear` have to be a direct child of `Clothing` and `Mens` a direct child of `Footwear`? Or can there be categories between them?

What's the field called that stores `clothing` etc.? `slug`?

**Comment by dellow** [comment]
Yes correct, they would be direct children as laid out above.

The field would be `handle`.

**Comment by staudenmeir** [comment]
Try this:

```php
$first = 'clothing';
$second = 'footwear';
$third = 'mens';

$categories = Category::whereHas('ancestors', function ($query) use ($first, $second, $third) {
    $query->where('handle', $third)
        ->whereHas('parent', function ($query) use ($first, $second) {
            $query->where('handle', $second)
                ->whereHas('parent', function ($query) use ($first) {
                    $query->where('handle', $first);
                });
        });
})->get();
```

How many categories do you have in your database?

**Comment by dellow** [comment]
Sorry for the delay. Ok great I will try that. 

Currently quite a few. Around 500 or so most are only 2 level deep though. 

Many thanks for your help. I'll try this and get back to you.
