### ISSUE TITLE
Routing with adjacency...

### ISSUE THREAD

**Issue by skoontastic** [staudenmeir/laravel-adjacency-list#86]
Not really an issue with the package, but hoping just for a push in the right direction. If I'm using this package for, say, a CMS where there are pages multiple levels deep, what's the best way to set up the routes in Laravel?

**Comment by staudenmeir** [comment]
A somewhat similar question came up just this week in #85. Do you have a URL structure like this in mind?

Can you share the table's migration and some sample data?

**Comment by skoontastic** [comment]
So in my particular case I'm building out a website for a school. Pages would have urls something like https://getschools.org/high-school/activities/volleyball/. So all of those would be pages of different models. The High School page would be a School model with a School view, activities would have an Activity model and view, etc., and all of them would have a polymorphic relationship to the Page model which would use the adjacency package so they can be sorted as a tree. A page would have a migration like:

```
public function up()
    {
        Schema::create('pages', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid');
            $table->string('title');
            $table->string('slug');
            $table->date('post_date');
            $table->morphs('pageable');
            $table->foreignId('parent_id')->nullable()->constrained('pages');
            $table->timestamps();
        });
    }
...
```
The Page model would then have a morph relationship to those various models:
```
...
public function pageable()
    {
        return $this->morphTo();
    }
...
```

So I would need some sort of wildcard route for the pages. Does that make sense? I suppose then the controller would be responsible for figuring out what kind of page it is and then presenting the appropriate view.

**Comment by staudenmeir** [comment]
How are the pages in the URL related? Are they direct children of each other (i.e. `high-school` > `activities` > `volleyball`)?

**Comment by skoontastic** [comment]
Yes, they would be related via the `pageable` model, which uses the adjacency list. So `volleyball` would have the `parent_id` of the `activities` page, which would in turn have the `high-school` page as the `parent_id`. The issue is just figuring out how to get the Laravel router to sort of ignore the leading slugs and focus on the last one only.

**Comment by staudenmeir** [comment]
Are `high-school`, `activities` and `volleyball` slugs of `pages` or slugs of `schools`, `activities` etc. (or both)?

Does this type of URL always have exactly three levels?

**Comment by skoontastic** [comment]
No, the levels can be arbitrary, so it could go deeper depending on the page structure of that section. The slugs, I think, would have to be slugs of `pages`.

I really appreciate you thinking about this with me, I understand this isn't exactly inside the scope of the plugin, but it is "adjacent" in a way. _I hope you see what I did there._

**Comment by staudenmeir** [comment]
> The issue is just figuring out how to get the Laravel router to sort of ignore the leading slugs and focus on the last one only.

So the controller wouldn't actually check the URL's slugs and their hierarchy but instead only take the last one and get its page from the database? With a route like https://stackoverflow.com/a/31408082/4848587?

**Comment by skoontastic** [comment]
Sweet, that got me there! Code is raw and ugly, but this seems to work.

```
Route::get('{school}/{path?}', [PageController::class, 'handle'])->where('path', '(.*)');
```

```
class PageController extends Controller
{
    public function handle($school, $path = null)
    {

        if ($path) {
            $path = collect(explode('/', $path));
            $page = Page::where('slug', $path->pop())->first();
        }

        return view('school_page', ['page' => $page, 'school' => $page->pageable]);
    }
}
```

Thanks for the push in the right direction, I really appreciate it.

**Comment by staudenmeir** [comment]
👍 Thanks for your donation!
