### ISSUE TITLE
Getting "Integrity constraint violation: 1052 Column 'depth' in field list is ambiguous"

### ISSUE THREAD

**Issue by jaesung2061** [staudenmeir/laravel-adjacency-list#87]
I have a fresh Laravel and Homestead installation and the latest release of this package.

laravel: v9.2.0  
php: v8.1.0  
mysql: 8.0.27-0ubuntu0.20.04.1  

I'm getting the error message as mentioned in the title:

> SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'depth' in field list is ambiguous

Here is the query:

```
with recursive `laravel_cte` as (
  (
    select
      *,
      1 as `depth`,
      cast(`id` as char(65535)) as `path`
    from
      `comments`
    where
      `comments`.`parent_id` in (
        227,
        228,
        229,
        230,
        231,
        232,
        233,
        234,
        235,
        236,
        237,
        238,
        239,
        240,
        241,
        242,
        243,
        373,
        374,
        375,
        685,
        686,
        687,
        688,
        689,
        690,
        691,
        692,
        693,
        694,
        695,
        696,
        697,
        698,
        699,
        700,
        701,
        702,
        703,
        704,
        705,
        706,
        707,
        708,
        709,
        710,
        711,
        1580,
        1581,
        1582,
        1583,
        1584,
        1585,
        1586,
        1587,
        1588,
        1589,
        1590,
        1591,
        1592,
        1593,
        1594,
        1595,
        1596,
        1597,
        1598,
        1599,
        1600,
        1601,
        1602,
        1603,
        1604,
        1605,
        1606,
        1607,
        1608,
        1609,
        1610,
        1611,
        1860,
        1861,
        1862,
        1863,
        1864,
        1865,
        1866,
        1867,
        1868,
        1869,
        2108,
        2109,
        2110,
        2111,
        2112,
        2113,
        2114,
        2115,
        2116,
        2117,
        2118,
        2119,
        2120,
        2121,
        2122,
        2123,
        2124,
        2125,
        2126,
        2492,
        2493,
        2494,
        2495,
        2496,
        2497,
        2498,
        2499,
        2500,
        2501,
        2502,
        2503,
        2504,
        2505,
        2506,
        2507,
        2929
      )
  )
  union all
  (
    select
      `comments`.*,
      `depth` + 1 as `depth`,
      concat(`path`,., `comments`.`id`)
    from
      `comments`
      inner join `laravel_cte` on `laravel_cte`.`id` = `comments`.`parent_id`
  )
)
select
  *
from
  `laravel_cte`
where
  `depth` < 2
```

What could be causing this issue? And thank you for this package!

**Comment by staudenmeir** [comment]
What query are you running to get this SQL?

**Comment by jaesung2061** [comment]
This is the query I'm running:

    Post::with('user')->with('comments.descendants')->latest()->paginate(10)

**Comment by staudenmeir** [comment]
Does your `comments` table have a column named `depth`?

**Comment by jaesung2061** [comment]
It does. It is an integer column.

**Comment by staudenmeir** [comment]
The package add its own computed `depth` column to the query and that conflicts with the table's column.

You need to customize it:

```php
class Comment extends Model
{
    use \Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

    public function getDepthName()
    {
        return 'laravel_depth';
    }
}
```

**Comment by jaesung2061** [comment]
That fixed it! Thank you so much!

I do have one more question, though. Is it possible to limit the number of replies per comment and to sort by a constraint such as votes?

I've tried this, but I get an error.

    $posts = Comment::withRecursiveQueryConstraint(function ($q) {
        $q->limit(10);
    }, function () {
        return Post::with('user')->with('comments.descendants')->latest()->paginate(10);
    });

> SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MySQL doesn't yet support 'ORDER BY / LIMIT / SELECT DISTINCT in recursive query block of Common Table Expression'

**Comment by jaesung2061** [comment]
I understand. I'll have to see which one is best suited for my use case. Thank you so much for your help and your packages.

**Comment by staudenmeir** [comment]
I released the package that merges `eloquent-eager-limit` and `laravel-adjacency-list`, but limits on `Descendants` relationships are not supported yet. Due to the nature of `Descendants` queries, not every use case is possible. A query can only work correctly if it's ordered by depth: `orderBy('depth')`/`breadthFirst()`

In your case, the query would select a comment's direct children first, then their children, and so on, until the limit is reached. Does that work for you?

**Comment by jaesung2061** [comment]
Hey @staudenmeir, thanks so much for this. I will take a look at it.

**Comment by staudenmeir** [comment]
Here is the package: https://github.com/staudenmeir/eloquent-eager-limit-x-laravel-adjacency-list

I have added support for limits on `Descendants` relationships in the meantime, but the limitation I mentioned still applies:
https://github.com/staudenmeir/eloquent-eager-limit-x-laravel-adjacency-list#limitations
