### ISSUE TITLE
Sanity check: comments for posts

### ISSUE THREAD

**Issue by mosfetish** [staudenmeir/laravel-adjacency-list#89]
I have a posts table and a comments table. Each post can have many comments and the post itself is effectively the root for all its comments,

Therefore my comments table has fields for: comment.id, comment.parent_id, comment.post_id. When a comment doesn't have a parent (that is, it's a "level 1" comment) I set the parent_id to NULL and set the post_id to the post's id Then I use a constraint for (some) queries to isolate the results to a specific post, such as:

```
$post_id = 113;

$constraint = function ($query) {
    $query->whereNull('parent_id')->where('post_id', $post_id);
};

$comments = Comment::treeOf($constraint)->get()->toTree();

```

Is this the best way to handle this kind of task?

**Comment by staudenmeir** [comment]
Yeah, that's I would do.

**Comment by mosfetish** [comment]
Thanks, Jonas. And thanks for the package.
