### ISSUE TITLE
possible to get a sub tree?

### ISSUE THREAD

**Issue by patrickomeara** [staudenmeir/laravel-adjacency-list#9]
Hi Jonas,

Is it possible to get a sub tree from an existing node?

```php
$node = Node::find(3456);
$node->tree();
```

I assume this would return the same structure that tree does, but only underneath `$node`

Also, is it possible to load children recursively? I originally thought that's what `tree()` would do, but I was wrong, `tree()` returns a flat list.

**Comment by staudenmeir** [comment]
Aren't the `descendants` the subtree?

You can define a recursive children relationship:

```php
class Node extends Model
{
    public function childrenRecursive()
    {
        return $this->children()->with('childrenRecursive');
    }
}
```

**Comment by patrickomeara** [comment]
Yep, I initially thought the tree structure was a nested.

Thanks for your help.
