### ISSUE TITLE
descendantsAndSelf always fetches the Self part ignoring criteria

### ISSUE THREAD

**Issue by pda-code** [staudenmeir/laravel-adjacency-list#90]
Suppose we have as a classic nested structure of Users Group

UserGroup-1
 --- UserGroup-1.1  
 --- UserGroup-1.2

![image](https://user-images.githubusercontent.com/10973438/159907533-dcd684be-bfb8-466e-8099-c9364db6839b.png)

and each `UserGroup::class` have `Roles  `with a classic pivot table

![image](https://user-images.githubusercontent.com/10973438/159907648-8d174274-79a4-4f59-915b-6af690b6fa91.png)

![image](https://user-images.githubusercontent.com/10973438/159907811-f8b18d73-3ef1-4989-a25c-8b7e3af15c80.png)

I want to fetch all the `descendantsAndSelf  `that has a specific role lets say role_id **25670**

![image](https://user-images.githubusercontent.com/10973438/159908615-6d5fd42e-b34a-4cf6-9403-f4b1b2cec49f.png)

Even If `UserGroup-1` does not have any roles it always fetches the `self `part without taken in account the restrictions

**Comment by staudenmeir** [comment]
Can you share some sample data (all three tables) and the expected vs. actual result?

**Comment by pda-code** [comment]
I attached a zip file with an sql of the database (3 tables + sample data) + 2 Eloquent models

[Demo.zip](https://github.com/staudenmeir/laravel-adjacency-list/files/8346524/Demo.zip)

### Running Example

![image](https://user-images.githubusercontent.com/10973438/160033021-a11763bf-37f6-40fa-bb6b-cbcf6e4d250d.png)

### Results
![image](https://user-images.githubusercontent.com/10973438/160033068-49ee7075-192a-4083-bd33-93a92a8f9581.png)

**Comment by staudenmeir** [comment]
The query does behave correctly: Your `whereHas('descendantsAndSelf', ...)` constraint returns all user groups that have role `1` themselves _or_ that have a descendant with that role. In this case, user group `1` is returned because its descendant `2` has that role.

> I want to fetch all the descendantsAndSelf that has a specific role lets say role_id 25670
> Even If UserGroup-1 does not have any roles it always fetches the self part without taken in account the restrictions

The query should only return user group `2`, right? Why should `1` not be returned?

What do you mean by "fetch all the descendantsAndSelf"?

**Comment by pda-code** [comment]
I think of `descendantsAndSelf` a way to fetch a subtree in a flat collection if items.

My basic usage of descendantsAndSelf is 

//<some_id> is the root of the subtree
`UserGroupModel::whereId(<some_id>)->whereHas('descendantsAndSelf', ...)`

meaning I want to return all the models contained in a subtree that match certain criteria.

For Example 'Find all UserGoups that has attached role 'adminstrator' that all are under "Department1" User Group

**Comment by staudenmeir** [comment]
If I understand you correctly, you also need to add the role constraint to the eager loading clause:

```php
->with([
    'descendantsAndSelf' => function($query) {
        $query->whereHas('roles', ...);
    },
)]
```

**Comment by pda-code** [comment]
Thank you very much for your time....

Your code runs as expected and i think i made a interpretation  mistake of what `descendantsAndSelf` means
