### ISSUE TITLE
Show all posts recursively, having Categories + Subcategories.

### ISSUE THREAD

**Issue by podrabinek** [staudenmeir/laravel-adjacency-list#92]
Help me please, what should I do? I want to show all posts recursively, having Categories + Subcategories.

I want to recursively list Posts within each Category, including all parent and self

Should be:

**/category/development/** (2 items)
-- id 23 Learn JS
-- id 24 Learn PHP

**/category/frontend/** (1 item)
-- id 23 Learn Javascript

**/category/backend/** (1 item)
-- id 24 Learn PHP

I have 3 tables:

### categories
| id  | parent_id | slug |
| ------------- | ------------- | ------------- |
| 1  | NULL  | development |
| 11  | 1  | frontend |
| 12  | 1  | backend |

### posts
| id  | title |
| ------------- | ------------- |
| 23  | Learn JS  |
| 24  | Learn PHP  |

### posts_categories
| post_id  | category_id |
| ------------- | ------------- |
| 23  | 11  |
| 24  | 12  |

If I do without recursive relationships, it works (but doesn't show posts for the `category_id = 1`):

--------------------
```php
// Post Model
public function getCategories()
{
    return $this->belongsToMany(Category::class, 'posts_categories');
}

// Category Controller
class CategoryController extends Controller
{

  public function index($id) {

    $items = Post::whereHas('getCategories', function ($query) use ($id) {
        $query->where('category_id', $id);
    })->get();

    return view('welcome', compact('items'));

  }
}

// Routes/web.php
Route::get('/{id}', [CategoryController::class, 'index']);

// Blade
@foreach($items as $item)
  {{ $item->title }}<br>
@endforeach
```
--------------

If I try `belongsToManyOfDescendantsAndSelf` in the Post Model, I get an error about **parent_id**.  Am I missing something? 

```php
// Post Model

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class Post extends Model
{
  use HasFactory, HasRecursiveRelationships;

  public function recursiveCategories()
  {
      return $this->belongsToManyOfDescendantsAndSelf(Category::class, 'posts_categories');
  }

}
```

```php

// Category Controller

$items = Post::whereHas('recursiveCategories', function ($query) use ($id) {
  $query->where('category_id', $id);
})->get();
```

I get 

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'posts.parent_id' in 'on clause'`

and the query is:

```sql
select * from `posts` where exists (with recursive `laravel_cte` as ((select *, 0 as `depth` from `posts` as `laravel_reserved_0` where `laravel_reserved_0`.`id` = `posts`.`id`) union all (select `posts`.*, `depth` + 1 as `depth` from `posts` inner join `laravel_cte` on `laravel_cte`.`id` = `posts`.`parent_id`)) select * from `categories` inner join `posts_categories` on `categories`.`id` = `posts_categories`.`category_id` where `category_id` = 11 and `post_id` in (select `id` from `laravel_cte`))
```

**Comment by podrabinek** [comment]
It's always better to go to sleep.

Apparently, moving the relationship to Category Model helped:

```php
// Category Model

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class Category extends Model
{

    use HasFactory, HasRecursiveRelationships;

    public function recursiveCategories()
    {
        return $this->belongsToManyOfDescendantsAndSelf(Post::class, 'posts_categories');
    }

}
```

```php
// Category Controller

class CategoryController extends Controller
{

    public function index($id) {

            $items = Category::find($id)
            ->recursiveCategories()
            ->get();
    }
}
```

**Comment by podrabinek** [comment]
Oh, no, I get multiple elements :(

**Comment by podrabinek** [comment]
Had to use Spatie's laravel-collection-macros to paginate on collection
```php
            $items = Category::find($id)
            ->recursiveCategories()
            ->get();
            $items = $items->unique()->paginate(5);
```

I also tried this, but got the pagination inconsistency:
```php
            $items = Category::find($id)
            ->recursiveCategories()
            ->distinct('posts_categories.post_id')
            ->paginate();
```

**Comment by staudenmeir** [comment]
> I also tried this, but got the pagination inconsistency:

What inconsistencies did you get?

**Comment by podrabinek** [comment]
Well, I got 4 items on first page, 5 on second and 3 on third with `paginate(5)`, for example. Expected 5, 5, 2

**Comment by staudenmeir** [comment]
Can you log all these pagination queries? Can you provide a database export of the three tables involved?

**Comment by podrabinek** [comment]
Cannot reproduce anymore :( Seems like everything is fine. Thank you so much!

P.S: could you confirm that `->distinct('posts_categories.post_id')` is reasonable for this situation? Looks like it changes nothing

**Comment by staudenmeir** [comment]
`->distinct('posts_categories.post_id')` doesn't have the desired effect because it behaves like `->distinct()` and applies `DISTINCT` to _all_ select columns (not a Laravel issue, that's how SQL works):

```sql
...
select distinct `posts`.*,
                `posts_categories`.`category_id` as `pivot_category_id`,
                `posts_categories`.`post_id`     as `pivot_post_id`
from `posts`
...
```

You get duplicate posts because the query also takes `posts_categories.category_id` into account when determining unique rows.

Distinct queries are even more complicated/troublesome in combination with pagination. Laravel does treat `->distinct('posts_categories.post_id')` and `->distinct()` differently here, but only when counting the number of total results. That's probably the reason for your inconsistencies:

<img width="993" alt="Bildschirmfoto 2022-04-10 um 18 17 58" src="https://user-images.githubusercontent.com/1853169/162629145-c0f444d1-af44-477b-a475-7084bc4148e5.png">

To actually get unique posts, you need to remove `posts_categories.category_id` from the query:

```php
$items = Category::find($id)
            ->recursiveCategories()
            ->getQuery()
            ->select('posts.*')
            ->groupBy('posts.id')
            ->paginate();
```

**Comment by podrabinek** [comment]
@staudenmeir Thank you so much for this explanation, appreciate it

**Comment by staudenmeir** [comment]
Thanks for your donation!

**Comment by podrabinek** [comment]
I've tested on my database with ~10k Posts records, 80 Categories and their respective depth 3, seems like the the query you suggested is too slow:

**377+87 ms**

```php
$items = Category::find($id)
            ->recursiveCategories()
            ->getQuery()
            ->select('posts.*')
            ->groupBy('posts.id')
            ->with('platform:id,slug,name,logo')
            ->paginate();
``` 



<img width="1103" alt="Cleanshot-11-10 14 18" src="https://user-images.githubusercontent.com/2670183/162693880-434cead6-0b74-47da-9390-a88066b0995c.png">



**9.76+1.72ms**

```php
    $recursivePosts = Category::find($category->id)
    ->recursiveCategories()
    ->distinct('posts_categories.post_id')
    ->with('platform:id,slug,name,logo')
    ->paginate(20);
```

<img width="1127" alt="Cleanshot-11-10 12 25" src="https://user-images.githubusercontent.com/2670183/162693540-e5be2373-818c-41f5-aab8-9b9ef95c1a38.png">

**Comment by staudenmeir** [comment]
Can you share the database dump?

**Comment by podrabinek** [comment]
[getyourstudy.gz](https://github.com/staudenmeir/laravel-adjacency-list/files/8463411/getyourstudy.gz)

**Comment by podrabinek** [comment]
Also I have performance issues with ORDER BY updated_at
You can fill the field with random dates and see

```php
update posts set updated_at =
    FROM_UNIXTIME(
        UNIX_TIMESTAMP('2022-04-10 14:53:27') + FLOOR(0 + (RAND() * 86400))
    )
```

**Comment by staudenmeir** [comment]
Try this query:

```php
Category::find($id)
            ->recursiveCategories()
            ->getQuery()
            ->select('posts.*')
            ->distinct('posts.id')
            ->with('platform:id,slug,name,logo')
            ->paginate();
```

It also returns the correct results, but is _much_ faster than the `GROUP BY` query on my machine. From what I know, they are basically the same query and should have a similar performance, but apparently that's not the case here.

**Comment by podrabinek** [comment]
I've kind of sorted it out - the query slows because I have 3 text fields (body, body_short, headline). I'm converting them with the Post Model Attribute, to get one field instead of three (because sometimes `body` is absent, sometimes `body_short`, etc). I don't know, maybe I have to make an aggregated field in the table and not to play with this data on the Model or Controller layer.

**245ms on 10k of posts**:

```php
    $recursivePosts = Category::find($id)
    ->recursiveCategories()
    ->getQuery()
    ->select('posts.id',
        'posts.title',
        'posts.slug',
        'posts.image',
        'posts.platform_id', 
        'posts.duration',
        'posts.flexible_deadline', 
        'posts.lessons_count', 
        'posts.certificate',
        'posts.body',
        'posts.body_short',
        'posts.headline')
    ->distinct('posts.id')
    ->with('platform:id,slug,name,logo')
    ->orderByDesc('posts.id')
    ->paginate(20);
```

**18 ms on 10k of posts**:
```php
    ...
    ->select('posts.id',
        'posts.title',
        'posts.slug',
        'posts.image',
        'posts.platform_id', 
        'posts.duration',
        'posts.flexible_deadline', 
        'posts.lessons_count', 
        'posts.certificate')
    ...
```

But still it bothers me a bit, because there will be 100k of records in the table

**Comment by staudenmeir** [comment]
Did you try `->groupBy()` with this query? In combination with `->orderByDesc('posts.id')`, it's a bit faster for me.

**Comment by podrabinek** [comment]
Yes, it's a bit faster, but the previous query grows in excecution time

Before `groupBy('posts.id')`

![Cleanshot-13-09 20 48](https://user-images.githubusercontent.com/2670183/163121916-e882aff4-c001-4538-814d-ea77a6577da1.png)


After:

![Cleanshot-13-09 22 31](https://user-images.githubusercontent.com/2670183/163122039-7e01f583-daa3-4791-90fd-f4bc08b0cac1.png)

The query:

```php
    $recursivePosts = Category::find($id)
    ->recursiveCategories()
    ->getQuery()
    ->select('posts.id','posts.title','posts.slug','posts.image','posts.platform_id', 'posts.duration','posts.flexible_deadline', 'posts.lessons_count', 'posts.certificate','posts.body', 'posts.body_short', 'posts.headline')
    ->distinct('posts.id')
    ->with('platform:id,slug,name,logo')
    ->groupBy('posts.id')
    ->orderByDesc('posts.id')
    ->paginate(20);
```

**Comment by staudenmeir** [comment]
Did you find a good solution?
