### ISSUE TITLE
Problem with alias

### ISSUE THREAD

**Issue by IMCAgro** [staudenmeir/laravel-adjacency-list#95]
mysql 8.0
php 7.3
Lar 8.75

constraint violation: 1052 Column 'id' in field list is ambiguous

I am trying to filter with constraint

```php 
$constraint = function (Builder $query) use ($self) {
            $self->scopeFilterQuery($query);
        };

return $this->treeOf($constraint,$maxDepth);`
```

Inside my filter query
```php
$org_id = $this->getState('filter.org_id');
if($org_id > 0) {
      $query->where('restaurant_id',$org_id);
}

$org_uniq = $this->getState('filter.org_uniq_id');
if(!empty($org_uniq)) {
    $query
        ->leftJoin('restaurants', function (JoinClause  $join) {
            $join
                ->on('restaurants.id', '=', 'categories.restaurant_id');
        })
    ->where('restaurants.uniq_id','=',$org_uniq);
}
```

Query starts without alias
```
(SQL: with recursive `api_laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from
```

**Comment by IMCAgro** [comment]
Besides - same problem if i want use aliases in table.

**Comment by staudenmeir** [comment]
Please share the whole error message.

**Comment by IMCAgro** [comment]
Oh sorry - i had fixed it( its another query -> but the same problem
 
I had made another trait - where select *, 0 as `depth`, cast(`id` as char(65535) this builds - and add alias for it

Query without alias is build here
```php
 protected function getInitialQuery(ExpressionGrammar $grammar, callable $constraint, $initialDepth, $from)
```


Its with error
`
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: with recursive `api_laravel_cte` as ((select *, 0 as `depth`, cast(`id` as char(65535)) as `path` from `api_ksenmart_categories` left join `api_providers` on `api_providers`.`type` = glovo left join `api_providers_visible` on `api_providers_visible`.`item_id` = `api_ksenmart_categories`.`id` and `api_providers`.`id` = `api_providers_visible`.`provider_id` and `api_providers_visible`.`item_type` = category where `api_ksenmart_categories`.`client_id` = 20 and `api_ksenmart_categories`.`is_upd` = 1 and (`api_providers_visible`.`is_visible` = 1 or `api_providers_visible`.`is_visible` is null) and exists (select * from `api_ksenmart_restaurants` where `api_ksenmart_categories`.`restaurant_id` = `api_ksenmart_restaurants`.`id` and `uniq_id` = 100000000 and `provider` in (poster_org, fo_org, aiko, g_org) and `client_id` = 20) and `api_ksenmart_categories`.`parent_id` = 0) union all (select `api_ksenmart_categories`.*, `depth` + 1 as `depth`, concat(`path`, ., `api_ksenmart_categories`.`id`) from `api_ksenmart_categories` inner join `api_laravel_cte` on `api_laravel_cte`.`id` = `api_ksenmart_categories`.`parent_id`)) select `api_laravel_cte`.*, `api_providers`.`name` as `prov_name`, `api_providers`.`type` as `prov_type` from `api_laravel_cte` left join `api_providers` on `api_providers`.`id` = `api_laravel_cte`.`provider_id` where `api_laravel_cte`.`is_upd` = 1 and exists (select * from `api_ksenmart_restaurants` where `api_laravel_cte`.`restaurant_id` = `api_ksenmart_restaurants`.`id` and `uniq_id` = 100000000 and `provider` in (poster_org, fo_org, aiko, g_org) and `client_id` = 20) and `client_id` = 20 order by `ordering` asc, `id` asc)
`

**Comment by IMCAgro** [comment]
great work - besides!
