### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::toTree does not exist

### ISSUE THREAD

**Issue by handhikadj** [staudenmeir/laravel-adjacency-list#98]
code this `\App\Models\Category::tree()->get()->toTree()` got that error

**Comment by staudenmeir** [comment]
What versions of the package and Laravel are you using?

**Comment by MUHAMMADSiyab** [comment]
Same issue, using laravel version ^7.24 and PHP 7.4. The package version is ^1.0

**Comment by staudenmeir** [comment]
What's the result of `composer show staudenmeir/laravel-adjacency-list`?

**Comment by MUHAMMADSiyab** [comment]
It's showing version 1.5

**Comment by MUHAMMADSiyab** [comment]
name     : staudenmeir/laravel-adjacency-list
descrip. : Recursive Laravel Eloquent relationships with CTEs
keywords : 
versions : * v1.5
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/staudenmeir/laravel-adjacency-list.git 4e5334c0c7db90b9678a22d9228da10709692c71
dist     : [zip] https://api.github.com/repos/staudenmeir/laravel-adjacency-list/zipball/4e5334c0c7db90b9678a22d9228da10709692c71 4e5334c0c7db90b9678a22d9228da10709692c71
path     : /home/siyabdev/projects/NSMS/vendor/staudenmeir/laravel-adjacency-list
names    : staudenmeir/laravel-adjacency-list

support
issues : https://github.com/staudenmeir/laravel-adjacency-list/issues
source : https://github.com/staudenmeir/laravel-adjacency-list/tree/v1.5

autoload
psr-4
Staudenmeir\LaravelAdjacencyList\ => src/

requires
illuminate/database ^7.0
php ^7.2.5
staudenmeir/laravel-cte ^1.3

requires (dev)
laravel/homestead ^10.0
phpunit/phpunit ^8.5

**Comment by staudenmeir** [comment]
I released `v1.5.1` that brings `toTree()` to Laravel 7.

**Comment by MUHAMMADSiyab** [comment]
@staudenmeir Glad it solved my problem 😊

**Comment by handhikadj** [comment]
> What versions of the package and Laravel are you using?

staudenmeir/laravel-adjacency-list v1.3.2
Laravel v6.20.44

**Comment by staudenmeir** [comment]
I released `v1.3.3` that brings `toTree()` to Laravel 6.

**Comment by handhikadj** [comment]
thanks. updated code: `return \App\Models\Category::get()->toTree();`
