### ISSUE TITLE
Filter all categories by column

### ISSUE THREAD

**Issue by jefferose** [staudenmeir/laravel-adjacency-list#99]
I'm building a site that has recursive categories called "categories" and each has a flag called 'is_visible' that's either 0 or 1. I need to pull back the tree with only visible categories, but can't seem to make it work.

This pulls the whole tree, which is great.
`$categories = Category::with('wordlists')->tree()->orderBy('title')->get()->toTree();`

Based on the docs, I thought I could do this:
`        $constraint = function ($query) {
            $query->where('is_visible', 1);
        };

      $categories = Category::with('wordlists')->treeOf($constraint)->orderBy('title')->get()->toTree();
`
This returns the tree, but duplicates stuff all over the place. I'm sure it's something simple, but I can't figure it out.

**Comment by staudenmeir** [comment]
Do you mean like this?

```php
$categories = Category::with('wordlists')->tree()->where('is_visible', 1)->orderBy('title')->get()->toTree();
```

**Comment by jefferose** [comment]
Of course it was just a matter of syntax! Thanks for your help.
